// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ttab/wires/v1/service.proto

package wiresv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ttab/elephant-tt-api/ttab/wires/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RssFeedServiceName is the fully-qualified name of the RssFeedService service.
	RssFeedServiceName = "ttab.wires.v1.RssFeedService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RssFeedServiceGetAllFeedsProcedure is the fully-qualified name of the RssFeedService's
	// GetAllFeeds RPC.
	RssFeedServiceGetAllFeedsProcedure = "/ttab.wires.v1.RssFeedService/GetAllFeeds"
	// RssFeedServiceUpdateFeedProcedure is the fully-qualified name of the RssFeedService's UpdateFeed
	// RPC.
	RssFeedServiceUpdateFeedProcedure = "/ttab.wires.v1.RssFeedService/UpdateFeed"
	// RssFeedServiceDeleteFeedProcedure is the fully-qualified name of the RssFeedService's DeleteFeed
	// RPC.
	RssFeedServiceDeleteFeedProcedure = "/ttab.wires.v1.RssFeedService/DeleteFeed"
)

// RssFeedServiceClient is a client for the ttab.wires.v1.RssFeedService service.
type RssFeedServiceClient interface {
	GetAllFeeds(context.Context, *connect.Request[v1.GetAllFeedsRequest]) (*connect.Response[v1.GetAllFeedsResponse], error)
	UpdateFeed(context.Context, *connect.Request[v1.UpdateFeedRequest]) (*connect.Response[v1.UpdateFeedResponse], error)
	DeleteFeed(context.Context, *connect.Request[v1.DeleteFeedRequest]) (*connect.Response[v1.DeleteFeedResponse], error)
}

// NewRssFeedServiceClient constructs a client for the ttab.wires.v1.RssFeedService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRssFeedServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RssFeedServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	rssFeedServiceMethods := v1.File_ttab_wires_v1_service_proto.Services().ByName("RssFeedService").Methods()
	return &rssFeedServiceClient{
		getAllFeeds: connect.NewClient[v1.GetAllFeedsRequest, v1.GetAllFeedsResponse](
			httpClient,
			baseURL+RssFeedServiceGetAllFeedsProcedure,
			connect.WithSchema(rssFeedServiceMethods.ByName("GetAllFeeds")),
			connect.WithClientOptions(opts...),
		),
		updateFeed: connect.NewClient[v1.UpdateFeedRequest, v1.UpdateFeedResponse](
			httpClient,
			baseURL+RssFeedServiceUpdateFeedProcedure,
			connect.WithSchema(rssFeedServiceMethods.ByName("UpdateFeed")),
			connect.WithClientOptions(opts...),
		),
		deleteFeed: connect.NewClient[v1.DeleteFeedRequest, v1.DeleteFeedResponse](
			httpClient,
			baseURL+RssFeedServiceDeleteFeedProcedure,
			connect.WithSchema(rssFeedServiceMethods.ByName("DeleteFeed")),
			connect.WithClientOptions(opts...),
		),
	}
}

// rssFeedServiceClient implements RssFeedServiceClient.
type rssFeedServiceClient struct {
	getAllFeeds *connect.Client[v1.GetAllFeedsRequest, v1.GetAllFeedsResponse]
	updateFeed  *connect.Client[v1.UpdateFeedRequest, v1.UpdateFeedResponse]
	deleteFeed  *connect.Client[v1.DeleteFeedRequest, v1.DeleteFeedResponse]
}

// GetAllFeeds calls ttab.wires.v1.RssFeedService.GetAllFeeds.
func (c *rssFeedServiceClient) GetAllFeeds(ctx context.Context, req *connect.Request[v1.GetAllFeedsRequest]) (*connect.Response[v1.GetAllFeedsResponse], error) {
	return c.getAllFeeds.CallUnary(ctx, req)
}

// UpdateFeed calls ttab.wires.v1.RssFeedService.UpdateFeed.
func (c *rssFeedServiceClient) UpdateFeed(ctx context.Context, req *connect.Request[v1.UpdateFeedRequest]) (*connect.Response[v1.UpdateFeedResponse], error) {
	return c.updateFeed.CallUnary(ctx, req)
}

// DeleteFeed calls ttab.wires.v1.RssFeedService.DeleteFeed.
func (c *rssFeedServiceClient) DeleteFeed(ctx context.Context, req *connect.Request[v1.DeleteFeedRequest]) (*connect.Response[v1.DeleteFeedResponse], error) {
	return c.deleteFeed.CallUnary(ctx, req)
}

// RssFeedServiceHandler is an implementation of the ttab.wires.v1.RssFeedService service.
type RssFeedServiceHandler interface {
	GetAllFeeds(context.Context, *connect.Request[v1.GetAllFeedsRequest]) (*connect.Response[v1.GetAllFeedsResponse], error)
	UpdateFeed(context.Context, *connect.Request[v1.UpdateFeedRequest]) (*connect.Response[v1.UpdateFeedResponse], error)
	DeleteFeed(context.Context, *connect.Request[v1.DeleteFeedRequest]) (*connect.Response[v1.DeleteFeedResponse], error)
}

// NewRssFeedServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRssFeedServiceHandler(svc RssFeedServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	rssFeedServiceMethods := v1.File_ttab_wires_v1_service_proto.Services().ByName("RssFeedService").Methods()
	rssFeedServiceGetAllFeedsHandler := connect.NewUnaryHandler(
		RssFeedServiceGetAllFeedsProcedure,
		svc.GetAllFeeds,
		connect.WithSchema(rssFeedServiceMethods.ByName("GetAllFeeds")),
		connect.WithHandlerOptions(opts...),
	)
	rssFeedServiceUpdateFeedHandler := connect.NewUnaryHandler(
		RssFeedServiceUpdateFeedProcedure,
		svc.UpdateFeed,
		connect.WithSchema(rssFeedServiceMethods.ByName("UpdateFeed")),
		connect.WithHandlerOptions(opts...),
	)
	rssFeedServiceDeleteFeedHandler := connect.NewUnaryHandler(
		RssFeedServiceDeleteFeedProcedure,
		svc.DeleteFeed,
		connect.WithSchema(rssFeedServiceMethods.ByName("DeleteFeed")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ttab.wires.v1.RssFeedService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RssFeedServiceGetAllFeedsProcedure:
			rssFeedServiceGetAllFeedsHandler.ServeHTTP(w, r)
		case RssFeedServiceUpdateFeedProcedure:
			rssFeedServiceUpdateFeedHandler.ServeHTTP(w, r)
		case RssFeedServiceDeleteFeedProcedure:
			rssFeedServiceDeleteFeedHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRssFeedServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRssFeedServiceHandler struct{}

func (UnimplementedRssFeedServiceHandler) GetAllFeeds(context.Context, *connect.Request[v1.GetAllFeedsRequest]) (*connect.Response[v1.GetAllFeedsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.wires.v1.RssFeedService.GetAllFeeds is not implemented"))
}

func (UnimplementedRssFeedServiceHandler) UpdateFeed(context.Context, *connect.Request[v1.UpdateFeedRequest]) (*connect.Response[v1.UpdateFeedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.wires.v1.RssFeedService.UpdateFeed is not implemented"))
}

func (UnimplementedRssFeedServiceHandler) DeleteFeed(context.Context, *connect.Request[v1.DeleteFeedRequest]) (*connect.Response[v1.DeleteFeedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.wires.v1.RssFeedService.DeleteFeed is not implemented"))
}
