// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v4.24.4
// source: wires/service.proto

package wires

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedType int32

const (
	FeedType_TYPE_UNKNOWN      FeedType = 0
	FeedType_TYPE_ARTICLE      FeedType = 1
	FeedType_TYPE_PRESSRELEASE FeedType = 2
)

// Enum value maps for FeedType.
var (
	FeedType_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "TYPE_ARTICLE",
		2: "TYPE_PRESSRELEASE",
	}
	FeedType_value = map[string]int32{
		"TYPE_UNKNOWN":      0,
		"TYPE_ARTICLE":      1,
		"TYPE_PRESSRELEASE": 2,
	}
)

func (x FeedType) Enum() *FeedType {
	p := new(FeedType)
	*p = x
	return p
}

func (x FeedType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedType) Descriptor() protoreflect.EnumDescriptor {
	return file_wires_service_proto_enumTypes[0].Descriptor()
}

func (FeedType) Type() protoreflect.EnumType {
	return &file_wires_service_proto_enumTypes[0]
}

func (x FeedType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedType.Descriptor instead.
func (FeedType) EnumDescriptor() ([]byte, []int) {
	return file_wires_service_proto_rawDescGZIP(), []int{0}
}

type GetAllFeedsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The page number to retrieve.
	// Defaults to 0 if not specified, representing the first page.
	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// The number of items to include in each page of results.
	// Defaults to 10 if not specified.
	PageSize      int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllFeedsRequest) Reset() {
	*x = GetAllFeedsRequest{}
	mi := &file_wires_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllFeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFeedsRequest) ProtoMessage() {}

func (x *GetAllFeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wires_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFeedsRequest.ProtoReflect.Descriptor instead.
func (*GetAllFeedsRequest) Descriptor() ([]byte, []int) {
	return file_wires_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllFeedsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllFeedsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetAllFeedsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current page number of the results being returned.
	// Reflects the "page" value from the request.
	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// The page number of the next set of results, or -1 if there are no more pages.
	NextPage int64 `protobuf:"varint,2,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"`
	// The list of feeds available on the current page sorted by title.
	Feeds         []*Feed `protobuf:"bytes,3,rep,name=feeds,proto3" json:"feeds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllFeedsResponse) Reset() {
	*x = GetAllFeedsResponse{}
	mi := &file_wires_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllFeedsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFeedsResponse) ProtoMessage() {}

func (x *GetAllFeedsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wires_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFeedsResponse.ProtoReflect.Descriptor instead.
func (*GetAllFeedsResponse) Descriptor() ([]byte, []int) {
	return file_wires_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllFeedsResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllFeedsResponse) GetNextPage() int64 {
	if x != nil {
		return x.NextPage
	}
	return 0
}

func (x *GetAllFeedsResponse) GetFeeds() []*Feed {
	if x != nil {
		return x.Feeds
	}
	return nil
}

type Feed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUIDv5 of the feed, created by using the url.
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// The human-readable title of the feed.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// The URL from which the feed is sourced.
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// Feed type enum. "TYPE_ARTICLE" (default) and "TYPE_PRESSRELEASE".
	// Use "TYPE_ARTICLE" and "type_exceptions" field for feeds with mixed types.
	Type FeedType `protobuf:"varint,4,opt,name=type,proto3,enum=ttab.wires.FeedType" json:"type,omitempty"`
	// A list of exceptions for fine-grained type categorization of feed items.
	// Primarily used for feeds with mixed content types.
	TypeExceptions []*ExceptionRule `protobuf:"bytes,10,rep,name=type_exceptions,json=typeExceptions,proto3" json:"type_exceptions,omitempty"`
	// Code representing the section of the feed.
	// Possible values: ["inr", "utr", "eko", "spt", "nojkul"].
	SectionCode string `protobuf:"bytes,5,opt,name=section_code,json=sectionCode,proto3" json:"section_code,omitempty"`
	// Time interval (in seconds) specifying how frequently the feed should be refreshed/imported.
	RefreshInterval int64 `protobuf:"varint,6,opt,name=refresh_interval,json=refreshInterval,proto3" json:"refresh_interval,omitempty"`
	// Language used in the feed. (BCP 47 standard)
	Language string `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	// The timestamp (ISO 8601 format) of the last time the feed was checked for updates.
	// This field is managed internally by the system and is not settable by clients in update requests.
	LastChecked string `protobuf:"bytes,8,opt,name=last_checked,json=lastChecked,proto3" json:"last_checked,omitempty"`
	// The timestamp (ISO 8601 format) of the most recent publication detected in the feed.
	// This field is managed internally by the system and is not settable by clients in update requests.
	LastPublication string `protobuf:"bytes,9,opt,name=last_publication,json=lastPublication,proto3" json:"last_publication,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Feed) Reset() {
	*x = Feed{}
	mi := &file_wires_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feed) ProtoMessage() {}

func (x *Feed) ProtoReflect() protoreflect.Message {
	mi := &file_wires_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feed.ProtoReflect.Descriptor instead.
func (*Feed) Descriptor() ([]byte, []int) {
	return file_wires_service_proto_rawDescGZIP(), []int{2}
}

func (x *Feed) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Feed) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Feed) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Feed) GetType() FeedType {
	if x != nil {
		return x.Type
	}
	return FeedType_TYPE_UNKNOWN
}

func (x *Feed) GetTypeExceptions() []*ExceptionRule {
	if x != nil {
		return x.TypeExceptions
	}
	return nil
}

func (x *Feed) GetSectionCode() string {
	if x != nil {
		return x.SectionCode
	}
	return ""
}

func (x *Feed) GetRefreshInterval() int64 {
	if x != nil {
		return x.RefreshInterval
	}
	return 0
}

func (x *Feed) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Feed) GetLastChecked() string {
	if x != nil {
		return x.LastChecked
	}
	return ""
}

func (x *Feed) GetLastPublication() string {
	if x != nil {
		return x.LastPublication
	}
	return ""
}

// One or both fileds can be used in a rule.
// If one of the fields in a rule matches a feed item, the exception is applied (logical OR).
type ExceptionRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A regex pattern to match against feed item titles.
	// Example: "^PRESS:" to match titles starting with "PRESS:".
	TitlePattern string `protobuf:"bytes,1,opt,name=title_pattern,json=titlePattern,proto3" json:"title_pattern,omitempty"`
	// A category to associate with feed items that match the title pattern.
	// Example: "Pressmeddelande" or "Pressrelease".
	HasCategory   string `protobuf:"bytes,2,opt,name=has_category,json=hasCategory,proto3" json:"has_category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExceptionRule) Reset() {
	*x = ExceptionRule{}
	mi := &file_wires_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExceptionRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExceptionRule) ProtoMessage() {}

func (x *ExceptionRule) ProtoReflect() protoreflect.Message {
	mi := &file_wires_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExceptionRule.ProtoReflect.Descriptor instead.
func (*ExceptionRule) Descriptor() ([]byte, []int) {
	return file_wires_service_proto_rawDescGZIP(), []int{3}
}

func (x *ExceptionRule) GetTitlePattern() string {
	if x != nil {
		return x.TitlePattern
	}
	return ""
}

func (x *ExceptionRule) GetHasCategory() string {
	if x != nil {
		return x.HasCategory
	}
	return ""
}

type UpdateFeedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The feed object containing the updated data.
	// All fields must be set except intenally mangaged fields.
	Feed          *Feed `protobuf:"bytes,1,opt,name=feed,proto3" json:"feed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFeedRequest) Reset() {
	*x = UpdateFeedRequest{}
	mi := &file_wires_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFeedRequest) ProtoMessage() {}

func (x *UpdateFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wires_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFeedRequest.ProtoReflect.Descriptor instead.
func (*UpdateFeedRequest) Descriptor() ([]byte, []int) {
	return file_wires_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateFeedRequest) GetFeed() *Feed {
	if x != nil {
		return x.Feed
	}
	return nil
}

type UpdateFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFeedResponse) Reset() {
	*x = UpdateFeedResponse{}
	mi := &file_wires_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFeedResponse) ProtoMessage() {}

func (x *UpdateFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wires_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFeedResponse.ProtoReflect.Descriptor instead.
func (*UpdateFeedResponse) Descriptor() ([]byte, []int) {
	return file_wires_service_proto_rawDescGZIP(), []int{5}
}

type DeleteFeedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUIDv5 of the feed, created by using the url.
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFeedRequest) Reset() {
	*x = DeleteFeedRequest{}
	mi := &file_wires_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFeedRequest) ProtoMessage() {}

func (x *DeleteFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wires_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFeedRequest.ProtoReflect.Descriptor instead.
func (*DeleteFeedRequest) Descriptor() ([]byte, []int) {
	return file_wires_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFeedRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DeleteFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFeedResponse) Reset() {
	*x = DeleteFeedResponse{}
	mi := &file_wires_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFeedResponse) ProtoMessage() {}

func (x *DeleteFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wires_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFeedResponse.ProtoReflect.Descriptor instead.
func (*DeleteFeedResponse) Descriptor() ([]byte, []int) {
	return file_wires_service_proto_rawDescGZIP(), []int{7}
}

var File_wires_service_proto protoreflect.FileDescriptor

var file_wires_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x77, 0x69, 0x72, 0x65, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x77, 0x69, 0x72, 0x65,
	0x73, 0x22, 0x45, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x65, 0x65, 0x64, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x6e, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x46, 0x65, 0x65, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65,
	0x12, 0x26, 0x0a, 0x05, 0x66, 0x65, 0x65, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x65,
	0x64, 0x52, 0x05, 0x66, 0x65, 0x65, 0x64, 0x73, 0x22, 0xe8, 0x02, 0x0a, 0x04, 0x46, 0x65, 0x65,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x28, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x74, 0x74,
	0x61, 0x62, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x42, 0x0a, 0x0f, 0x74, 0x79, 0x70, 0x65, 0x5f,
	0x65, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x73, 0x2e, 0x45, 0x78,
	0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x0e, 0x74, 0x79, 0x70,
	0x65, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x73,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x29,
	0x0a, 0x10, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76,
	0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x61, 0x73,
	0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74,
	0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x57, 0x0a, 0x0d, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x75, 0x6c, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x5f, 0x70, 0x61,
	0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x68, 0x61, 0x73,
	0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x68, 0x61, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x39, 0x0a, 0x11,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x24, 0x0a, 0x04, 0x66, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x65,
	0x64, 0x52, 0x04, 0x66, 0x65, 0x65, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x27, 0x0a,
	0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x45, 0x0a, 0x08,
	0x46, 0x65, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x41, 0x52, 0x54, 0x49, 0x43, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x52, 0x45, 0x53, 0x53, 0x52, 0x45, 0x4c, 0x45, 0x41, 0x53,
	0x45, 0x10, 0x02, 0x32, 0xf3, 0x01, 0x0a, 0x07, 0x52, 0x73, 0x73, 0x46, 0x65, 0x65, 0x64, 0x12,
	0x4e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x65, 0x65, 0x64, 0x73, 0x12, 0x1e,
	0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x46, 0x65, 0x65, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x46, 0x65, 0x65, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4b, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x65, 0x65, 0x64, 0x12, 0x1d, 0x2e,
	0x74, 0x74, 0x61, 0x62, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x74,
	0x74, 0x61, 0x62, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0a,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x65, 0x65, 0x64, 0x12, 0x1d, 0x2e, 0x74, 0x74, 0x61,
	0x62, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x65,
	0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x74, 0x74, 0x61, 0x62,
	0x2e, 0x77, 0x69, 0x72, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x65, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x74, 0x61, 0x62, 0x2f, 0x65, 0x6c, 0x65,
	0x70, 0x68, 0x61, 0x6e, 0x74, 0x2d, 0x74, 0x74, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x69, 0x72,
	0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wires_service_proto_rawDescOnce sync.Once
	file_wires_service_proto_rawDescData = file_wires_service_proto_rawDesc
)

func file_wires_service_proto_rawDescGZIP() []byte {
	file_wires_service_proto_rawDescOnce.Do(func() {
		file_wires_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_wires_service_proto_rawDescData)
	})
	return file_wires_service_proto_rawDescData
}

var file_wires_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wires_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_wires_service_proto_goTypes = []any{
	(FeedType)(0),               // 0: ttab.wires.FeedType
	(*GetAllFeedsRequest)(nil),  // 1: ttab.wires.GetAllFeedsRequest
	(*GetAllFeedsResponse)(nil), // 2: ttab.wires.GetAllFeedsResponse
	(*Feed)(nil),                // 3: ttab.wires.Feed
	(*ExceptionRule)(nil),       // 4: ttab.wires.ExceptionRule
	(*UpdateFeedRequest)(nil),   // 5: ttab.wires.UpdateFeedRequest
	(*UpdateFeedResponse)(nil),  // 6: ttab.wires.UpdateFeedResponse
	(*DeleteFeedRequest)(nil),   // 7: ttab.wires.DeleteFeedRequest
	(*DeleteFeedResponse)(nil),  // 8: ttab.wires.DeleteFeedResponse
}
var file_wires_service_proto_depIdxs = []int32{
	3, // 0: ttab.wires.GetAllFeedsResponse.feeds:type_name -> ttab.wires.Feed
	0, // 1: ttab.wires.Feed.type:type_name -> ttab.wires.FeedType
	4, // 2: ttab.wires.Feed.type_exceptions:type_name -> ttab.wires.ExceptionRule
	3, // 3: ttab.wires.UpdateFeedRequest.feed:type_name -> ttab.wires.Feed
	1, // 4: ttab.wires.RssFeed.GetAllFeeds:input_type -> ttab.wires.GetAllFeedsRequest
	5, // 5: ttab.wires.RssFeed.UpdateFeed:input_type -> ttab.wires.UpdateFeedRequest
	7, // 6: ttab.wires.RssFeed.DeleteFeed:input_type -> ttab.wires.DeleteFeedRequest
	2, // 7: ttab.wires.RssFeed.GetAllFeeds:output_type -> ttab.wires.GetAllFeedsResponse
	6, // 8: ttab.wires.RssFeed.UpdateFeed:output_type -> ttab.wires.UpdateFeedResponse
	8, // 9: ttab.wires.RssFeed.DeleteFeed:output_type -> ttab.wires.DeleteFeedResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_wires_service_proto_init() }
func file_wires_service_proto_init() {
	if File_wires_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wires_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wires_service_proto_goTypes,
		DependencyIndexes: file_wires_service_proto_depIdxs,
		EnumInfos:         file_wires_service_proto_enumTypes,
		MessageInfos:      file_wires_service_proto_msgTypes,
	}.Build()
	File_wires_service_proto = out.File
	file_wires_service_proto_rawDesc = nil
	file_wires_service_proto_goTypes = nil
	file_wires_service_proto_depIdxs = nil
}
