// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: wires/service.proto

package wires

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedType int32

const (
	FeedType_TYPE_UNKNOWN      FeedType = 0
	FeedType_TYPE_ARTICLE      FeedType = 1
	FeedType_TYPE_PRESSRELEASE FeedType = 2
)

// Enum value maps for FeedType.
var (
	FeedType_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "TYPE_ARTICLE",
		2: "TYPE_PRESSRELEASE",
	}
	FeedType_value = map[string]int32{
		"TYPE_UNKNOWN":      0,
		"TYPE_ARTICLE":      1,
		"TYPE_PRESSRELEASE": 2,
	}
)

func (x FeedType) Enum() *FeedType {
	p := new(FeedType)
	*p = x
	return p
}

func (x FeedType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedType) Descriptor() protoreflect.EnumDescriptor {
	return file_wires_service_proto_enumTypes[0].Descriptor()
}

func (FeedType) Type() protoreflect.EnumType {
	return &file_wires_service_proto_enumTypes[0]
}

func (x FeedType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedType.Descriptor instead.
func (FeedType) EnumDescriptor() ([]byte, []int) {
	return file_wires_service_proto_rawDescGZIP(), []int{0}
}

type GetAllFeedsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The page number to retrieve.
	// Defaults to 0 if not specified, representing the first page.
	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// The number of items to include in each page of results.
	// Defaults to 10 if not specified.
	PageSize      int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllFeedsRequest) Reset() {
	*x = GetAllFeedsRequest{}
	mi := &file_wires_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllFeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFeedsRequest) ProtoMessage() {}

func (x *GetAllFeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wires_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFeedsRequest.ProtoReflect.Descriptor instead.
func (*GetAllFeedsRequest) Descriptor() ([]byte, []int) {
	return file_wires_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllFeedsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllFeedsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetAllFeedsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current page number of the results being returned.
	// Reflects the "page" value from the request.
	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// The page number of the next set of results, or -1 if there are no more pages.
	NextPage int64 `protobuf:"varint,2,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"`
	// The list of feeds available on the current page sorted by title.
	Feeds         []*Feed `protobuf:"bytes,3,rep,name=feeds,proto3" json:"feeds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllFeedsResponse) Reset() {
	*x = GetAllFeedsResponse{}
	mi := &file_wires_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllFeedsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFeedsResponse) ProtoMessage() {}

func (x *GetAllFeedsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wires_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFeedsResponse.ProtoReflect.Descriptor instead.
func (*GetAllFeedsResponse) Descriptor() ([]byte, []int) {
	return file_wires_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllFeedsResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllFeedsResponse) GetNextPage() int64 {
	if x != nil {
		return x.NextPage
	}
	return 0
}

func (x *GetAllFeedsResponse) GetFeeds() []*Feed {
	if x != nil {
		return x.Feeds
	}
	return nil
}

type Feed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUIDv5 of the feed, created by using the url.
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// The human-readable title of the feed.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// The URL from which the feed is sourced.
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// Feed type enum. "TYPE_ARTICLE" (default) and "TYPE_PRESSRELEASE".
	// Use "TYPE_ARTICLE" and "type_exceptions" field for feeds with mixed types.
	Type FeedType `protobuf:"varint,4,opt,name=type,proto3,enum=ttab.wires.FeedType" json:"type,omitempty"`
	// A list of exceptions for fine-grained type categorization of feed items.
	// Primarily used for feeds with mixed content types.
	TypeExceptions []*ExceptionRule `protobuf:"bytes,10,rep,name=type_exceptions,json=typeExceptions,proto3" json:"type_exceptions,omitempty"`
	// Code representing the section of the feed.
	// Possible values: ["inr", "utr", "eko", "spt", "nojkul"].
	SectionCode string `protobuf:"bytes,5,opt,name=section_code,json=sectionCode,proto3" json:"section_code,omitempty"`
	// Time interval (in seconds) specifying how frequently the feed should be refreshed/imported.
	RefreshInterval int64 `protobuf:"varint,6,opt,name=refresh_interval,json=refreshInterval,proto3" json:"refresh_interval,omitempty"`
	// Language used in the feed. (BCP 47 standard)
	Language string `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	// The timestamp (ISO 8601 format) of the last time the feed was checked for updates.
	// This field is managed internally by the system and is not settable by clients in update requests.
	LastChecked string `protobuf:"bytes,8,opt,name=last_checked,json=lastChecked,proto3" json:"last_checked,omitempty"`
	// The timestamp (ISO 8601 format) of the most recent publication detected in the feed.
	// This field is managed internally by the system and is not settable by clients in update requests.
	LastPublication string `protobuf:"bytes,9,opt,name=last_publication,json=lastPublication,proto3" json:"last_publication,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Feed) Reset() {
	*x = Feed{}
	mi := &file_wires_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feed) ProtoMessage() {}

func (x *Feed) ProtoReflect() protoreflect.Message {
	mi := &file_wires_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feed.ProtoReflect.Descriptor instead.
func (*Feed) Descriptor() ([]byte, []int) {
	return file_wires_service_proto_rawDescGZIP(), []int{2}
}

func (x *Feed) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Feed) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Feed) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Feed) GetType() FeedType {
	if x != nil {
		return x.Type
	}
	return FeedType_TYPE_UNKNOWN
}

func (x *Feed) GetTypeExceptions() []*ExceptionRule {
	if x != nil {
		return x.TypeExceptions
	}
	return nil
}

func (x *Feed) GetSectionCode() string {
	if x != nil {
		return x.SectionCode
	}
	return ""
}

func (x *Feed) GetRefreshInterval() int64 {
	if x != nil {
		return x.RefreshInterval
	}
	return 0
}

func (x *Feed) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Feed) GetLastChecked() string {
	if x != nil {
		return x.LastChecked
	}
	return ""
}

func (x *Feed) GetLastPublication() string {
	if x != nil {
		return x.LastPublication
	}
	return ""
}

// One or both fileds can be used in a rule.
// If one of the fields in a rule matches a feed item, the exception is applied (logical OR).
type ExceptionRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A regex pattern to match against feed item titles.
	// Example: "^PRESS:" to match titles starting with "PRESS:".
	TitlePattern string `protobuf:"bytes,1,opt,name=title_pattern,json=titlePattern,proto3" json:"title_pattern,omitempty"`
	// A category to associate with feed items that match the title pattern.
	// Example: "Pressmeddelande" or "Pressrelease".
	HasCategory   string `protobuf:"bytes,2,opt,name=has_category,json=hasCategory,proto3" json:"has_category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExceptionRule) Reset() {
	*x = ExceptionRule{}
	mi := &file_wires_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExceptionRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExceptionRule) ProtoMessage() {}

func (x *ExceptionRule) ProtoReflect() protoreflect.Message {
	mi := &file_wires_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExceptionRule.ProtoReflect.Descriptor instead.
func (*ExceptionRule) Descriptor() ([]byte, []int) {
	return file_wires_service_proto_rawDescGZIP(), []int{3}
}

func (x *ExceptionRule) GetTitlePattern() string {
	if x != nil {
		return x.TitlePattern
	}
	return ""
}

func (x *ExceptionRule) GetHasCategory() string {
	if x != nil {
		return x.HasCategory
	}
	return ""
}

type UpdateFeedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The feed object containing the updated data.
	// All fields must be set except intenally mangaged fields.
	Feed          *Feed `protobuf:"bytes,1,opt,name=feed,proto3" json:"feed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFeedRequest) Reset() {
	*x = UpdateFeedRequest{}
	mi := &file_wires_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFeedRequest) ProtoMessage() {}

func (x *UpdateFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wires_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFeedRequest.ProtoReflect.Descriptor instead.
func (*UpdateFeedRequest) Descriptor() ([]byte, []int) {
	return file_wires_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateFeedRequest) GetFeed() *Feed {
	if x != nil {
		return x.Feed
	}
	return nil
}

type UpdateFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFeedResponse) Reset() {
	*x = UpdateFeedResponse{}
	mi := &file_wires_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFeedResponse) ProtoMessage() {}

func (x *UpdateFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wires_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFeedResponse.ProtoReflect.Descriptor instead.
func (*UpdateFeedResponse) Descriptor() ([]byte, []int) {
	return file_wires_service_proto_rawDescGZIP(), []int{5}
}

type DeleteFeedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUIDv5 of the feed, created by using the url.
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFeedRequest) Reset() {
	*x = DeleteFeedRequest{}
	mi := &file_wires_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFeedRequest) ProtoMessage() {}

func (x *DeleteFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wires_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFeedRequest.ProtoReflect.Descriptor instead.
func (*DeleteFeedRequest) Descriptor() ([]byte, []int) {
	return file_wires_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFeedRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DeleteFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFeedResponse) Reset() {
	*x = DeleteFeedResponse{}
	mi := &file_wires_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFeedResponse) ProtoMessage() {}

func (x *DeleteFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wires_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFeedResponse.ProtoReflect.Descriptor instead.
func (*DeleteFeedResponse) Descriptor() ([]byte, []int) {
	return file_wires_service_proto_rawDescGZIP(), []int{7}
}

var File_wires_service_proto protoreflect.FileDescriptor

const file_wires_service_proto_rawDesc = "" +
	"\n" +
	"\x13wires/service.proto\x12\n" +
	"ttab.wires\"E\n" +
	"\x12GetAllFeedsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\"n\n" +
	"\x13GetAllFeedsResponse\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tnext_page\x18\x02 \x01(\x03R\bnextPage\x12&\n" +
	"\x05feeds\x18\x03 \x03(\v2\x10.ttab.wires.FeedR\x05feeds\"\xe8\x02\n" +
	"\x04Feed\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.ttab.wires.FeedTypeR\x04type\x12B\n" +
	"\x0ftype_exceptions\x18\n" +
	" \x03(\v2\x19.ttab.wires.ExceptionRuleR\x0etypeExceptions\x12!\n" +
	"\fsection_code\x18\x05 \x01(\tR\vsectionCode\x12)\n" +
	"\x10refresh_interval\x18\x06 \x01(\x03R\x0frefreshInterval\x12\x1a\n" +
	"\blanguage\x18\a \x01(\tR\blanguage\x12!\n" +
	"\flast_checked\x18\b \x01(\tR\vlastChecked\x12)\n" +
	"\x10last_publication\x18\t \x01(\tR\x0flastPublication\"W\n" +
	"\rExceptionRule\x12#\n" +
	"\rtitle_pattern\x18\x01 \x01(\tR\ftitlePattern\x12!\n" +
	"\fhas_category\x18\x02 \x01(\tR\vhasCategory\"9\n" +
	"\x11UpdateFeedRequest\x12$\n" +
	"\x04feed\x18\x01 \x01(\v2\x10.ttab.wires.FeedR\x04feed\"\x14\n" +
	"\x12UpdateFeedResponse\"'\n" +
	"\x11DeleteFeedRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x14\n" +
	"\x12DeleteFeedResponse*E\n" +
	"\bFeedType\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\x10\n" +
	"\fTYPE_ARTICLE\x10\x01\x12\x15\n" +
	"\x11TYPE_PRESSRELEASE\x10\x022\xf3\x01\n" +
	"\aRssFeed\x12N\n" +
	"\vGetAllFeeds\x12\x1e.ttab.wires.GetAllFeedsRequest\x1a\x1f.ttab.wires.GetAllFeedsResponse\x12K\n" +
	"\n" +
	"UpdateFeed\x12\x1d.ttab.wires.UpdateFeedRequest\x1a\x1e.ttab.wires.UpdateFeedResponse\x12K\n" +
	"\n" +
	"DeleteFeed\x12\x1d.ttab.wires.DeleteFeedRequest\x1a\x1e.ttab.wires.DeleteFeedResponseB'Z%github.com/ttab/elephant-tt-api/wiresb\x06proto3"

var (
	file_wires_service_proto_rawDescOnce sync.Once
	file_wires_service_proto_rawDescData []byte
)

func file_wires_service_proto_rawDescGZIP() []byte {
	file_wires_service_proto_rawDescOnce.Do(func() {
		file_wires_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wires_service_proto_rawDesc), len(file_wires_service_proto_rawDesc)))
	})
	return file_wires_service_proto_rawDescData
}

var file_wires_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wires_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_wires_service_proto_goTypes = []any{
	(FeedType)(0),               // 0: ttab.wires.FeedType
	(*GetAllFeedsRequest)(nil),  // 1: ttab.wires.GetAllFeedsRequest
	(*GetAllFeedsResponse)(nil), // 2: ttab.wires.GetAllFeedsResponse
	(*Feed)(nil),                // 3: ttab.wires.Feed
	(*ExceptionRule)(nil),       // 4: ttab.wires.ExceptionRule
	(*UpdateFeedRequest)(nil),   // 5: ttab.wires.UpdateFeedRequest
	(*UpdateFeedResponse)(nil),  // 6: ttab.wires.UpdateFeedResponse
	(*DeleteFeedRequest)(nil),   // 7: ttab.wires.DeleteFeedRequest
	(*DeleteFeedResponse)(nil),  // 8: ttab.wires.DeleteFeedResponse
}
var file_wires_service_proto_depIdxs = []int32{
	3, // 0: ttab.wires.GetAllFeedsResponse.feeds:type_name -> ttab.wires.Feed
	0, // 1: ttab.wires.Feed.type:type_name -> ttab.wires.FeedType
	4, // 2: ttab.wires.Feed.type_exceptions:type_name -> ttab.wires.ExceptionRule
	3, // 3: ttab.wires.UpdateFeedRequest.feed:type_name -> ttab.wires.Feed
	1, // 4: ttab.wires.RssFeed.GetAllFeeds:input_type -> ttab.wires.GetAllFeedsRequest
	5, // 5: ttab.wires.RssFeed.UpdateFeed:input_type -> ttab.wires.UpdateFeedRequest
	7, // 6: ttab.wires.RssFeed.DeleteFeed:input_type -> ttab.wires.DeleteFeedRequest
	2, // 7: ttab.wires.RssFeed.GetAllFeeds:output_type -> ttab.wires.GetAllFeedsResponse
	6, // 8: ttab.wires.RssFeed.UpdateFeed:output_type -> ttab.wires.UpdateFeedResponse
	8, // 9: ttab.wires.RssFeed.DeleteFeed:output_type -> ttab.wires.DeleteFeedResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_wires_service_proto_init() }
func file_wires_service_proto_init() {
	if File_wires_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wires_service_proto_rawDesc), len(file_wires_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wires_service_proto_goTypes,
		DependencyIndexes: file_wires_service_proto_depIdxs,
		EnumInfos:         file_wires_service_proto_enumTypes,
		MessageInfos:      file_wires_service_proto_msgTypes,
	}.Build()
	File_wires_service_proto = out.File
	file_wires_service_proto_goTypes = nil
	file_wires_service_proto_depIdxs = nil
}
