// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v4.24.4
// source: everysport/service.proto

package everysport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManualImportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FromDate is the date from which to fetch events for import. Optional,
	// defaults to today.
	FromDate string `protobuf:"bytes,1,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	// FromDate is the last date we should get events for. Optional.
	ToDate string `protobuf:"bytes,2,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	// Category only re-imports the events with the specific category.
	Category int64 `protobuf:"varint,3,opt,name=category,proto3" json:"category,omitempty"`
	// Category only re-imports the events for the specific competition static ID.
	Competition int64 `protobuf:"varint,4,opt,name=competition,proto3" json:"competition,omitempty"`
	// Force overwrite of calendar entries.
	Force         bool `protobuf:"varint,5,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualImportRequest) Reset() {
	*x = ManualImportRequest{}
	mi := &file_everysport_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualImportRequest) ProtoMessage() {}

func (x *ManualImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_everysport_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualImportRequest.ProtoReflect.Descriptor instead.
func (*ManualImportRequest) Descriptor() ([]byte, []int) {
	return file_everysport_service_proto_rawDescGZIP(), []int{0}
}

func (x *ManualImportRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *ManualImportRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

func (x *ManualImportRequest) GetCategory() int64 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *ManualImportRequest) GetCompetition() int64 {
	if x != nil {
		return x.Competition
	}
	return 0
}

func (x *ManualImportRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type ManualImportResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// QueuedImports is the total numer of events that were queued for import.
	QueuedImports int64 `protobuf:"varint,1,opt,name=queued_imports,json=queuedImports,proto3" json:"queued_imports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualImportResponse) Reset() {
	*x = ManualImportResponse{}
	mi := &file_everysport_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualImportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualImportResponse) ProtoMessage() {}

func (x *ManualImportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_everysport_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualImportResponse.ProtoReflect.Descriptor instead.
func (*ManualImportResponse) Descriptor() ([]byte, []int) {
	return file_everysport_service_proto_rawDescGZIP(), []int{1}
}

func (x *ManualImportResponse) GetQueuedImports() int64 {
	if x != nil {
		return x.QueuedImports
	}
	return 0
}

var File_everysport_service_proto protoreflect.FileDescriptor

var file_everysport_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x65, 0x76, 0x65, 0x72, 0x79, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x74, 0x74, 0x61, 0x62,
	0x2e, 0x65, 0x76, 0x65, 0x72, 0x79, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x9f, 0x01, 0x0a, 0x13,
	0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x74, 0x6f, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70,
	0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x22, 0x3d, 0x0a,
	0x14, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x5f,
	0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x71,
	0x75, 0x65, 0x75, 0x65, 0x64, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x32, 0x65, 0x0a, 0x06,
	0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x12, 0x5b, 0x0a, 0x0c, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c,
	0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x24, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x65, 0x76,
	0x65, 0x72, 0x79, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x49,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x74,
	0x74, 0x61, 0x62, 0x2e, 0x65, 0x76, 0x65, 0x72, 0x79, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x4d,
	0x61, 0x6e, 0x75, 0x61, 0x6c, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x74, 0x74, 0x61, 0x62, 0x2f, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2d,
	0x74, 0x74, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x76, 0x65, 0x72, 0x79, 0x73, 0x70, 0x6f, 0x72,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_everysport_service_proto_rawDescOnce sync.Once
	file_everysport_service_proto_rawDescData = file_everysport_service_proto_rawDesc
)

func file_everysport_service_proto_rawDescGZIP() []byte {
	file_everysport_service_proto_rawDescOnce.Do(func() {
		file_everysport_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_everysport_service_proto_rawDescData)
	})
	return file_everysport_service_proto_rawDescData
}

var file_everysport_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_everysport_service_proto_goTypes = []any{
	(*ManualImportRequest)(nil),  // 0: ttab.everysport.ManualImportRequest
	(*ManualImportResponse)(nil), // 1: ttab.everysport.ManualImportResponse
}
var file_everysport_service_proto_depIdxs = []int32{
	0, // 0: ttab.everysport.Manage.ManualImport:input_type -> ttab.everysport.ManualImportRequest
	1, // 1: ttab.everysport.Manage.ManualImport:output_type -> ttab.everysport.ManualImportResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_everysport_service_proto_init() }
func file_everysport_service_proto_init() {
	if File_everysport_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_everysport_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_everysport_service_proto_goTypes,
		DependencyIndexes: file_everysport_service_proto_depIdxs,
		MessageInfos:      file_everysport_service_proto_msgTypes,
	}.Build()
	File_everysport_service_proto = out.File
	file_everysport_service_proto_rawDesc = nil
	file_everysport_service_proto_goTypes = nil
	file_everysport_service_proto_depIdxs = nil
}
