// Code generated by protoc-gen-elephant-rpc. DO NOT EDIT.
//
// Source: baboon/service.proto

package baboonconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	baboon "github.com/ttab/elephant-tt-api/baboon"
	http "net/http"
)

// NewAssetsServiceHandler builds an HTTP handler for the ttab.baboon.Assets service from an
// implementation of the plain baboon.Assets interface, and returns the path to mount it on together
// with the handler, just like NewAssetsHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewAssetsServiceHandler(svc baboon.Assets, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewAssetsHandler(&assetsServiceHandler{svc: svc}, opts...)
}

// assetsServiceHandler implements AssetsHandler on top of a baboon.Assets.
type assetsServiceHandler struct {
	svc baboon.Assets
}

func (h *assetsServiceHandler) StoreFont(ctx context.Context, req *connect.Request[baboon.StoreFontRequest]) (*connect.Response[baboon.StoreFontResponse], error) {
	res, err := h.svc.StoreFont(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *assetsServiceHandler) GetFonts(ctx context.Context, req *connect.Request[baboon.GetFontsRequest]) (*connect.Response[baboon.GetFontsResponse], error) {
	res, err := h.svc.GetFonts(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *assetsServiceHandler) ListFonts(ctx context.Context, req *connect.Request[baboon.ListFontsRequest]) (*connect.Response[baboon.ListFontsResponse], error) {
	res, err := h.svc.ListFonts(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *assetsServiceHandler) DeleteFont(ctx context.Context, req *connect.Request[baboon.DeleteFontRequest]) (*connect.Response[baboon.DeleteFontResponse], error) {
	res, err := h.svc.DeleteFont(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *assetsServiceHandler) StoreICCProfile(ctx context.Context, req *connect.Request[baboon.StoreICCProfileRequest]) (*connect.Response[baboon.StoreICCProfileResponse], error) {
	res, err := h.svc.StoreICCProfile(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *assetsServiceHandler) ListICCProfiles(ctx context.Context, req *connect.Request[baboon.ListICCProfilesRequest]) (*connect.Response[baboon.ListICCProfilesResponse], error) {
	res, err := h.svc.ListICCProfiles(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewAssetsServiceClient constructs a client for the ttab.baboon.Assets service that implements the
// plain baboon.Assets interface, so that it is a drop-in for the Twirp clients. The options are the
// ones NewAssetsClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewAssetsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) baboon.Assets {
	return &assetsServiceClient{
		client: NewAssetsClient(httpClient, baseURL, opts...),
	}
}

// assetsServiceClient implements baboon.Assets on top of a AssetsClient.
type assetsServiceClient struct {
	client AssetsClient
}

func (c *assetsServiceClient) StoreFont(ctx context.Context, req *baboon.StoreFontRequest) (*baboon.StoreFontResponse, error) {
	res, err := c.client.StoreFont(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *assetsServiceClient) GetFonts(ctx context.Context, req *baboon.GetFontsRequest) (*baboon.GetFontsResponse, error) {
	res, err := c.client.GetFonts(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *assetsServiceClient) ListFonts(ctx context.Context, req *baboon.ListFontsRequest) (*baboon.ListFontsResponse, error) {
	res, err := c.client.ListFonts(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *assetsServiceClient) DeleteFont(ctx context.Context, req *baboon.DeleteFontRequest) (*baboon.DeleteFontResponse, error) {
	res, err := c.client.DeleteFont(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *assetsServiceClient) StoreICCProfile(ctx context.Context, req *baboon.StoreICCProfileRequest) (*baboon.StoreICCProfileResponse, error) {
	res, err := c.client.StoreICCProfile(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *assetsServiceClient) ListICCProfiles(ctx context.Context, req *baboon.ListICCProfilesRequest) (*baboon.ListICCProfilesResponse, error) {
	res, err := c.client.ListICCProfiles(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

// NewPrintServiceHandler builds an HTTP handler for the ttab.baboon.Print service from an
// implementation of the plain baboon.Print interface, and returns the path to mount it on together
// with the handler, just like NewPrintHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewPrintServiceHandler(svc baboon.Print, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewPrintHandler(&printServiceHandler{svc: svc}, opts...)
}

// printServiceHandler implements PrintHandler on top of a baboon.Print.
type printServiceHandler struct {
	svc baboon.Print
}

func (h *printServiceHandler) RenderArticle(ctx context.Context, req *connect.Request[baboon.RenderArticleRequest]) (*connect.Response[baboon.RenderArticleResponse], error) {
	res, err := h.svc.RenderArticle(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *printServiceHandler) GetEditableArchive(ctx context.Context, req *connect.Request[baboon.GetEditableArchiveRequest]) (*connect.Response[baboon.GetEditableArchiveResponse], error) {
	res, err := h.svc.GetEditableArchive(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *printServiceHandler) LayoutPreview(ctx context.Context, req *connect.Request[baboon.LayoutPreviewRequest]) (*connect.Response[baboon.LayoutPreviewResponse], error) {
	res, err := h.svc.LayoutPreview(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *printServiceHandler) CreateFlow(ctx context.Context, req *connect.Request[baboon.CreateFlowRequest]) (*connect.Response[baboon.CreateFlowResponse], error) {
	res, err := h.svc.CreateFlow(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *printServiceHandler) CopyArticleToFlow(ctx context.Context, req *connect.Request[baboon.CopyArticleToFlowRequest]) (*connect.Response[baboon.CopyArticleToFlowResponse], error) {
	res, err := h.svc.CopyArticleToFlow(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *printServiceHandler) GetScribusInfo(ctx context.Context, req *connect.Request[baboon.GetScribusInfoRequest]) (*connect.Response[baboon.GetScribusInfoResponse], error) {
	res, err := h.svc.GetScribusInfo(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *printServiceHandler) GetRenderedArticles(ctx context.Context, req *connect.Request[baboon.GetRenderedArticlesRequest]) (*connect.Response[baboon.GetRenderedArticlesResponse], error) {
	res, err := h.svc.GetRenderedArticles(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *printServiceHandler) SetHypenation(ctx context.Context, req *connect.Request[baboon.SetHypenationRequest]) (*connect.Response[baboon.SetHypenationResponse], error) {
	res, err := h.svc.SetHypenation(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *printServiceHandler) ListHypenations(ctx context.Context, req *connect.Request[baboon.ListHypenationsRequest]) (*connect.Response[baboon.ListHypenationsResponse], error) {
	res, err := h.svc.ListHypenations(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *printServiceHandler) RemoveHypenation(ctx context.Context, req *connect.Request[baboon.RemoveHypenationRequest]) (*connect.Response[baboon.RemoveHypenationResponse], error) {
	res, err := h.svc.RemoveHypenation(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewPrintServiceClient constructs a client for the ttab.baboon.Print service that implements the
// plain baboon.Print interface, so that it is a drop-in for the Twirp clients. The options are the
// ones NewPrintClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewPrintServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) baboon.Print {
	return &printServiceClient{
		client: NewPrintClient(httpClient, baseURL, opts...),
	}
}

// printServiceClient implements baboon.Print on top of a PrintClient.
type printServiceClient struct {
	client PrintClient
}

func (c *printServiceClient) RenderArticle(ctx context.Context, req *baboon.RenderArticleRequest) (*baboon.RenderArticleResponse, error) {
	res, err := c.client.RenderArticle(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *printServiceClient) GetEditableArchive(ctx context.Context, req *baboon.GetEditableArchiveRequest) (*baboon.GetEditableArchiveResponse, error) {
	res, err := c.client.GetEditableArchive(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *printServiceClient) LayoutPreview(ctx context.Context, req *baboon.LayoutPreviewRequest) (*baboon.LayoutPreviewResponse, error) {
	res, err := c.client.LayoutPreview(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *printServiceClient) CreateFlow(ctx context.Context, req *baboon.CreateFlowRequest) (*baboon.CreateFlowResponse, error) {
	res, err := c.client.CreateFlow(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *printServiceClient) CopyArticleToFlow(ctx context.Context, req *baboon.CopyArticleToFlowRequest) (*baboon.CopyArticleToFlowResponse, error) {
	res, err := c.client.CopyArticleToFlow(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *printServiceClient) GetScribusInfo(ctx context.Context, req *baboon.GetScribusInfoRequest) (*baboon.GetScribusInfoResponse, error) {
	res, err := c.client.GetScribusInfo(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *printServiceClient) GetRenderedArticles(ctx context.Context, req *baboon.GetRenderedArticlesRequest) (*baboon.GetRenderedArticlesResponse, error) {
	res, err := c.client.GetRenderedArticles(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *printServiceClient) SetHypenation(ctx context.Context, req *baboon.SetHypenationRequest) (*baboon.SetHypenationResponse, error) {
	res, err := c.client.SetHypenation(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *printServiceClient) ListHypenations(ctx context.Context, req *baboon.ListHypenationsRequest) (*baboon.ListHypenationsResponse, error) {
	res, err := c.client.ListHypenations(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *printServiceClient) RemoveHypenation(ctx context.Context, req *baboon.RemoveHypenationRequest) (*baboon.RemoveHypenationResponse, error) {
	res, err := c.client.RemoveHypenation(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}
