// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: baboon/service.proto

package baboonconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	baboon "github.com/ttab/elephant-tt-api/baboon"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AssetsName is the fully-qualified name of the Assets service.
	AssetsName = "ttab.baboon.Assets"
	// PrintName is the fully-qualified name of the Print service.
	PrintName = "ttab.baboon.Print"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AssetsStoreFontProcedure is the fully-qualified name of the Assets's StoreFont RPC.
	AssetsStoreFontProcedure = "/ttab.baboon.Assets/StoreFont"
	// AssetsGetFontsProcedure is the fully-qualified name of the Assets's GetFonts RPC.
	AssetsGetFontsProcedure = "/ttab.baboon.Assets/GetFonts"
	// AssetsListFontsProcedure is the fully-qualified name of the Assets's ListFonts RPC.
	AssetsListFontsProcedure = "/ttab.baboon.Assets/ListFonts"
	// AssetsDeleteFontProcedure is the fully-qualified name of the Assets's DeleteFont RPC.
	AssetsDeleteFontProcedure = "/ttab.baboon.Assets/DeleteFont"
	// AssetsStoreICCProfileProcedure is the fully-qualified name of the Assets's StoreICCProfile RPC.
	AssetsStoreICCProfileProcedure = "/ttab.baboon.Assets/StoreICCProfile"
	// AssetsListICCProfilesProcedure is the fully-qualified name of the Assets's ListICCProfiles RPC.
	AssetsListICCProfilesProcedure = "/ttab.baboon.Assets/ListICCProfiles"
	// PrintRenderArticleProcedure is the fully-qualified name of the Print's RenderArticle RPC.
	PrintRenderArticleProcedure = "/ttab.baboon.Print/RenderArticle"
	// PrintGetEditableArchiveProcedure is the fully-qualified name of the Print's GetEditableArchive
	// RPC.
	PrintGetEditableArchiveProcedure = "/ttab.baboon.Print/GetEditableArchive"
	// PrintLayoutPreviewProcedure is the fully-qualified name of the Print's LayoutPreview RPC.
	PrintLayoutPreviewProcedure = "/ttab.baboon.Print/LayoutPreview"
	// PrintCreateFlowProcedure is the fully-qualified name of the Print's CreateFlow RPC.
	PrintCreateFlowProcedure = "/ttab.baboon.Print/CreateFlow"
	// PrintCopyArticleToFlowProcedure is the fully-qualified name of the Print's CopyArticleToFlow RPC.
	PrintCopyArticleToFlowProcedure = "/ttab.baboon.Print/CopyArticleToFlow"
	// PrintGetScribusInfoProcedure is the fully-qualified name of the Print's GetScribusInfo RPC.
	PrintGetScribusInfoProcedure = "/ttab.baboon.Print/GetScribusInfo"
	// PrintGetRenderedArticlesProcedure is the fully-qualified name of the Print's GetRenderedArticles
	// RPC.
	PrintGetRenderedArticlesProcedure = "/ttab.baboon.Print/GetRenderedArticles"
	// PrintSetHypenationProcedure is the fully-qualified name of the Print's SetHypenation RPC.
	PrintSetHypenationProcedure = "/ttab.baboon.Print/SetHypenation"
	// PrintListHypenationsProcedure is the fully-qualified name of the Print's ListHypenations RPC.
	PrintListHypenationsProcedure = "/ttab.baboon.Print/ListHypenations"
	// PrintRemoveHypenationProcedure is the fully-qualified name of the Print's RemoveHypenation RPC.
	PrintRemoveHypenationProcedure = "/ttab.baboon.Print/RemoveHypenation"
)

// AssetsClient is a client for the ttab.baboon.Assets service.
type AssetsClient interface {
	StoreFont(context.Context, *connect.Request[baboon.StoreFontRequest]) (*connect.Response[baboon.StoreFontResponse], error)
	GetFonts(context.Context, *connect.Request[baboon.GetFontsRequest]) (*connect.Response[baboon.GetFontsResponse], error)
	ListFonts(context.Context, *connect.Request[baboon.ListFontsRequest]) (*connect.Response[baboon.ListFontsResponse], error)
	DeleteFont(context.Context, *connect.Request[baboon.DeleteFontRequest]) (*connect.Response[baboon.DeleteFontResponse], error)
	StoreICCProfile(context.Context, *connect.Request[baboon.StoreICCProfileRequest]) (*connect.Response[baboon.StoreICCProfileResponse], error)
	ListICCProfiles(context.Context, *connect.Request[baboon.ListICCProfilesRequest]) (*connect.Response[baboon.ListICCProfilesResponse], error)
}

// NewAssetsClient constructs a client for the ttab.baboon.Assets service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAssetsClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AssetsClient {
	baseURL = strings.TrimRight(baseURL, "/")
	assetsMethods := baboon.File_baboon_service_proto.Services().ByName("Assets").Methods()
	return &assetsClient{
		storeFont: connect.NewClient[baboon.StoreFontRequest, baboon.StoreFontResponse](
			httpClient,
			baseURL+AssetsStoreFontProcedure,
			connect.WithSchema(assetsMethods.ByName("StoreFont")),
			connect.WithClientOptions(opts...),
		),
		getFonts: connect.NewClient[baboon.GetFontsRequest, baboon.GetFontsResponse](
			httpClient,
			baseURL+AssetsGetFontsProcedure,
			connect.WithSchema(assetsMethods.ByName("GetFonts")),
			connect.WithClientOptions(opts...),
		),
		listFonts: connect.NewClient[baboon.ListFontsRequest, baboon.ListFontsResponse](
			httpClient,
			baseURL+AssetsListFontsProcedure,
			connect.WithSchema(assetsMethods.ByName("ListFonts")),
			connect.WithClientOptions(opts...),
		),
		deleteFont: connect.NewClient[baboon.DeleteFontRequest, baboon.DeleteFontResponse](
			httpClient,
			baseURL+AssetsDeleteFontProcedure,
			connect.WithSchema(assetsMethods.ByName("DeleteFont")),
			connect.WithClientOptions(opts...),
		),
		storeICCProfile: connect.NewClient[baboon.StoreICCProfileRequest, baboon.StoreICCProfileResponse](
			httpClient,
			baseURL+AssetsStoreICCProfileProcedure,
			connect.WithSchema(assetsMethods.ByName("StoreICCProfile")),
			connect.WithClientOptions(opts...),
		),
		listICCProfiles: connect.NewClient[baboon.ListICCProfilesRequest, baboon.ListICCProfilesResponse](
			httpClient,
			baseURL+AssetsListICCProfilesProcedure,
			connect.WithSchema(assetsMethods.ByName("ListICCProfiles")),
			connect.WithClientOptions(opts...),
		),
	}
}

// assetsClient implements AssetsClient.
type assetsClient struct {
	storeFont       *connect.Client[baboon.StoreFontRequest, baboon.StoreFontResponse]
	getFonts        *connect.Client[baboon.GetFontsRequest, baboon.GetFontsResponse]
	listFonts       *connect.Client[baboon.ListFontsRequest, baboon.ListFontsResponse]
	deleteFont      *connect.Client[baboon.DeleteFontRequest, baboon.DeleteFontResponse]
	storeICCProfile *connect.Client[baboon.StoreICCProfileRequest, baboon.StoreICCProfileResponse]
	listICCProfiles *connect.Client[baboon.ListICCProfilesRequest, baboon.ListICCProfilesResponse]
}

// StoreFont calls ttab.baboon.Assets.StoreFont.
func (c *assetsClient) StoreFont(ctx context.Context, req *connect.Request[baboon.StoreFontRequest]) (*connect.Response[baboon.StoreFontResponse], error) {
	return c.storeFont.CallUnary(ctx, req)
}

// GetFonts calls ttab.baboon.Assets.GetFonts.
func (c *assetsClient) GetFonts(ctx context.Context, req *connect.Request[baboon.GetFontsRequest]) (*connect.Response[baboon.GetFontsResponse], error) {
	return c.getFonts.CallUnary(ctx, req)
}

// ListFonts calls ttab.baboon.Assets.ListFonts.
func (c *assetsClient) ListFonts(ctx context.Context, req *connect.Request[baboon.ListFontsRequest]) (*connect.Response[baboon.ListFontsResponse], error) {
	return c.listFonts.CallUnary(ctx, req)
}

// DeleteFont calls ttab.baboon.Assets.DeleteFont.
func (c *assetsClient) DeleteFont(ctx context.Context, req *connect.Request[baboon.DeleteFontRequest]) (*connect.Response[baboon.DeleteFontResponse], error) {
	return c.deleteFont.CallUnary(ctx, req)
}

// StoreICCProfile calls ttab.baboon.Assets.StoreICCProfile.
func (c *assetsClient) StoreICCProfile(ctx context.Context, req *connect.Request[baboon.StoreICCProfileRequest]) (*connect.Response[baboon.StoreICCProfileResponse], error) {
	return c.storeICCProfile.CallUnary(ctx, req)
}

// ListICCProfiles calls ttab.baboon.Assets.ListICCProfiles.
func (c *assetsClient) ListICCProfiles(ctx context.Context, req *connect.Request[baboon.ListICCProfilesRequest]) (*connect.Response[baboon.ListICCProfilesResponse], error) {
	return c.listICCProfiles.CallUnary(ctx, req)
}

// AssetsHandler is an implementation of the ttab.baboon.Assets service.
type AssetsHandler interface {
	StoreFont(context.Context, *connect.Request[baboon.StoreFontRequest]) (*connect.Response[baboon.StoreFontResponse], error)
	GetFonts(context.Context, *connect.Request[baboon.GetFontsRequest]) (*connect.Response[baboon.GetFontsResponse], error)
	ListFonts(context.Context, *connect.Request[baboon.ListFontsRequest]) (*connect.Response[baboon.ListFontsResponse], error)
	DeleteFont(context.Context, *connect.Request[baboon.DeleteFontRequest]) (*connect.Response[baboon.DeleteFontResponse], error)
	StoreICCProfile(context.Context, *connect.Request[baboon.StoreICCProfileRequest]) (*connect.Response[baboon.StoreICCProfileResponse], error)
	ListICCProfiles(context.Context, *connect.Request[baboon.ListICCProfilesRequest]) (*connect.Response[baboon.ListICCProfilesResponse], error)
}

// NewAssetsHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAssetsHandler(svc AssetsHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	assetsMethods := baboon.File_baboon_service_proto.Services().ByName("Assets").Methods()
	assetsStoreFontHandler := connect.NewUnaryHandler(
		AssetsStoreFontProcedure,
		svc.StoreFont,
		connect.WithSchema(assetsMethods.ByName("StoreFont")),
		connect.WithHandlerOptions(opts...),
	)
	assetsGetFontsHandler := connect.NewUnaryHandler(
		AssetsGetFontsProcedure,
		svc.GetFonts,
		connect.WithSchema(assetsMethods.ByName("GetFonts")),
		connect.WithHandlerOptions(opts...),
	)
	assetsListFontsHandler := connect.NewUnaryHandler(
		AssetsListFontsProcedure,
		svc.ListFonts,
		connect.WithSchema(assetsMethods.ByName("ListFonts")),
		connect.WithHandlerOptions(opts...),
	)
	assetsDeleteFontHandler := connect.NewUnaryHandler(
		AssetsDeleteFontProcedure,
		svc.DeleteFont,
		connect.WithSchema(assetsMethods.ByName("DeleteFont")),
		connect.WithHandlerOptions(opts...),
	)
	assetsStoreICCProfileHandler := connect.NewUnaryHandler(
		AssetsStoreICCProfileProcedure,
		svc.StoreICCProfile,
		connect.WithSchema(assetsMethods.ByName("StoreICCProfile")),
		connect.WithHandlerOptions(opts...),
	)
	assetsListICCProfilesHandler := connect.NewUnaryHandler(
		AssetsListICCProfilesProcedure,
		svc.ListICCProfiles,
		connect.WithSchema(assetsMethods.ByName("ListICCProfiles")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ttab.baboon.Assets/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AssetsStoreFontProcedure:
			assetsStoreFontHandler.ServeHTTP(w, r)
		case AssetsGetFontsProcedure:
			assetsGetFontsHandler.ServeHTTP(w, r)
		case AssetsListFontsProcedure:
			assetsListFontsHandler.ServeHTTP(w, r)
		case AssetsDeleteFontProcedure:
			assetsDeleteFontHandler.ServeHTTP(w, r)
		case AssetsStoreICCProfileProcedure:
			assetsStoreICCProfileHandler.ServeHTTP(w, r)
		case AssetsListICCProfilesProcedure:
			assetsListICCProfilesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAssetsHandler returns CodeUnimplemented from all methods.
type UnimplementedAssetsHandler struct{}

func (UnimplementedAssetsHandler) StoreFont(context.Context, *connect.Request[baboon.StoreFontRequest]) (*connect.Response[baboon.StoreFontResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.baboon.Assets.StoreFont is not implemented"))
}

func (UnimplementedAssetsHandler) GetFonts(context.Context, *connect.Request[baboon.GetFontsRequest]) (*connect.Response[baboon.GetFontsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.baboon.Assets.GetFonts is not implemented"))
}

func (UnimplementedAssetsHandler) ListFonts(context.Context, *connect.Request[baboon.ListFontsRequest]) (*connect.Response[baboon.ListFontsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.baboon.Assets.ListFonts is not implemented"))
}

func (UnimplementedAssetsHandler) DeleteFont(context.Context, *connect.Request[baboon.DeleteFontRequest]) (*connect.Response[baboon.DeleteFontResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.baboon.Assets.DeleteFont is not implemented"))
}

func (UnimplementedAssetsHandler) StoreICCProfile(context.Context, *connect.Request[baboon.StoreICCProfileRequest]) (*connect.Response[baboon.StoreICCProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.baboon.Assets.StoreICCProfile is not implemented"))
}

func (UnimplementedAssetsHandler) ListICCProfiles(context.Context, *connect.Request[baboon.ListICCProfilesRequest]) (*connect.Response[baboon.ListICCProfilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.baboon.Assets.ListICCProfiles is not implemented"))
}

// PrintClient is a client for the ttab.baboon.Print service.
type PrintClient interface {
	RenderArticle(context.Context, *connect.Request[baboon.RenderArticleRequest]) (*connect.Response[baboon.RenderArticleResponse], error)
	GetEditableArchive(context.Context, *connect.Request[baboon.GetEditableArchiveRequest]) (*connect.Response[baboon.GetEditableArchiveResponse], error)
	// LayoutPreview is used by the CLI tool to do preview rendering.
	LayoutPreview(context.Context, *connect.Request[baboon.LayoutPreviewRequest]) (*connect.Response[baboon.LayoutPreviewResponse], error)
	CreateFlow(context.Context, *connect.Request[baboon.CreateFlowRequest]) (*connect.Response[baboon.CreateFlowResponse], error)
	CopyArticleToFlow(context.Context, *connect.Request[baboon.CopyArticleToFlowRequest]) (*connect.Response[baboon.CopyArticleToFlowResponse], error)
	GetScribusInfo(context.Context, *connect.Request[baboon.GetScribusInfoRequest]) (*connect.Response[baboon.GetScribusInfoResponse], error)
	// GetRenderedArticles allows a client to consume and download all finished renders.
	GetRenderedArticles(context.Context, *connect.Request[baboon.GetRenderedArticlesRequest]) (*connect.Response[baboon.GetRenderedArticlesResponse], error)
	// SetHypenation allows clients to set custom hypenation for a word.
	SetHypenation(context.Context, *connect.Request[baboon.SetHypenationRequest]) (*connect.Response[baboon.SetHypenationResponse], error)
	// ListHypenations is used to list words in the hypenation dictionary.
	ListHypenations(context.Context, *connect.Request[baboon.ListHypenationsRequest]) (*connect.Response[baboon.ListHypenationsResponse], error)
	// RemoveHypenation is used to remove a custom hypenation for a word.
	RemoveHypenation(context.Context, *connect.Request[baboon.RemoveHypenationRequest]) (*connect.Response[baboon.RemoveHypenationResponse], error)
}

// NewPrintClient constructs a client for the ttab.baboon.Print service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPrintClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PrintClient {
	baseURL = strings.TrimRight(baseURL, "/")
	printMethods := baboon.File_baboon_service_proto.Services().ByName("Print").Methods()
	return &printClient{
		renderArticle: connect.NewClient[baboon.RenderArticleRequest, baboon.RenderArticleResponse](
			httpClient,
			baseURL+PrintRenderArticleProcedure,
			connect.WithSchema(printMethods.ByName("RenderArticle")),
			connect.WithClientOptions(opts...),
		),
		getEditableArchive: connect.NewClient[baboon.GetEditableArchiveRequest, baboon.GetEditableArchiveResponse](
			httpClient,
			baseURL+PrintGetEditableArchiveProcedure,
			connect.WithSchema(printMethods.ByName("GetEditableArchive")),
			connect.WithClientOptions(opts...),
		),
		layoutPreview: connect.NewClient[baboon.LayoutPreviewRequest, baboon.LayoutPreviewResponse](
			httpClient,
			baseURL+PrintLayoutPreviewProcedure,
			connect.WithSchema(printMethods.ByName("LayoutPreview")),
			connect.WithClientOptions(opts...),
		),
		createFlow: connect.NewClient[baboon.CreateFlowRequest, baboon.CreateFlowResponse](
			httpClient,
			baseURL+PrintCreateFlowProcedure,
			connect.WithSchema(printMethods.ByName("CreateFlow")),
			connect.WithClientOptions(opts...),
		),
		copyArticleToFlow: connect.NewClient[baboon.CopyArticleToFlowRequest, baboon.CopyArticleToFlowResponse](
			httpClient,
			baseURL+PrintCopyArticleToFlowProcedure,
			connect.WithSchema(printMethods.ByName("CopyArticleToFlow")),
			connect.WithClientOptions(opts...),
		),
		getScribusInfo: connect.NewClient[baboon.GetScribusInfoRequest, baboon.GetScribusInfoResponse](
			httpClient,
			baseURL+PrintGetScribusInfoProcedure,
			connect.WithSchema(printMethods.ByName("GetScribusInfo")),
			connect.WithClientOptions(opts...),
		),
		getRenderedArticles: connect.NewClient[baboon.GetRenderedArticlesRequest, baboon.GetRenderedArticlesResponse](
			httpClient,
			baseURL+PrintGetRenderedArticlesProcedure,
			connect.WithSchema(printMethods.ByName("GetRenderedArticles")),
			connect.WithClientOptions(opts...),
		),
		setHypenation: connect.NewClient[baboon.SetHypenationRequest, baboon.SetHypenationResponse](
			httpClient,
			baseURL+PrintSetHypenationProcedure,
			connect.WithSchema(printMethods.ByName("SetHypenation")),
			connect.WithClientOptions(opts...),
		),
		listHypenations: connect.NewClient[baboon.ListHypenationsRequest, baboon.ListHypenationsResponse](
			httpClient,
			baseURL+PrintListHypenationsProcedure,
			connect.WithSchema(printMethods.ByName("ListHypenations")),
			connect.WithClientOptions(opts...),
		),
		removeHypenation: connect.NewClient[baboon.RemoveHypenationRequest, baboon.RemoveHypenationResponse](
			httpClient,
			baseURL+PrintRemoveHypenationProcedure,
			connect.WithSchema(printMethods.ByName("RemoveHypenation")),
			connect.WithClientOptions(opts...),
		),
	}
}

// printClient implements PrintClient.
type printClient struct {
	renderArticle       *connect.Client[baboon.RenderArticleRequest, baboon.RenderArticleResponse]
	getEditableArchive  *connect.Client[baboon.GetEditableArchiveRequest, baboon.GetEditableArchiveResponse]
	layoutPreview       *connect.Client[baboon.LayoutPreviewRequest, baboon.LayoutPreviewResponse]
	createFlow          *connect.Client[baboon.CreateFlowRequest, baboon.CreateFlowResponse]
	copyArticleToFlow   *connect.Client[baboon.CopyArticleToFlowRequest, baboon.CopyArticleToFlowResponse]
	getScribusInfo      *connect.Client[baboon.GetScribusInfoRequest, baboon.GetScribusInfoResponse]
	getRenderedArticles *connect.Client[baboon.GetRenderedArticlesRequest, baboon.GetRenderedArticlesResponse]
	setHypenation       *connect.Client[baboon.SetHypenationRequest, baboon.SetHypenationResponse]
	listHypenations     *connect.Client[baboon.ListHypenationsRequest, baboon.ListHypenationsResponse]
	removeHypenation    *connect.Client[baboon.RemoveHypenationRequest, baboon.RemoveHypenationResponse]
}

// RenderArticle calls ttab.baboon.Print.RenderArticle.
func (c *printClient) RenderArticle(ctx context.Context, req *connect.Request[baboon.RenderArticleRequest]) (*connect.Response[baboon.RenderArticleResponse], error) {
	return c.renderArticle.CallUnary(ctx, req)
}

// GetEditableArchive calls ttab.baboon.Print.GetEditableArchive.
func (c *printClient) GetEditableArchive(ctx context.Context, req *connect.Request[baboon.GetEditableArchiveRequest]) (*connect.Response[baboon.GetEditableArchiveResponse], error) {
	return c.getEditableArchive.CallUnary(ctx, req)
}

// LayoutPreview calls ttab.baboon.Print.LayoutPreview.
func (c *printClient) LayoutPreview(ctx context.Context, req *connect.Request[baboon.LayoutPreviewRequest]) (*connect.Response[baboon.LayoutPreviewResponse], error) {
	return c.layoutPreview.CallUnary(ctx, req)
}

// CreateFlow calls ttab.baboon.Print.CreateFlow.
func (c *printClient) CreateFlow(ctx context.Context, req *connect.Request[baboon.CreateFlowRequest]) (*connect.Response[baboon.CreateFlowResponse], error) {
	return c.createFlow.CallUnary(ctx, req)
}

// CopyArticleToFlow calls ttab.baboon.Print.CopyArticleToFlow.
func (c *printClient) CopyArticleToFlow(ctx context.Context, req *connect.Request[baboon.CopyArticleToFlowRequest]) (*connect.Response[baboon.CopyArticleToFlowResponse], error) {
	return c.copyArticleToFlow.CallUnary(ctx, req)
}

// GetScribusInfo calls ttab.baboon.Print.GetScribusInfo.
func (c *printClient) GetScribusInfo(ctx context.Context, req *connect.Request[baboon.GetScribusInfoRequest]) (*connect.Response[baboon.GetScribusInfoResponse], error) {
	return c.getScribusInfo.CallUnary(ctx, req)
}

// GetRenderedArticles calls ttab.baboon.Print.GetRenderedArticles.
func (c *printClient) GetRenderedArticles(ctx context.Context, req *connect.Request[baboon.GetRenderedArticlesRequest]) (*connect.Response[baboon.GetRenderedArticlesResponse], error) {
	return c.getRenderedArticles.CallUnary(ctx, req)
}

// SetHypenation calls ttab.baboon.Print.SetHypenation.
func (c *printClient) SetHypenation(ctx context.Context, req *connect.Request[baboon.SetHypenationRequest]) (*connect.Response[baboon.SetHypenationResponse], error) {
	return c.setHypenation.CallUnary(ctx, req)
}

// ListHypenations calls ttab.baboon.Print.ListHypenations.
func (c *printClient) ListHypenations(ctx context.Context, req *connect.Request[baboon.ListHypenationsRequest]) (*connect.Response[baboon.ListHypenationsResponse], error) {
	return c.listHypenations.CallUnary(ctx, req)
}

// RemoveHypenation calls ttab.baboon.Print.RemoveHypenation.
func (c *printClient) RemoveHypenation(ctx context.Context, req *connect.Request[baboon.RemoveHypenationRequest]) (*connect.Response[baboon.RemoveHypenationResponse], error) {
	return c.removeHypenation.CallUnary(ctx, req)
}

// PrintHandler is an implementation of the ttab.baboon.Print service.
type PrintHandler interface {
	RenderArticle(context.Context, *connect.Request[baboon.RenderArticleRequest]) (*connect.Response[baboon.RenderArticleResponse], error)
	GetEditableArchive(context.Context, *connect.Request[baboon.GetEditableArchiveRequest]) (*connect.Response[baboon.GetEditableArchiveResponse], error)
	// LayoutPreview is used by the CLI tool to do preview rendering.
	LayoutPreview(context.Context, *connect.Request[baboon.LayoutPreviewRequest]) (*connect.Response[baboon.LayoutPreviewResponse], error)
	CreateFlow(context.Context, *connect.Request[baboon.CreateFlowRequest]) (*connect.Response[baboon.CreateFlowResponse], error)
	CopyArticleToFlow(context.Context, *connect.Request[baboon.CopyArticleToFlowRequest]) (*connect.Response[baboon.CopyArticleToFlowResponse], error)
	GetScribusInfo(context.Context, *connect.Request[baboon.GetScribusInfoRequest]) (*connect.Response[baboon.GetScribusInfoResponse], error)
	// GetRenderedArticles allows a client to consume and download all finished renders.
	GetRenderedArticles(context.Context, *connect.Request[baboon.GetRenderedArticlesRequest]) (*connect.Response[baboon.GetRenderedArticlesResponse], error)
	// SetHypenation allows clients to set custom hypenation for a word.
	SetHypenation(context.Context, *connect.Request[baboon.SetHypenationRequest]) (*connect.Response[baboon.SetHypenationResponse], error)
	// ListHypenations is used to list words in the hypenation dictionary.
	ListHypenations(context.Context, *connect.Request[baboon.ListHypenationsRequest]) (*connect.Response[baboon.ListHypenationsResponse], error)
	// RemoveHypenation is used to remove a custom hypenation for a word.
	RemoveHypenation(context.Context, *connect.Request[baboon.RemoveHypenationRequest]) (*connect.Response[baboon.RemoveHypenationResponse], error)
}

// NewPrintHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPrintHandler(svc PrintHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	printMethods := baboon.File_baboon_service_proto.Services().ByName("Print").Methods()
	printRenderArticleHandler := connect.NewUnaryHandler(
		PrintRenderArticleProcedure,
		svc.RenderArticle,
		connect.WithSchema(printMethods.ByName("RenderArticle")),
		connect.WithHandlerOptions(opts...),
	)
	printGetEditableArchiveHandler := connect.NewUnaryHandler(
		PrintGetEditableArchiveProcedure,
		svc.GetEditableArchive,
		connect.WithSchema(printMethods.ByName("GetEditableArchive")),
		connect.WithHandlerOptions(opts...),
	)
	printLayoutPreviewHandler := connect.NewUnaryHandler(
		PrintLayoutPreviewProcedure,
		svc.LayoutPreview,
		connect.WithSchema(printMethods.ByName("LayoutPreview")),
		connect.WithHandlerOptions(opts...),
	)
	printCreateFlowHandler := connect.NewUnaryHandler(
		PrintCreateFlowProcedure,
		svc.CreateFlow,
		connect.WithSchema(printMethods.ByName("CreateFlow")),
		connect.WithHandlerOptions(opts...),
	)
	printCopyArticleToFlowHandler := connect.NewUnaryHandler(
		PrintCopyArticleToFlowProcedure,
		svc.CopyArticleToFlow,
		connect.WithSchema(printMethods.ByName("CopyArticleToFlow")),
		connect.WithHandlerOptions(opts...),
	)
	printGetScribusInfoHandler := connect.NewUnaryHandler(
		PrintGetScribusInfoProcedure,
		svc.GetScribusInfo,
		connect.WithSchema(printMethods.ByName("GetScribusInfo")),
		connect.WithHandlerOptions(opts...),
	)
	printGetRenderedArticlesHandler := connect.NewUnaryHandler(
		PrintGetRenderedArticlesProcedure,
		svc.GetRenderedArticles,
		connect.WithSchema(printMethods.ByName("GetRenderedArticles")),
		connect.WithHandlerOptions(opts...),
	)
	printSetHypenationHandler := connect.NewUnaryHandler(
		PrintSetHypenationProcedure,
		svc.SetHypenation,
		connect.WithSchema(printMethods.ByName("SetHypenation")),
		connect.WithHandlerOptions(opts...),
	)
	printListHypenationsHandler := connect.NewUnaryHandler(
		PrintListHypenationsProcedure,
		svc.ListHypenations,
		connect.WithSchema(printMethods.ByName("ListHypenations")),
		connect.WithHandlerOptions(opts...),
	)
	printRemoveHypenationHandler := connect.NewUnaryHandler(
		PrintRemoveHypenationProcedure,
		svc.RemoveHypenation,
		connect.WithSchema(printMethods.ByName("RemoveHypenation")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ttab.baboon.Print/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PrintRenderArticleProcedure:
			printRenderArticleHandler.ServeHTTP(w, r)
		case PrintGetEditableArchiveProcedure:
			printGetEditableArchiveHandler.ServeHTTP(w, r)
		case PrintLayoutPreviewProcedure:
			printLayoutPreviewHandler.ServeHTTP(w, r)
		case PrintCreateFlowProcedure:
			printCreateFlowHandler.ServeHTTP(w, r)
		case PrintCopyArticleToFlowProcedure:
			printCopyArticleToFlowHandler.ServeHTTP(w, r)
		case PrintGetScribusInfoProcedure:
			printGetScribusInfoHandler.ServeHTTP(w, r)
		case PrintGetRenderedArticlesProcedure:
			printGetRenderedArticlesHandler.ServeHTTP(w, r)
		case PrintSetHypenationProcedure:
			printSetHypenationHandler.ServeHTTP(w, r)
		case PrintListHypenationsProcedure:
			printListHypenationsHandler.ServeHTTP(w, r)
		case PrintRemoveHypenationProcedure:
			printRemoveHypenationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPrintHandler returns CodeUnimplemented from all methods.
type UnimplementedPrintHandler struct{}

func (UnimplementedPrintHandler) RenderArticle(context.Context, *connect.Request[baboon.RenderArticleRequest]) (*connect.Response[baboon.RenderArticleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.baboon.Print.RenderArticle is not implemented"))
}

func (UnimplementedPrintHandler) GetEditableArchive(context.Context, *connect.Request[baboon.GetEditableArchiveRequest]) (*connect.Response[baboon.GetEditableArchiveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.baboon.Print.GetEditableArchive is not implemented"))
}

func (UnimplementedPrintHandler) LayoutPreview(context.Context, *connect.Request[baboon.LayoutPreviewRequest]) (*connect.Response[baboon.LayoutPreviewResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.baboon.Print.LayoutPreview is not implemented"))
}

func (UnimplementedPrintHandler) CreateFlow(context.Context, *connect.Request[baboon.CreateFlowRequest]) (*connect.Response[baboon.CreateFlowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.baboon.Print.CreateFlow is not implemented"))
}

func (UnimplementedPrintHandler) CopyArticleToFlow(context.Context, *connect.Request[baboon.CopyArticleToFlowRequest]) (*connect.Response[baboon.CopyArticleToFlowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.baboon.Print.CopyArticleToFlow is not implemented"))
}

func (UnimplementedPrintHandler) GetScribusInfo(context.Context, *connect.Request[baboon.GetScribusInfoRequest]) (*connect.Response[baboon.GetScribusInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.baboon.Print.GetScribusInfo is not implemented"))
}

func (UnimplementedPrintHandler) GetRenderedArticles(context.Context, *connect.Request[baboon.GetRenderedArticlesRequest]) (*connect.Response[baboon.GetRenderedArticlesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.baboon.Print.GetRenderedArticles is not implemented"))
}

func (UnimplementedPrintHandler) SetHypenation(context.Context, *connect.Request[baboon.SetHypenationRequest]) (*connect.Response[baboon.SetHypenationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.baboon.Print.SetHypenation is not implemented"))
}

func (UnimplementedPrintHandler) ListHypenations(context.Context, *connect.Request[baboon.ListHypenationsRequest]) (*connect.Response[baboon.ListHypenationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.baboon.Print.ListHypenations is not implemented"))
}

func (UnimplementedPrintHandler) RemoveHypenation(context.Context, *connect.Request[baboon.RemoveHypenationRequest]) (*connect.Response[baboon.RemoveHypenationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.baboon.Print.RemoveHypenation is not implemented"))
}
