// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: genai/service.proto

package genai

import (
	newsdoc "github.com/ttab/elephant-api/newsdoc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStatus int32

const (
	JobStatus_STATUS_UNKNOWN JobStatus = 0
	JobStatus_STATUS_DONE    JobStatus = 1
	JobStatus_STATUS_FAILED  JobStatus = 2
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_DONE",
		2: "STATUS_FAILED",
	}
	JobStatus_value = map[string]int32{
		"STATUS_UNKNOWN": 0,
		"STATUS_DONE":    1,
		"STATUS_FAILED":  2,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_genai_service_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_genai_service_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_genai_service_proto_rawDescGZIP(), []int{0}
}

type JobType int32

const (
	JobType_JOB_TYPE_UNKNOWN  JobType = 0
	JobType_JOB_TYPE_DOCUMENT JobType = 1
	JobType_JOB_TYPE_FEEDBACK JobType = 2
	JobType_JOB_TYPE_TEXT     JobType = 3
)

// Enum value maps for JobType.
var (
	JobType_name = map[int32]string{
		0: "JOB_TYPE_UNKNOWN",
		1: "JOB_TYPE_DOCUMENT",
		2: "JOB_TYPE_FEEDBACK",
		3: "JOB_TYPE_TEXT",
	}
	JobType_value = map[string]int32{
		"JOB_TYPE_UNKNOWN":  0,
		"JOB_TYPE_DOCUMENT": 1,
		"JOB_TYPE_FEEDBACK": 2,
		"JOB_TYPE_TEXT":     3,
	}
)

func (x JobType) Enum() *JobType {
	p := new(JobType)
	*p = x
	return p
}

func (x JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_genai_service_proto_enumTypes[1].Descriptor()
}

func (JobType) Type() protoreflect.EnumType {
	return &file_genai_service_proto_enumTypes[1]
}

func (x JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobType.Descriptor instead.
func (JobType) EnumDescriptor() ([]byte, []int) {
	return file_genai_service_proto_rawDescGZIP(), []int{1}
}

type DocumentFromTextRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model is the URI of the model to use.
	Model string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	// Text to send as input.
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// UUID to set for the document.
	Uuid string `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// URI to set for the document.
	Uri string `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	// AdditionalLinks that should be added to the generated document.
	AdditionalLinks []*newsdoc.Block `protobuf:"bytes,5,rep,name=additionalLinks,proto3" json:"additionalLinks,omitempty"`
	// AdditionalMeta blocks that should be added to the generated document.
	AdditionalMeta []*newsdoc.Block `protobuf:"bytes,6,rep,name=additionalMeta,proto3" json:"additionalMeta,omitempty"`
	// AsyncTimeoutSeconds is the time after which a JobID will be returned
	// instead of a direct result. Optional, defaults to no timeout.
	AsyncTimeoutSeconds int64 `protobuf:"varint,7,opt,name=async_timeout_seconds,json=asyncTimeoutSeconds,proto3" json:"async_timeout_seconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DocumentFromTextRequest) Reset() {
	*x = DocumentFromTextRequest{}
	mi := &file_genai_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentFromTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentFromTextRequest) ProtoMessage() {}

func (x *DocumentFromTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_genai_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentFromTextRequest.ProtoReflect.Descriptor instead.
func (*DocumentFromTextRequest) Descriptor() ([]byte, []int) {
	return file_genai_service_proto_rawDescGZIP(), []int{0}
}

func (x *DocumentFromTextRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DocumentFromTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DocumentFromTextRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *DocumentFromTextRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *DocumentFromTextRequest) GetAdditionalLinks() []*newsdoc.Block {
	if x != nil {
		return x.AdditionalLinks
	}
	return nil
}

func (x *DocumentFromTextRequest) GetAdditionalMeta() []*newsdoc.Block {
	if x != nil {
		return x.AdditionalMeta
	}
	return nil
}

func (x *DocumentFromTextRequest) GetAsyncTimeoutSeconds() int64 {
	if x != nil {
		return x.AsyncTimeoutSeconds
	}
	return 0
}

type DocumentFromTextResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JobID that identifies the job.
	JobId int64 `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Document that was generated.
	Document      *newsdoc.Document `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentFromTextResponse) Reset() {
	*x = DocumentFromTextResponse{}
	mi := &file_genai_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentFromTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentFromTextResponse) ProtoMessage() {}

func (x *DocumentFromTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_genai_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentFromTextResponse.ProtoReflect.Descriptor instead.
func (*DocumentFromTextResponse) Descriptor() ([]byte, []int) {
	return file_genai_service_proto_rawDescGZIP(), []int{1}
}

func (x *DocumentFromTextResponse) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *DocumentFromTextResponse) GetDocument() *newsdoc.Document {
	if x != nil {
		return x.Document
	}
	return nil
}

type LanguageFeedbackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model is the URI of the model to use.
	Model string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	// Paragraphs to review. Feedback will reference these paragraphs by
	// index. Optional, but either paragraphs, document_uuid, or document must be
	// set.
	Paragraphs []string `protobuf:"bytes,2,rep,name=paragraphs,proto3" json:"paragraphs,omitempty"`
	// DocumentUUID of the document to give feedback on. The "core/text" content
	// blocks will be extracted and the feedback will reference them by
	// index. Optional, but either paragraphs, document_uuid, or document must be
	// set.
	DocumentUuid string `protobuf:"bytes,3,opt,name=document_uuid,json=documentUuid,proto3" json:"document_uuid,omitempty"`
	// Document is the document to give feedback on. The "core/text" content
	// blocks will be extracted and the feedback will reference them by
	// index. Optional, but either paragraphs, document_uuid, or document must be
	// set.
	Document *newsdoc.Document `protobuf:"bytes,4,opt,name=document,proto3" json:"document,omitempty"`
	// AsyncTimeoutSeconds is the time after which a JobID will be returned
	// instead of a direct result. Optional, defaults to no timeout.
	AsyncTimeoutSeconds int64 `protobuf:"varint,5,opt,name=async_timeout_seconds,json=asyncTimeoutSeconds,proto3" json:"async_timeout_seconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LanguageFeedbackRequest) Reset() {
	*x = LanguageFeedbackRequest{}
	mi := &file_genai_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanguageFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguageFeedbackRequest) ProtoMessage() {}

func (x *LanguageFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_genai_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguageFeedbackRequest.ProtoReflect.Descriptor instead.
func (*LanguageFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_genai_service_proto_rawDescGZIP(), []int{2}
}

func (x *LanguageFeedbackRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LanguageFeedbackRequest) GetParagraphs() []string {
	if x != nil {
		return x.Paragraphs
	}
	return nil
}

func (x *LanguageFeedbackRequest) GetDocumentUuid() string {
	if x != nil {
		return x.DocumentUuid
	}
	return ""
}

func (x *LanguageFeedbackRequest) GetDocument() *newsdoc.Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *LanguageFeedbackRequest) GetAsyncTimeoutSeconds() int64 {
	if x != nil {
		return x.AsyncTimeoutSeconds
	}
	return 0
}

type LanguageFeedbackResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JobID that identifies the created job.
	JobId int64 `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Feedback items.
	Feedback []*LanguageFeedback `protobuf:"bytes,2,rep,name=feedback,proto3" json:"feedback,omitempty"`
	// Paragraphs are the paragraphs being referenced in the feedback.
	Paragraphs    []string `protobuf:"bytes,3,rep,name=paragraphs,proto3" json:"paragraphs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LanguageFeedbackResponse) Reset() {
	*x = LanguageFeedbackResponse{}
	mi := &file_genai_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanguageFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguageFeedbackResponse) ProtoMessage() {}

func (x *LanguageFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_genai_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguageFeedbackResponse.ProtoReflect.Descriptor instead.
func (*LanguageFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_genai_service_proto_rawDescGZIP(), []int{3}
}

func (x *LanguageFeedbackResponse) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *LanguageFeedbackResponse) GetFeedback() []*LanguageFeedback {
	if x != nil {
		return x.Feedback
	}
	return nil
}

func (x *LanguageFeedbackResponse) GetParagraphs() []string {
	if x != nil {
		return x.Paragraphs
	}
	return nil
}

type LanguageFeedback struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Paragraph index. Set to -1 if the feedback couldn't be connected to a
	// specific paragraph.
	Paragraph int64 `protobuf:"varint,1,opt,name=paragraph,proto3" json:"paragraph,omitempty"`
	// Original text excerpt.
	Original string `protobuf:"bytes,2,opt,name=original,proto3" json:"original,omitempty"`
	// Suggestion for new text.
	Suggestion string `protobuf:"bytes,4,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	// Motivation for the change.
	Motivation string `protobuf:"bytes,5,opt,name=motivation,proto3" json:"motivation,omitempty"`
	// ParagraphID is present when the feedback is performed on a document and the
	// text block had a ID.
	ParagraphId   string `protobuf:"bytes,6,opt,name=paragraph_id,json=paragraphId,proto3" json:"paragraph_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LanguageFeedback) Reset() {
	*x = LanguageFeedback{}
	mi := &file_genai_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanguageFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguageFeedback) ProtoMessage() {}

func (x *LanguageFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_genai_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguageFeedback.ProtoReflect.Descriptor instead.
func (*LanguageFeedback) Descriptor() ([]byte, []int) {
	return file_genai_service_proto_rawDescGZIP(), []int{4}
}

func (x *LanguageFeedback) GetParagraph() int64 {
	if x != nil {
		return x.Paragraph
	}
	return 0
}

func (x *LanguageFeedback) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

func (x *LanguageFeedback) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

func (x *LanguageFeedback) GetMotivation() string {
	if x != nil {
		return x.Motivation
	}
	return ""
}

func (x *LanguageFeedback) GetParagraphId() string {
	if x != nil {
		return x.ParagraphId
	}
	return ""
}

type TextRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model is the URI of the model to use.
	Model string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	// Text to send as input.
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// ParseText tries to parse the generated text into blocks if set to true.
	ParseText bool `protobuf:"varint,3,opt,name=parse_text,json=parseText,proto3" json:"parse_text,omitempty"`
	// CharacterCount sets a target for how long the generated text should be.
	CharacterCount int32 `protobuf:"varint,4,opt,name=character_count,json=characterCount,proto3" json:"character_count,omitempty"`
	// AsyncTimeoutSeconds is the time after which a JobID will be returned
	// instead of a direct result. Optional, defaults to no timeout.
	AsyncTimeoutSeconds int64 `protobuf:"varint,5,opt,name=async_timeout_seconds,json=asyncTimeoutSeconds,proto3" json:"async_timeout_seconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TextRequest) Reset() {
	*x = TextRequest{}
	mi := &file_genai_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextRequest) ProtoMessage() {}

func (x *TextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_genai_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextRequest.ProtoReflect.Descriptor instead.
func (*TextRequest) Descriptor() ([]byte, []int) {
	return file_genai_service_proto_rawDescGZIP(), []int{5}
}

func (x *TextRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *TextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextRequest) GetParseText() bool {
	if x != nil {
		return x.ParseText
	}
	return false
}

func (x *TextRequest) GetCharacterCount() int32 {
	if x != nil {
		return x.CharacterCount
	}
	return 0
}

func (x *TextRequest) GetAsyncTimeoutSeconds() int64 {
	if x != nil {
		return x.AsyncTimeoutSeconds
	}
	return 0
}

type TextResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JobID that identifies the created job.
	JobId int64 `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Text is the generated text.
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// Contet blocks generated from the text.
	Content       []*newsdoc.Block `protobuf:"bytes,3,rep,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextResponse) Reset() {
	*x = TextResponse{}
	mi := &file_genai_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextResponse) ProtoMessage() {}

func (x *TextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_genai_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextResponse.ProtoReflect.Descriptor instead.
func (*TextResponse) Descriptor() ([]byte, []int) {
	return file_genai_service_proto_rawDescGZIP(), []int{6}
}

func (x *TextResponse) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *TextResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextResponse) GetContent() []*newsdoc.Block {
	if x != nil {
		return x.Content
	}
	return nil
}

type ListJobsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// After lists jobs after the given ID. Optional, omit to get latest.
	After         int64 `protobuf:"varint,1,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_genai_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_genai_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_genai_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListJobsRequest) GetAfter() int64 {
	if x != nil {
		return x.After
	}
	return 0
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobReference        `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_genai_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_genai_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_genai_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListJobsResponse) GetJobs() []*JobReference {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type WaitForJobsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Jobs and the currently known version that the client is waiting
	// for. Required.
	Jobs map[int64]int64 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// MaxWaitSec is the maximum time to wait for updates. Optional, defaults to
	// 10.
	MaxWaitSec    int64 `protobuf:"varint,2,opt,name=max_wait_sec,json=maxWaitSec,proto3" json:"max_wait_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForJobsRequest) Reset() {
	*x = WaitForJobsRequest{}
	mi := &file_genai_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForJobsRequest) ProtoMessage() {}

func (x *WaitForJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_genai_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForJobsRequest.ProtoReflect.Descriptor instead.
func (*WaitForJobsRequest) Descriptor() ([]byte, []int) {
	return file_genai_service_proto_rawDescGZIP(), []int{9}
}

func (x *WaitForJobsRequest) GetJobs() map[int64]int64 {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *WaitForJobsRequest) GetMaxWaitSec() int64 {
	if x != nil {
		return x.MaxWaitSec
	}
	return 0
}

type WaitForJobsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated jobs, can be empty if the wait timed out without any updates.
	Updated       []*JobReference `protobuf:"bytes,1,rep,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForJobsResponse) Reset() {
	*x = WaitForJobsResponse{}
	mi := &file_genai_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForJobsResponse) ProtoMessage() {}

func (x *WaitForJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_genai_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForJobsResponse.ProtoReflect.Descriptor instead.
func (*WaitForJobsResponse) Descriptor() ([]byte, []int) {
	return file_genai_service_proto_rawDescGZIP(), []int{10}
}

func (x *WaitForJobsResponse) GetUpdated() []*JobReference {
	if x != nil {
		return x.Updated
	}
	return nil
}

type GetResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResultRequest) Reset() {
	*x = GetResultRequest{}
	mi := &file_genai_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultRequest) ProtoMessage() {}

func (x *GetResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_genai_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultRequest.ProtoReflect.Descriptor instead.
func (*GetResultRequest) Descriptor() ([]byte, []int) {
	return file_genai_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetResultRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type JobReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        JobStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=ttab.genai.JobStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobReference) Reset() {
	*x = JobReference{}
	mi := &file_genai_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobReference) ProtoMessage() {}

func (x *JobReference) ProtoReflect() protoreflect.Message {
	mi := &file_genai_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobReference.ProtoReflect.Descriptor instead.
func (*JobReference) Descriptor() ([]byte, []int) {
	return file_genai_service_proto_rawDescGZIP(), []int{12}
}

func (x *JobReference) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JobReference) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_STATUS_UNKNOWN
}

type GetResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Type          JobType                `protobuf:"varint,3,opt,name=type,proto3,enum=ttab.genai.JobType" json:"type,omitempty"`
	Status        JobStatus              `protobuf:"varint,4,opt,name=status,proto3,enum=ttab.genai.JobStatus" json:"status,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	Document      *newsdoc.Document      `protobuf:"bytes,7,opt,name=document,proto3" json:"document,omitempty"`
	Feedback      *LanguageFeedback      `protobuf:"bytes,8,opt,name=feedback,proto3" json:"feedback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResultResponse) Reset() {
	*x = GetResultResponse{}
	mi := &file_genai_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultResponse) ProtoMessage() {}

func (x *GetResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_genai_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultResponse.ProtoReflect.Descriptor instead.
func (*GetResultResponse) Descriptor() ([]byte, []int) {
	return file_genai_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetResultResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetResultResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GetResultResponse) GetType() JobType {
	if x != nil {
		return x.Type
	}
	return JobType_JOB_TYPE_UNKNOWN
}

func (x *GetResultResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_STATUS_UNKNOWN
}

func (x *GetResultResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GetResultResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetResultResponse) GetDocument() *newsdoc.Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *GetResultResponse) GetFeedback() *LanguageFeedback {
	if x != nil {
		return x.Feedback
	}
	return nil
}

var File_genai_service_proto protoreflect.FileDescriptor

const file_genai_service_proto_rawDesc = "" +
	"\n" +
	"\x13genai/service.proto\x12\n" +
	"ttab.genai\x1a\x15newsdoc/newsdoc.proto\"\x8f\x02\n" +
	"\x17DocumentFromTextRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04uuid\x18\x03 \x01(\tR\x04uuid\x12\x10\n" +
	"\x03uri\x18\x04 \x01(\tR\x03uri\x128\n" +
	"\x0fadditionalLinks\x18\x05 \x03(\v2\x0e.newsdoc.BlockR\x0fadditionalLinks\x126\n" +
	"\x0eadditionalMeta\x18\x06 \x03(\v2\x0e.newsdoc.BlockR\x0eadditionalMeta\x122\n" +
	"\x15async_timeout_seconds\x18\a \x01(\x03R\x13asyncTimeoutSeconds\"`\n" +
	"\x18DocumentFromTextResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12-\n" +
	"\bdocument\x18\x02 \x01(\v2\x11.newsdoc.DocumentR\bdocument\"\xd7\x01\n" +
	"\x17LanguageFeedbackRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1e\n" +
	"\n" +
	"paragraphs\x18\x02 \x03(\tR\n" +
	"paragraphs\x12#\n" +
	"\rdocument_uuid\x18\x03 \x01(\tR\fdocumentUuid\x12-\n" +
	"\bdocument\x18\x04 \x01(\v2\x11.newsdoc.DocumentR\bdocument\x122\n" +
	"\x15async_timeout_seconds\x18\x05 \x01(\x03R\x13asyncTimeoutSeconds\"\x8b\x01\n" +
	"\x18LanguageFeedbackResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x128\n" +
	"\bfeedback\x18\x02 \x03(\v2\x1c.ttab.genai.LanguageFeedbackR\bfeedback\x12\x1e\n" +
	"\n" +
	"paragraphs\x18\x03 \x03(\tR\n" +
	"paragraphs\"\xaf\x01\n" +
	"\x10LanguageFeedback\x12\x1c\n" +
	"\tparagraph\x18\x01 \x01(\x03R\tparagraph\x12\x1a\n" +
	"\boriginal\x18\x02 \x01(\tR\boriginal\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x04 \x01(\tR\n" +
	"suggestion\x12\x1e\n" +
	"\n" +
	"motivation\x18\x05 \x01(\tR\n" +
	"motivation\x12!\n" +
	"\fparagraph_id\x18\x06 \x01(\tR\vparagraphId\"\xb3\x01\n" +
	"\vTextRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"parse_text\x18\x03 \x01(\bR\tparseText\x12'\n" +
	"\x0fcharacter_count\x18\x04 \x01(\x05R\x0echaracterCount\x122\n" +
	"\x15async_timeout_seconds\x18\x05 \x01(\x03R\x13asyncTimeoutSeconds\"c\n" +
	"\fTextResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12(\n" +
	"\acontent\x18\x03 \x03(\v2\x0e.newsdoc.BlockR\acontent\"'\n" +
	"\x0fListJobsRequest\x12\x14\n" +
	"\x05after\x18\x01 \x01(\x03R\x05after\"@\n" +
	"\x10ListJobsResponse\x12,\n" +
	"\x04jobs\x18\x01 \x03(\v2\x18.ttab.genai.JobReferenceR\x04jobs\"\xad\x01\n" +
	"\x12WaitForJobsRequest\x12<\n" +
	"\x04jobs\x18\x01 \x03(\v2(.ttab.genai.WaitForJobsRequest.JobsEntryR\x04jobs\x12 \n" +
	"\fmax_wait_sec\x18\x02 \x01(\x03R\n" +
	"maxWaitSec\x1a7\n" +
	"\tJobsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"I\n" +
	"\x13WaitForJobsResponse\x122\n" +
	"\aupdated\x18\x01 \x03(\v2\x18.ttab.genai.JobReferenceR\aupdated\"\"\n" +
	"\x10GetResultRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"M\n" +
	"\fJobReference\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.ttab.genai.JobStatusR\x06status\"\xaf\x02\n" +
	"\x11GetResultResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.ttab.genai.JobTypeR\x04type\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.ttab.genai.JobStatusR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12-\n" +
	"\bdocument\x18\a \x01(\v2\x11.newsdoc.DocumentR\bdocument\x128\n" +
	"\bfeedback\x18\b \x01(\v2\x1c.ttab.genai.LanguageFeedbackR\bfeedback*C\n" +
	"\tJobStatus\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vSTATUS_DONE\x10\x01\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x02*`\n" +
	"\aJobType\x12\x14\n" +
	"\x10JOB_TYPE_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11JOB_TYPE_DOCUMENT\x10\x01\x12\x15\n" +
	"\x11JOB_TYPE_FEEDBACK\x10\x02\x12\x11\n" +
	"\rJOB_TYPE_TEXT\x10\x032\xe4\x03\n" +
	"\bGenerate\x12]\n" +
	"\x10DocumentFromText\x12#.ttab.genai.DocumentFromTextRequest\x1a$.ttab.genai.DocumentFromTextResponse\x12]\n" +
	"\x10LanguageFeedback\x12#.ttab.genai.LanguageFeedbackRequest\x1a$.ttab.genai.LanguageFeedbackResponse\x129\n" +
	"\x04Text\x12\x17.ttab.genai.TextRequest\x1a\x18.ttab.genai.TextResponse\x12E\n" +
	"\bListJobs\x12\x1b.ttab.genai.ListJobsRequest\x1a\x1c.ttab.genai.ListJobsResponse\x12N\n" +
	"\vWaitForJobs\x12\x1e.ttab.genai.WaitForJobsRequest\x1a\x1f.ttab.genai.WaitForJobsResponse\x12H\n" +
	"\tGetResult\x12\x1c.ttab.genai.GetResultRequest\x1a\x1d.ttab.genai.GetResultResponseB'Z%github.com/ttab/elephant-tt-api/genaib\x06proto3"

var (
	file_genai_service_proto_rawDescOnce sync.Once
	file_genai_service_proto_rawDescData []byte
)

func file_genai_service_proto_rawDescGZIP() []byte {
	file_genai_service_proto_rawDescOnce.Do(func() {
		file_genai_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_genai_service_proto_rawDesc), len(file_genai_service_proto_rawDesc)))
	})
	return file_genai_service_proto_rawDescData
}

var file_genai_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_genai_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_genai_service_proto_goTypes = []any{
	(JobStatus)(0),                   // 0: ttab.genai.JobStatus
	(JobType)(0),                     // 1: ttab.genai.JobType
	(*DocumentFromTextRequest)(nil),  // 2: ttab.genai.DocumentFromTextRequest
	(*DocumentFromTextResponse)(nil), // 3: ttab.genai.DocumentFromTextResponse
	(*LanguageFeedbackRequest)(nil),  // 4: ttab.genai.LanguageFeedbackRequest
	(*LanguageFeedbackResponse)(nil), // 5: ttab.genai.LanguageFeedbackResponse
	(*LanguageFeedback)(nil),         // 6: ttab.genai.LanguageFeedback
	(*TextRequest)(nil),              // 7: ttab.genai.TextRequest
	(*TextResponse)(nil),             // 8: ttab.genai.TextResponse
	(*ListJobsRequest)(nil),          // 9: ttab.genai.ListJobsRequest
	(*ListJobsResponse)(nil),         // 10: ttab.genai.ListJobsResponse
	(*WaitForJobsRequest)(nil),       // 11: ttab.genai.WaitForJobsRequest
	(*WaitForJobsResponse)(nil),      // 12: ttab.genai.WaitForJobsResponse
	(*GetResultRequest)(nil),         // 13: ttab.genai.GetResultRequest
	(*JobReference)(nil),             // 14: ttab.genai.JobReference
	(*GetResultResponse)(nil),        // 15: ttab.genai.GetResultResponse
	nil,                              // 16: ttab.genai.WaitForJobsRequest.JobsEntry
	(*newsdoc.Block)(nil),            // 17: newsdoc.Block
	(*newsdoc.Document)(nil),         // 18: newsdoc.Document
}
var file_genai_service_proto_depIdxs = []int32{
	17, // 0: ttab.genai.DocumentFromTextRequest.additionalLinks:type_name -> newsdoc.Block
	17, // 1: ttab.genai.DocumentFromTextRequest.additionalMeta:type_name -> newsdoc.Block
	18, // 2: ttab.genai.DocumentFromTextResponse.document:type_name -> newsdoc.Document
	18, // 3: ttab.genai.LanguageFeedbackRequest.document:type_name -> newsdoc.Document
	6,  // 4: ttab.genai.LanguageFeedbackResponse.feedback:type_name -> ttab.genai.LanguageFeedback
	17, // 5: ttab.genai.TextResponse.content:type_name -> newsdoc.Block
	14, // 6: ttab.genai.ListJobsResponse.jobs:type_name -> ttab.genai.JobReference
	16, // 7: ttab.genai.WaitForJobsRequest.jobs:type_name -> ttab.genai.WaitForJobsRequest.JobsEntry
	14, // 8: ttab.genai.WaitForJobsResponse.updated:type_name -> ttab.genai.JobReference
	0,  // 9: ttab.genai.JobReference.status:type_name -> ttab.genai.JobStatus
	1,  // 10: ttab.genai.GetResultResponse.type:type_name -> ttab.genai.JobType
	0,  // 11: ttab.genai.GetResultResponse.status:type_name -> ttab.genai.JobStatus
	18, // 12: ttab.genai.GetResultResponse.document:type_name -> newsdoc.Document
	6,  // 13: ttab.genai.GetResultResponse.feedback:type_name -> ttab.genai.LanguageFeedback
	2,  // 14: ttab.genai.Generate.DocumentFromText:input_type -> ttab.genai.DocumentFromTextRequest
	4,  // 15: ttab.genai.Generate.LanguageFeedback:input_type -> ttab.genai.LanguageFeedbackRequest
	7,  // 16: ttab.genai.Generate.Text:input_type -> ttab.genai.TextRequest
	9,  // 17: ttab.genai.Generate.ListJobs:input_type -> ttab.genai.ListJobsRequest
	11, // 18: ttab.genai.Generate.WaitForJobs:input_type -> ttab.genai.WaitForJobsRequest
	13, // 19: ttab.genai.Generate.GetResult:input_type -> ttab.genai.GetResultRequest
	3,  // 20: ttab.genai.Generate.DocumentFromText:output_type -> ttab.genai.DocumentFromTextResponse
	5,  // 21: ttab.genai.Generate.LanguageFeedback:output_type -> ttab.genai.LanguageFeedbackResponse
	8,  // 22: ttab.genai.Generate.Text:output_type -> ttab.genai.TextResponse
	10, // 23: ttab.genai.Generate.ListJobs:output_type -> ttab.genai.ListJobsResponse
	12, // 24: ttab.genai.Generate.WaitForJobs:output_type -> ttab.genai.WaitForJobsResponse
	15, // 25: ttab.genai.Generate.GetResult:output_type -> ttab.genai.GetResultResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_genai_service_proto_init() }
func file_genai_service_proto_init() {
	if File_genai_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_genai_service_proto_rawDesc), len(file_genai_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_genai_service_proto_goTypes,
		DependencyIndexes: file_genai_service_proto_depIdxs,
		EnumInfos:         file_genai_service_proto_enumTypes,
		MessageInfos:      file_genai_service_proto_msgTypes,
	}.Build()
	File_genai_service_proto = out.File
	file_genai_service_proto_goTypes = nil
	file_genai_service_proto_depIdxs = nil
}
