// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ntb/service.proto

package ntbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	ntb "github.com/ttab/elephant-tt-api/ntb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MetadataName is the fully-qualified name of the Metadata service.
	MetadataName = "ttab.ntb.Metadata"
	// MediaName is the fully-qualified name of the Media service.
	MediaName = "ttab.ntb.Media"
	// NynorskName is the fully-qualified name of the Nynorsk service.
	NynorskName = "ttab.ntb.Nynorsk"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MetadataGetAssignmentProcedure is the fully-qualified name of the Metadata's GetAssignment RPC.
	MetadataGetAssignmentProcedure = "/ttab.ntb.Metadata/GetAssignment"
	// MetadataListAssignmentsProcedure is the fully-qualified name of the Metadata's ListAssignments
	// RPC.
	MetadataListAssignmentsProcedure = "/ttab.ntb.Metadata/ListAssignments"
	// MediaSearchProcedure is the fully-qualified name of the Media's Search RPC.
	MediaSearchProcedure = "/ttab.ntb.Media/Search"
	// MediaGetItemProcedure is the fully-qualified name of the Media's GetItem RPC.
	MediaGetItemProcedure = "/ttab.ntb.Media/GetItem"
	// MediaGetSortFieldsProcedure is the fully-qualified name of the Media's GetSortFields RPC.
	MediaGetSortFieldsProcedure = "/ttab.ntb.Media/GetSortFields"
	// NynorskTranslateProcedure is the fully-qualified name of the Nynorsk's Translate RPC.
	NynorskTranslateProcedure = "/ttab.ntb.Nynorsk/Translate"
	// NynorskGetLanguagePrefsProcedure is the fully-qualified name of the Nynorsk's GetLanguagePrefs
	// RPC.
	NynorskGetLanguagePrefsProcedure = "/ttab.ntb.Nynorsk/GetLanguagePrefs"
	// NynorskGetDocumentFormatsProcedure is the fully-qualified name of the Nynorsk's
	// GetDocumentFormats RPC.
	NynorskGetDocumentFormatsProcedure = "/ttab.ntb.Nynorsk/GetDocumentFormats"
	// NynorskGetPreferenceTemplatesProcedure is the fully-qualified name of the Nynorsk's
	// GetPreferenceTemplates RPC.
	NynorskGetPreferenceTemplatesProcedure = "/ttab.ntb.Nynorsk/GetPreferenceTemplates"
)

// MetadataClient is a client for the ttab.ntb.Metadata service.
type MetadataClient interface {
	// GetAssignment returns metadata for a specific assignment.
	GetAssignment(context.Context, *connect.Request[ntb.GetAssignmentRequest]) (*connect.Response[ntb.GetAssignmentResponse], error)
	// ListAssignments returns metadata for all assignments.
	ListAssignments(context.Context, *connect.Request[ntb.ListAssignmentsRequest]) (*connect.Response[ntb.ListAssignmentsResponse], error)
}

// NewMetadataClient constructs a client for the ttab.ntb.Metadata service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMetadataClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MetadataClient {
	baseURL = strings.TrimRight(baseURL, "/")
	metadataMethods := ntb.File_ntb_service_proto.Services().ByName("Metadata").Methods()
	return &metadataClient{
		getAssignment: connect.NewClient[ntb.GetAssignmentRequest, ntb.GetAssignmentResponse](
			httpClient,
			baseURL+MetadataGetAssignmentProcedure,
			connect.WithSchema(metadataMethods.ByName("GetAssignment")),
			connect.WithClientOptions(opts...),
		),
		listAssignments: connect.NewClient[ntb.ListAssignmentsRequest, ntb.ListAssignmentsResponse](
			httpClient,
			baseURL+MetadataListAssignmentsProcedure,
			connect.WithSchema(metadataMethods.ByName("ListAssignments")),
			connect.WithClientOptions(opts...),
		),
	}
}

// metadataClient implements MetadataClient.
type metadataClient struct {
	getAssignment   *connect.Client[ntb.GetAssignmentRequest, ntb.GetAssignmentResponse]
	listAssignments *connect.Client[ntb.ListAssignmentsRequest, ntb.ListAssignmentsResponse]
}

// GetAssignment calls ttab.ntb.Metadata.GetAssignment.
func (c *metadataClient) GetAssignment(ctx context.Context, req *connect.Request[ntb.GetAssignmentRequest]) (*connect.Response[ntb.GetAssignmentResponse], error) {
	return c.getAssignment.CallUnary(ctx, req)
}

// ListAssignments calls ttab.ntb.Metadata.ListAssignments.
func (c *metadataClient) ListAssignments(ctx context.Context, req *connect.Request[ntb.ListAssignmentsRequest]) (*connect.Response[ntb.ListAssignmentsResponse], error) {
	return c.listAssignments.CallUnary(ctx, req)
}

// MetadataHandler is an implementation of the ttab.ntb.Metadata service.
type MetadataHandler interface {
	// GetAssignment returns metadata for a specific assignment.
	GetAssignment(context.Context, *connect.Request[ntb.GetAssignmentRequest]) (*connect.Response[ntb.GetAssignmentResponse], error)
	// ListAssignments returns metadata for all assignments.
	ListAssignments(context.Context, *connect.Request[ntb.ListAssignmentsRequest]) (*connect.Response[ntb.ListAssignmentsResponse], error)
}

// NewMetadataHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMetadataHandler(svc MetadataHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	metadataMethods := ntb.File_ntb_service_proto.Services().ByName("Metadata").Methods()
	metadataGetAssignmentHandler := connect.NewUnaryHandler(
		MetadataGetAssignmentProcedure,
		svc.GetAssignment,
		connect.WithSchema(metadataMethods.ByName("GetAssignment")),
		connect.WithHandlerOptions(opts...),
	)
	metadataListAssignmentsHandler := connect.NewUnaryHandler(
		MetadataListAssignmentsProcedure,
		svc.ListAssignments,
		connect.WithSchema(metadataMethods.ByName("ListAssignments")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ttab.ntb.Metadata/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MetadataGetAssignmentProcedure:
			metadataGetAssignmentHandler.ServeHTTP(w, r)
		case MetadataListAssignmentsProcedure:
			metadataListAssignmentsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMetadataHandler returns CodeUnimplemented from all methods.
type UnimplementedMetadataHandler struct{}

func (UnimplementedMetadataHandler) GetAssignment(context.Context, *connect.Request[ntb.GetAssignmentRequest]) (*connect.Response[ntb.GetAssignmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.ntb.Metadata.GetAssignment is not implemented"))
}

func (UnimplementedMetadataHandler) ListAssignments(context.Context, *connect.Request[ntb.ListAssignmentsRequest]) (*connect.Response[ntb.ListAssignmentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.ntb.Metadata.ListAssignments is not implemented"))
}

// MediaClient is a client for the ttab.ntb.Media service.
type MediaClient interface {
	// Search in a media archive.
	Search(context.Context, *connect.Request[ntb.SearchRequest]) (*connect.Response[ntb.SearchResponse], error)
	// GetItem fetches a single media item.
	GetItem(context.Context, *connect.Request[ntb.GetItemRequest]) (*connect.Response[ntb.GetItemResponse], error)
	// GetSortFields returns the available sort fields.
	GetSortFields(context.Context, *connect.Request[ntb.GetSortFieldsRequest]) (*connect.Response[ntb.GetSortFieldsResponse], error)
}

// NewMediaClient constructs a client for the ttab.ntb.Media service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMediaClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MediaClient {
	baseURL = strings.TrimRight(baseURL, "/")
	mediaMethods := ntb.File_ntb_service_proto.Services().ByName("Media").Methods()
	return &mediaClient{
		search: connect.NewClient[ntb.SearchRequest, ntb.SearchResponse](
			httpClient,
			baseURL+MediaSearchProcedure,
			connect.WithSchema(mediaMethods.ByName("Search")),
			connect.WithClientOptions(opts...),
		),
		getItem: connect.NewClient[ntb.GetItemRequest, ntb.GetItemResponse](
			httpClient,
			baseURL+MediaGetItemProcedure,
			connect.WithSchema(mediaMethods.ByName("GetItem")),
			connect.WithClientOptions(opts...),
		),
		getSortFields: connect.NewClient[ntb.GetSortFieldsRequest, ntb.GetSortFieldsResponse](
			httpClient,
			baseURL+MediaGetSortFieldsProcedure,
			connect.WithSchema(mediaMethods.ByName("GetSortFields")),
			connect.WithClientOptions(opts...),
		),
	}
}

// mediaClient implements MediaClient.
type mediaClient struct {
	search        *connect.Client[ntb.SearchRequest, ntb.SearchResponse]
	getItem       *connect.Client[ntb.GetItemRequest, ntb.GetItemResponse]
	getSortFields *connect.Client[ntb.GetSortFieldsRequest, ntb.GetSortFieldsResponse]
}

// Search calls ttab.ntb.Media.Search.
func (c *mediaClient) Search(ctx context.Context, req *connect.Request[ntb.SearchRequest]) (*connect.Response[ntb.SearchResponse], error) {
	return c.search.CallUnary(ctx, req)
}

// GetItem calls ttab.ntb.Media.GetItem.
func (c *mediaClient) GetItem(ctx context.Context, req *connect.Request[ntb.GetItemRequest]) (*connect.Response[ntb.GetItemResponse], error) {
	return c.getItem.CallUnary(ctx, req)
}

// GetSortFields calls ttab.ntb.Media.GetSortFields.
func (c *mediaClient) GetSortFields(ctx context.Context, req *connect.Request[ntb.GetSortFieldsRequest]) (*connect.Response[ntb.GetSortFieldsResponse], error) {
	return c.getSortFields.CallUnary(ctx, req)
}

// MediaHandler is an implementation of the ttab.ntb.Media service.
type MediaHandler interface {
	// Search in a media archive.
	Search(context.Context, *connect.Request[ntb.SearchRequest]) (*connect.Response[ntb.SearchResponse], error)
	// GetItem fetches a single media item.
	GetItem(context.Context, *connect.Request[ntb.GetItemRequest]) (*connect.Response[ntb.GetItemResponse], error)
	// GetSortFields returns the available sort fields.
	GetSortFields(context.Context, *connect.Request[ntb.GetSortFieldsRequest]) (*connect.Response[ntb.GetSortFieldsResponse], error)
}

// NewMediaHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMediaHandler(svc MediaHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	mediaMethods := ntb.File_ntb_service_proto.Services().ByName("Media").Methods()
	mediaSearchHandler := connect.NewUnaryHandler(
		MediaSearchProcedure,
		svc.Search,
		connect.WithSchema(mediaMethods.ByName("Search")),
		connect.WithHandlerOptions(opts...),
	)
	mediaGetItemHandler := connect.NewUnaryHandler(
		MediaGetItemProcedure,
		svc.GetItem,
		connect.WithSchema(mediaMethods.ByName("GetItem")),
		connect.WithHandlerOptions(opts...),
	)
	mediaGetSortFieldsHandler := connect.NewUnaryHandler(
		MediaGetSortFieldsProcedure,
		svc.GetSortFields,
		connect.WithSchema(mediaMethods.ByName("GetSortFields")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ttab.ntb.Media/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MediaSearchProcedure:
			mediaSearchHandler.ServeHTTP(w, r)
		case MediaGetItemProcedure:
			mediaGetItemHandler.ServeHTTP(w, r)
		case MediaGetSortFieldsProcedure:
			mediaGetSortFieldsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMediaHandler returns CodeUnimplemented from all methods.
type UnimplementedMediaHandler struct{}

func (UnimplementedMediaHandler) Search(context.Context, *connect.Request[ntb.SearchRequest]) (*connect.Response[ntb.SearchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.ntb.Media.Search is not implemented"))
}

func (UnimplementedMediaHandler) GetItem(context.Context, *connect.Request[ntb.GetItemRequest]) (*connect.Response[ntb.GetItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.ntb.Media.GetItem is not implemented"))
}

func (UnimplementedMediaHandler) GetSortFields(context.Context, *connect.Request[ntb.GetSortFieldsRequest]) (*connect.Response[ntb.GetSortFieldsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.ntb.Media.GetSortFields is not implemented"))
}

// NynorskClient is a client for the ttab.ntb.Nynorsk service.
type NynorskClient interface {
	// Translate translates a document between Scandinavian languages.
	Translate(context.Context, *connect.Request[ntb.TranslateRequest]) (*connect.Response[ntb.TranslateResponse], error)
	// GetLanguagePrefs returns the available optional language forms.
	GetLanguagePrefs(context.Context, *connect.Request[ntb.GetLanguagePrefsRequest]) (*connect.Response[ntb.GetLanguagePrefsResponse], error)
	// GetDocumentFormats returns the supported document formats.
	GetDocumentFormats(context.Context, *connect.Request[ntb.GetDocumentFormatsRequest]) (*connect.Response[ntb.GetDocumentFormatsResponse], error)
	// GetPreferenceTemplates returns the available preference templates and the
	// language forms they enable.
	GetPreferenceTemplates(context.Context, *connect.Request[ntb.GetPreferenceTemplatesRequest]) (*connect.Response[ntb.GetPreferenceTemplatesResponse], error)
}

// NewNynorskClient constructs a client for the ttab.ntb.Nynorsk service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNynorskClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NynorskClient {
	baseURL = strings.TrimRight(baseURL, "/")
	nynorskMethods := ntb.File_ntb_service_proto.Services().ByName("Nynorsk").Methods()
	return &nynorskClient{
		translate: connect.NewClient[ntb.TranslateRequest, ntb.TranslateResponse](
			httpClient,
			baseURL+NynorskTranslateProcedure,
			connect.WithSchema(nynorskMethods.ByName("Translate")),
			connect.WithClientOptions(opts...),
		),
		getLanguagePrefs: connect.NewClient[ntb.GetLanguagePrefsRequest, ntb.GetLanguagePrefsResponse](
			httpClient,
			baseURL+NynorskGetLanguagePrefsProcedure,
			connect.WithSchema(nynorskMethods.ByName("GetLanguagePrefs")),
			connect.WithClientOptions(opts...),
		),
		getDocumentFormats: connect.NewClient[ntb.GetDocumentFormatsRequest, ntb.GetDocumentFormatsResponse](
			httpClient,
			baseURL+NynorskGetDocumentFormatsProcedure,
			connect.WithSchema(nynorskMethods.ByName("GetDocumentFormats")),
			connect.WithClientOptions(opts...),
		),
		getPreferenceTemplates: connect.NewClient[ntb.GetPreferenceTemplatesRequest, ntb.GetPreferenceTemplatesResponse](
			httpClient,
			baseURL+NynorskGetPreferenceTemplatesProcedure,
			connect.WithSchema(nynorskMethods.ByName("GetPreferenceTemplates")),
			connect.WithClientOptions(opts...),
		),
	}
}

// nynorskClient implements NynorskClient.
type nynorskClient struct {
	translate              *connect.Client[ntb.TranslateRequest, ntb.TranslateResponse]
	getLanguagePrefs       *connect.Client[ntb.GetLanguagePrefsRequest, ntb.GetLanguagePrefsResponse]
	getDocumentFormats     *connect.Client[ntb.GetDocumentFormatsRequest, ntb.GetDocumentFormatsResponse]
	getPreferenceTemplates *connect.Client[ntb.GetPreferenceTemplatesRequest, ntb.GetPreferenceTemplatesResponse]
}

// Translate calls ttab.ntb.Nynorsk.Translate.
func (c *nynorskClient) Translate(ctx context.Context, req *connect.Request[ntb.TranslateRequest]) (*connect.Response[ntb.TranslateResponse], error) {
	return c.translate.CallUnary(ctx, req)
}

// GetLanguagePrefs calls ttab.ntb.Nynorsk.GetLanguagePrefs.
func (c *nynorskClient) GetLanguagePrefs(ctx context.Context, req *connect.Request[ntb.GetLanguagePrefsRequest]) (*connect.Response[ntb.GetLanguagePrefsResponse], error) {
	return c.getLanguagePrefs.CallUnary(ctx, req)
}

// GetDocumentFormats calls ttab.ntb.Nynorsk.GetDocumentFormats.
func (c *nynorskClient) GetDocumentFormats(ctx context.Context, req *connect.Request[ntb.GetDocumentFormatsRequest]) (*connect.Response[ntb.GetDocumentFormatsResponse], error) {
	return c.getDocumentFormats.CallUnary(ctx, req)
}

// GetPreferenceTemplates calls ttab.ntb.Nynorsk.GetPreferenceTemplates.
func (c *nynorskClient) GetPreferenceTemplates(ctx context.Context, req *connect.Request[ntb.GetPreferenceTemplatesRequest]) (*connect.Response[ntb.GetPreferenceTemplatesResponse], error) {
	return c.getPreferenceTemplates.CallUnary(ctx, req)
}

// NynorskHandler is an implementation of the ttab.ntb.Nynorsk service.
type NynorskHandler interface {
	// Translate translates a document between Scandinavian languages.
	Translate(context.Context, *connect.Request[ntb.TranslateRequest]) (*connect.Response[ntb.TranslateResponse], error)
	// GetLanguagePrefs returns the available optional language forms.
	GetLanguagePrefs(context.Context, *connect.Request[ntb.GetLanguagePrefsRequest]) (*connect.Response[ntb.GetLanguagePrefsResponse], error)
	// GetDocumentFormats returns the supported document formats.
	GetDocumentFormats(context.Context, *connect.Request[ntb.GetDocumentFormatsRequest]) (*connect.Response[ntb.GetDocumentFormatsResponse], error)
	// GetPreferenceTemplates returns the available preference templates and the
	// language forms they enable.
	GetPreferenceTemplates(context.Context, *connect.Request[ntb.GetPreferenceTemplatesRequest]) (*connect.Response[ntb.GetPreferenceTemplatesResponse], error)
}

// NewNynorskHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNynorskHandler(svc NynorskHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	nynorskMethods := ntb.File_ntb_service_proto.Services().ByName("Nynorsk").Methods()
	nynorskTranslateHandler := connect.NewUnaryHandler(
		NynorskTranslateProcedure,
		svc.Translate,
		connect.WithSchema(nynorskMethods.ByName("Translate")),
		connect.WithHandlerOptions(opts...),
	)
	nynorskGetLanguagePrefsHandler := connect.NewUnaryHandler(
		NynorskGetLanguagePrefsProcedure,
		svc.GetLanguagePrefs,
		connect.WithSchema(nynorskMethods.ByName("GetLanguagePrefs")),
		connect.WithHandlerOptions(opts...),
	)
	nynorskGetDocumentFormatsHandler := connect.NewUnaryHandler(
		NynorskGetDocumentFormatsProcedure,
		svc.GetDocumentFormats,
		connect.WithSchema(nynorskMethods.ByName("GetDocumentFormats")),
		connect.WithHandlerOptions(opts...),
	)
	nynorskGetPreferenceTemplatesHandler := connect.NewUnaryHandler(
		NynorskGetPreferenceTemplatesProcedure,
		svc.GetPreferenceTemplates,
		connect.WithSchema(nynorskMethods.ByName("GetPreferenceTemplates")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ttab.ntb.Nynorsk/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NynorskTranslateProcedure:
			nynorskTranslateHandler.ServeHTTP(w, r)
		case NynorskGetLanguagePrefsProcedure:
			nynorskGetLanguagePrefsHandler.ServeHTTP(w, r)
		case NynorskGetDocumentFormatsProcedure:
			nynorskGetDocumentFormatsHandler.ServeHTTP(w, r)
		case NynorskGetPreferenceTemplatesProcedure:
			nynorskGetPreferenceTemplatesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNynorskHandler returns CodeUnimplemented from all methods.
type UnimplementedNynorskHandler struct{}

func (UnimplementedNynorskHandler) Translate(context.Context, *connect.Request[ntb.TranslateRequest]) (*connect.Response[ntb.TranslateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.ntb.Nynorsk.Translate is not implemented"))
}

func (UnimplementedNynorskHandler) GetLanguagePrefs(context.Context, *connect.Request[ntb.GetLanguagePrefsRequest]) (*connect.Response[ntb.GetLanguagePrefsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.ntb.Nynorsk.GetLanguagePrefs is not implemented"))
}

func (UnimplementedNynorskHandler) GetDocumentFormats(context.Context, *connect.Request[ntb.GetDocumentFormatsRequest]) (*connect.Response[ntb.GetDocumentFormatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.ntb.Nynorsk.GetDocumentFormats is not implemented"))
}

func (UnimplementedNynorskHandler) GetPreferenceTemplates(context.Context, *connect.Request[ntb.GetPreferenceTemplatesRequest]) (*connect.Response[ntb.GetPreferenceTemplatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.ntb.Nynorsk.GetPreferenceTemplates is not implemented"))
}
