// Code generated by protoc-gen-elephant-rpc. DO NOT EDIT.
//
// Source: ntb/service.proto

package ntbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	ntb "github.com/ttab/elephant-tt-api/ntb"
	http "net/http"
)

// NewMetadataServiceHandler builds an HTTP handler for the ttab.ntb.Metadata service from an
// implementation of the plain ntb.Metadata interface, and returns the path to mount it on together
// with the handler, just like NewMetadataHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewMetadataServiceHandler(svc ntb.Metadata, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewMetadataHandler(&metadataServiceHandler{svc: svc}, opts...)
}

// metadataServiceHandler implements MetadataHandler on top of a ntb.Metadata.
type metadataServiceHandler struct {
	svc ntb.Metadata
}

func (h *metadataServiceHandler) GetAssignment(ctx context.Context, req *connect.Request[ntb.GetAssignmentRequest]) (*connect.Response[ntb.GetAssignmentResponse], error) {
	res, err := h.svc.GetAssignment(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *metadataServiceHandler) ListAssignments(ctx context.Context, req *connect.Request[ntb.ListAssignmentsRequest]) (*connect.Response[ntb.ListAssignmentsResponse], error) {
	res, err := h.svc.ListAssignments(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewMetadataServiceClient constructs a client for the ttab.ntb.Metadata service that implements
// the plain ntb.Metadata interface, so that it is a drop-in for the Twirp clients. The options are
// the ones NewMetadataClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewMetadataServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ntb.Metadata {
	return &metadataServiceClient{
		client: NewMetadataClient(httpClient, baseURL, opts...),
	}
}

// metadataServiceClient implements ntb.Metadata on top of a MetadataClient.
type metadataServiceClient struct {
	client MetadataClient
}

func (c *metadataServiceClient) GetAssignment(ctx context.Context, req *ntb.GetAssignmentRequest) (*ntb.GetAssignmentResponse, error) {
	res, err := c.client.GetAssignment(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *metadataServiceClient) ListAssignments(ctx context.Context, req *ntb.ListAssignmentsRequest) (*ntb.ListAssignmentsResponse, error) {
	res, err := c.client.ListAssignments(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

// NewMediaServiceHandler builds an HTTP handler for the ttab.ntb.Media service from an
// implementation of the plain ntb.Media interface, and returns the path to mount it on together
// with the handler, just like NewMediaHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewMediaServiceHandler(svc ntb.Media, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewMediaHandler(&mediaServiceHandler{svc: svc}, opts...)
}

// mediaServiceHandler implements MediaHandler on top of a ntb.Media.
type mediaServiceHandler struct {
	svc ntb.Media
}

func (h *mediaServiceHandler) Search(ctx context.Context, req *connect.Request[ntb.SearchRequest]) (*connect.Response[ntb.SearchResponse], error) {
	res, err := h.svc.Search(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *mediaServiceHandler) GetItem(ctx context.Context, req *connect.Request[ntb.GetItemRequest]) (*connect.Response[ntb.GetItemResponse], error) {
	res, err := h.svc.GetItem(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *mediaServiceHandler) GetSortFields(ctx context.Context, req *connect.Request[ntb.GetSortFieldsRequest]) (*connect.Response[ntb.GetSortFieldsResponse], error) {
	res, err := h.svc.GetSortFields(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewMediaServiceClient constructs a client for the ttab.ntb.Media service that implements the
// plain ntb.Media interface, so that it is a drop-in for the Twirp clients. The options are the
// ones NewMediaClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewMediaServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ntb.Media {
	return &mediaServiceClient{
		client: NewMediaClient(httpClient, baseURL, opts...),
	}
}

// mediaServiceClient implements ntb.Media on top of a MediaClient.
type mediaServiceClient struct {
	client MediaClient
}

func (c *mediaServiceClient) Search(ctx context.Context, req *ntb.SearchRequest) (*ntb.SearchResponse, error) {
	res, err := c.client.Search(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *mediaServiceClient) GetItem(ctx context.Context, req *ntb.GetItemRequest) (*ntb.GetItemResponse, error) {
	res, err := c.client.GetItem(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *mediaServiceClient) GetSortFields(ctx context.Context, req *ntb.GetSortFieldsRequest) (*ntb.GetSortFieldsResponse, error) {
	res, err := c.client.GetSortFields(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

// NewNynorskServiceHandler builds an HTTP handler for the ttab.ntb.Nynorsk service from an
// implementation of the plain ntb.Nynorsk interface, and returns the path to mount it on together
// with the handler, just like NewNynorskHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewNynorskServiceHandler(svc ntb.Nynorsk, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewNynorskHandler(&nynorskServiceHandler{svc: svc}, opts...)
}

// nynorskServiceHandler implements NynorskHandler on top of a ntb.Nynorsk.
type nynorskServiceHandler struct {
	svc ntb.Nynorsk
}

func (h *nynorskServiceHandler) Translate(ctx context.Context, req *connect.Request[ntb.TranslateRequest]) (*connect.Response[ntb.TranslateResponse], error) {
	res, err := h.svc.Translate(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *nynorskServiceHandler) GetLanguagePrefs(ctx context.Context, req *connect.Request[ntb.GetLanguagePrefsRequest]) (*connect.Response[ntb.GetLanguagePrefsResponse], error) {
	res, err := h.svc.GetLanguagePrefs(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *nynorskServiceHandler) GetDocumentFormats(ctx context.Context, req *connect.Request[ntb.GetDocumentFormatsRequest]) (*connect.Response[ntb.GetDocumentFormatsResponse], error) {
	res, err := h.svc.GetDocumentFormats(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *nynorskServiceHandler) GetPreferenceTemplates(ctx context.Context, req *connect.Request[ntb.GetPreferenceTemplatesRequest]) (*connect.Response[ntb.GetPreferenceTemplatesResponse], error) {
	res, err := h.svc.GetPreferenceTemplates(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewNynorskServiceClient constructs a client for the ttab.ntb.Nynorsk service that implements the
// plain ntb.Nynorsk interface, so that it is a drop-in for the Twirp clients. The options are the
// ones NewNynorskClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewNynorskServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ntb.Nynorsk {
	return &nynorskServiceClient{
		client: NewNynorskClient(httpClient, baseURL, opts...),
	}
}

// nynorskServiceClient implements ntb.Nynorsk on top of a NynorskClient.
type nynorskServiceClient struct {
	client NynorskClient
}

func (c *nynorskServiceClient) Translate(ctx context.Context, req *ntb.TranslateRequest) (*ntb.TranslateResponse, error) {
	res, err := c.client.Translate(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *nynorskServiceClient) GetLanguagePrefs(ctx context.Context, req *ntb.GetLanguagePrefsRequest) (*ntb.GetLanguagePrefsResponse, error) {
	res, err := c.client.GetLanguagePrefs(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *nynorskServiceClient) GetDocumentFormats(ctx context.Context, req *ntb.GetDocumentFormatsRequest) (*ntb.GetDocumentFormatsResponse, error) {
	res, err := c.client.GetDocumentFormats(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *nynorskServiceClient) GetPreferenceTemplates(ctx context.Context, req *ntb.GetPreferenceTemplatesRequest) (*ntb.GetPreferenceTemplatesResponse, error) {
	res, err := c.client.GetPreferenceTemplates(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}
