// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: wires/service.proto

package wiresconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	wires "github.com/ttab/elephant-tt-api/wires"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RssFeedName is the fully-qualified name of the RssFeed service.
	RssFeedName = "ttab.wires.RssFeed"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RssFeedGetAllFeedsProcedure is the fully-qualified name of the RssFeed's GetAllFeeds RPC.
	RssFeedGetAllFeedsProcedure = "/ttab.wires.RssFeed/GetAllFeeds"
	// RssFeedUpdateFeedProcedure is the fully-qualified name of the RssFeed's UpdateFeed RPC.
	RssFeedUpdateFeedProcedure = "/ttab.wires.RssFeed/UpdateFeed"
	// RssFeedDeleteFeedProcedure is the fully-qualified name of the RssFeed's DeleteFeed RPC.
	RssFeedDeleteFeedProcedure = "/ttab.wires.RssFeed/DeleteFeed"
)

// RssFeedClient is a client for the ttab.wires.RssFeed service.
type RssFeedClient interface {
	GetAllFeeds(context.Context, *connect.Request[wires.GetAllFeedsRequest]) (*connect.Response[wires.GetAllFeedsResponse], error)
	UpdateFeed(context.Context, *connect.Request[wires.UpdateFeedRequest]) (*connect.Response[wires.UpdateFeedResponse], error)
	DeleteFeed(context.Context, *connect.Request[wires.DeleteFeedRequest]) (*connect.Response[wires.DeleteFeedResponse], error)
}

// NewRssFeedClient constructs a client for the ttab.wires.RssFeed service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRssFeedClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RssFeedClient {
	baseURL = strings.TrimRight(baseURL, "/")
	rssFeedMethods := wires.File_wires_service_proto.Services().ByName("RssFeed").Methods()
	return &rssFeedClient{
		getAllFeeds: connect.NewClient[wires.GetAllFeedsRequest, wires.GetAllFeedsResponse](
			httpClient,
			baseURL+RssFeedGetAllFeedsProcedure,
			connect.WithSchema(rssFeedMethods.ByName("GetAllFeeds")),
			connect.WithClientOptions(opts...),
		),
		updateFeed: connect.NewClient[wires.UpdateFeedRequest, wires.UpdateFeedResponse](
			httpClient,
			baseURL+RssFeedUpdateFeedProcedure,
			connect.WithSchema(rssFeedMethods.ByName("UpdateFeed")),
			connect.WithClientOptions(opts...),
		),
		deleteFeed: connect.NewClient[wires.DeleteFeedRequest, wires.DeleteFeedResponse](
			httpClient,
			baseURL+RssFeedDeleteFeedProcedure,
			connect.WithSchema(rssFeedMethods.ByName("DeleteFeed")),
			connect.WithClientOptions(opts...),
		),
	}
}

// rssFeedClient implements RssFeedClient.
type rssFeedClient struct {
	getAllFeeds *connect.Client[wires.GetAllFeedsRequest, wires.GetAllFeedsResponse]
	updateFeed  *connect.Client[wires.UpdateFeedRequest, wires.UpdateFeedResponse]
	deleteFeed  *connect.Client[wires.DeleteFeedRequest, wires.DeleteFeedResponse]
}

// GetAllFeeds calls ttab.wires.RssFeed.GetAllFeeds.
func (c *rssFeedClient) GetAllFeeds(ctx context.Context, req *connect.Request[wires.GetAllFeedsRequest]) (*connect.Response[wires.GetAllFeedsResponse], error) {
	return c.getAllFeeds.CallUnary(ctx, req)
}

// UpdateFeed calls ttab.wires.RssFeed.UpdateFeed.
func (c *rssFeedClient) UpdateFeed(ctx context.Context, req *connect.Request[wires.UpdateFeedRequest]) (*connect.Response[wires.UpdateFeedResponse], error) {
	return c.updateFeed.CallUnary(ctx, req)
}

// DeleteFeed calls ttab.wires.RssFeed.DeleteFeed.
func (c *rssFeedClient) DeleteFeed(ctx context.Context, req *connect.Request[wires.DeleteFeedRequest]) (*connect.Response[wires.DeleteFeedResponse], error) {
	return c.deleteFeed.CallUnary(ctx, req)
}

// RssFeedHandler is an implementation of the ttab.wires.RssFeed service.
type RssFeedHandler interface {
	GetAllFeeds(context.Context, *connect.Request[wires.GetAllFeedsRequest]) (*connect.Response[wires.GetAllFeedsResponse], error)
	UpdateFeed(context.Context, *connect.Request[wires.UpdateFeedRequest]) (*connect.Response[wires.UpdateFeedResponse], error)
	DeleteFeed(context.Context, *connect.Request[wires.DeleteFeedRequest]) (*connect.Response[wires.DeleteFeedResponse], error)
}

// NewRssFeedHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRssFeedHandler(svc RssFeedHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	rssFeedMethods := wires.File_wires_service_proto.Services().ByName("RssFeed").Methods()
	rssFeedGetAllFeedsHandler := connect.NewUnaryHandler(
		RssFeedGetAllFeedsProcedure,
		svc.GetAllFeeds,
		connect.WithSchema(rssFeedMethods.ByName("GetAllFeeds")),
		connect.WithHandlerOptions(opts...),
	)
	rssFeedUpdateFeedHandler := connect.NewUnaryHandler(
		RssFeedUpdateFeedProcedure,
		svc.UpdateFeed,
		connect.WithSchema(rssFeedMethods.ByName("UpdateFeed")),
		connect.WithHandlerOptions(opts...),
	)
	rssFeedDeleteFeedHandler := connect.NewUnaryHandler(
		RssFeedDeleteFeedProcedure,
		svc.DeleteFeed,
		connect.WithSchema(rssFeedMethods.ByName("DeleteFeed")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ttab.wires.RssFeed/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RssFeedGetAllFeedsProcedure:
			rssFeedGetAllFeedsHandler.ServeHTTP(w, r)
		case RssFeedUpdateFeedProcedure:
			rssFeedUpdateFeedHandler.ServeHTTP(w, r)
		case RssFeedDeleteFeedProcedure:
			rssFeedDeleteFeedHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRssFeedHandler returns CodeUnimplemented from all methods.
type UnimplementedRssFeedHandler struct{}

func (UnimplementedRssFeedHandler) GetAllFeeds(context.Context, *connect.Request[wires.GetAllFeedsRequest]) (*connect.Response[wires.GetAllFeedsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.wires.RssFeed.GetAllFeeds is not implemented"))
}

func (UnimplementedRssFeedHandler) UpdateFeed(context.Context, *connect.Request[wires.UpdateFeedRequest]) (*connect.Response[wires.UpdateFeedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.wires.RssFeed.UpdateFeed is not implemented"))
}

func (UnimplementedRssFeedHandler) DeleteFeed(context.Context, *connect.Request[wires.DeleteFeedRequest]) (*connect.Response[wires.DeleteFeedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.wires.RssFeed.DeleteFeed is not implemented"))
}
