// Code generated by protoc-gen-elephant-rpc. DO NOT EDIT.
//
// Source: wires/service.proto

package wiresconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	wires "github.com/ttab/elephant-tt-api/wires"
	http "net/http"
)

// NewRssFeedServiceHandler builds an HTTP handler for the ttab.wires.RssFeed service from an
// implementation of the plain wires.RssFeed interface, and returns the path to mount it on together
// with the handler, just like NewRssFeedHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewRssFeedServiceHandler(svc wires.RssFeed, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewRssFeedHandler(&rssFeedServiceHandler{svc: svc}, opts...)
}

// rssFeedServiceHandler implements RssFeedHandler on top of a wires.RssFeed.
type rssFeedServiceHandler struct {
	svc wires.RssFeed
}

func (h *rssFeedServiceHandler) GetAllFeeds(ctx context.Context, req *connect.Request[wires.GetAllFeedsRequest]) (*connect.Response[wires.GetAllFeedsResponse], error) {
	res, err := h.svc.GetAllFeeds(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *rssFeedServiceHandler) UpdateFeed(ctx context.Context, req *connect.Request[wires.UpdateFeedRequest]) (*connect.Response[wires.UpdateFeedResponse], error) {
	res, err := h.svc.UpdateFeed(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *rssFeedServiceHandler) DeleteFeed(ctx context.Context, req *connect.Request[wires.DeleteFeedRequest]) (*connect.Response[wires.DeleteFeedResponse], error) {
	res, err := h.svc.DeleteFeed(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewRssFeedServiceClient constructs a client for the ttab.wires.RssFeed service that implements
// the plain wires.RssFeed interface, so that it is a drop-in for the Twirp clients. The options are
// the ones NewRssFeedClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewRssFeedServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) wires.RssFeed {
	return &rssFeedServiceClient{
		client: NewRssFeedClient(httpClient, baseURL, opts...),
	}
}

// rssFeedServiceClient implements wires.RssFeed on top of a RssFeedClient.
type rssFeedServiceClient struct {
	client RssFeedClient
}

func (c *rssFeedServiceClient) GetAllFeeds(ctx context.Context, req *wires.GetAllFeedsRequest) (*wires.GetAllFeedsResponse, error) {
	res, err := c.client.GetAllFeeds(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *rssFeedServiceClient) UpdateFeed(ctx context.Context, req *wires.UpdateFeedRequest) (*wires.UpdateFeedResponse, error) {
	res, err := c.client.UpdateFeed(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *rssFeedServiceClient) DeleteFeed(ctx context.Context, req *wires.DeleteFeedRequest) (*wires.DeleteFeedResponse, error) {
	res, err := c.client.DeleteFeed(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}
