// Code generated by protoc-gen-elephant-rpc. DO NOT EDIT.
//
// Source: genai/service.proto

package genaiconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	genai "github.com/ttab/elephant-tt-api/genai"
	http "net/http"
)

// NewGenerateServiceHandler builds an HTTP handler for the ttab.genai.Generate service from an
// implementation of the plain genai.Generate interface, and returns the path to mount it on
// together with the handler, just like NewGenerateHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewGenerateServiceHandler(svc genai.Generate, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewGenerateHandler(&generateServiceHandler{svc: svc}, opts...)
}

// generateServiceHandler implements GenerateHandler on top of a genai.Generate.
type generateServiceHandler struct {
	svc genai.Generate
}

func (h *generateServiceHandler) DocumentFromText(ctx context.Context, req *connect.Request[genai.DocumentFromTextRequest]) (*connect.Response[genai.DocumentFromTextResponse], error) {
	res, err := h.svc.DocumentFromText(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *generateServiceHandler) LanguageFeedback(ctx context.Context, req *connect.Request[genai.LanguageFeedbackRequest]) (*connect.Response[genai.LanguageFeedbackResponse], error) {
	res, err := h.svc.LanguageFeedback(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *generateServiceHandler) Text(ctx context.Context, req *connect.Request[genai.TextRequest]) (*connect.Response[genai.TextResponse], error) {
	res, err := h.svc.Text(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *generateServiceHandler) ListJobs(ctx context.Context, req *connect.Request[genai.ListJobsRequest]) (*connect.Response[genai.ListJobsResponse], error) {
	res, err := h.svc.ListJobs(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *generateServiceHandler) WaitForJobs(ctx context.Context, req *connect.Request[genai.WaitForJobsRequest]) (*connect.Response[genai.WaitForJobsResponse], error) {
	res, err := h.svc.WaitForJobs(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *generateServiceHandler) GetResult(ctx context.Context, req *connect.Request[genai.GetResultRequest]) (*connect.Response[genai.GetResultResponse], error) {
	res, err := h.svc.GetResult(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewGenerateServiceClient constructs a client for the ttab.genai.Generate service that implements
// the plain genai.Generate interface, so that it is a drop-in for the Twirp clients. The options
// are the ones NewGenerateClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewGenerateServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) genai.Generate {
	return &generateServiceClient{
		client: NewGenerateClient(httpClient, baseURL, opts...),
	}
}

// generateServiceClient implements genai.Generate on top of a GenerateClient.
type generateServiceClient struct {
	client GenerateClient
}

func (c *generateServiceClient) DocumentFromText(ctx context.Context, req *genai.DocumentFromTextRequest) (*genai.DocumentFromTextResponse, error) {
	res, err := c.client.DocumentFromText(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *generateServiceClient) LanguageFeedback(ctx context.Context, req *genai.LanguageFeedbackRequest) (*genai.LanguageFeedbackResponse, error) {
	res, err := c.client.LanguageFeedback(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *generateServiceClient) Text(ctx context.Context, req *genai.TextRequest) (*genai.TextResponse, error) {
	res, err := c.client.Text(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *generateServiceClient) ListJobs(ctx context.Context, req *genai.ListJobsRequest) (*genai.ListJobsResponse, error) {
	res, err := c.client.ListJobs(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *generateServiceClient) WaitForJobs(ctx context.Context, req *genai.WaitForJobsRequest) (*genai.WaitForJobsResponse, error) {
	res, err := c.client.WaitForJobs(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *generateServiceClient) GetResult(ctx context.Context, req *genai.GetResultRequest) (*genai.GetResultResponse, error) {
	res, err := c.client.GetResult(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}
