// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: genai/service.proto

package genaiconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	genai "github.com/ttab/elephant-tt-api/genai"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GenerateName is the fully-qualified name of the Generate service.
	GenerateName = "ttab.genai.Generate"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GenerateDocumentFromTextProcedure is the fully-qualified name of the Generate's DocumentFromText
	// RPC.
	GenerateDocumentFromTextProcedure = "/ttab.genai.Generate/DocumentFromText"
	// GenerateLanguageFeedbackProcedure is the fully-qualified name of the Generate's LanguageFeedback
	// RPC.
	GenerateLanguageFeedbackProcedure = "/ttab.genai.Generate/LanguageFeedback"
	// GenerateTextProcedure is the fully-qualified name of the Generate's Text RPC.
	GenerateTextProcedure = "/ttab.genai.Generate/Text"
	// GenerateListJobsProcedure is the fully-qualified name of the Generate's ListJobs RPC.
	GenerateListJobsProcedure = "/ttab.genai.Generate/ListJobs"
	// GenerateWaitForJobsProcedure is the fully-qualified name of the Generate's WaitForJobs RPC.
	GenerateWaitForJobsProcedure = "/ttab.genai.Generate/WaitForJobs"
	// GenerateGetResultProcedure is the fully-qualified name of the Generate's GetResult RPC.
	GenerateGetResultProcedure = "/ttab.genai.Generate/GetResult"
)

// GenerateClient is a client for the ttab.genai.Generate service.
type GenerateClient interface {
	// DocumentFromText creates a document from an input text.
	DocumentFromText(context.Context, *connect.Request[genai.DocumentFromTextRequest]) (*connect.Response[genai.DocumentFromTextResponse], error)
	// LanguageFeedback gives feedback on a text.
	LanguageFeedback(context.Context, *connect.Request[genai.LanguageFeedbackRequest]) (*connect.Response[genai.LanguageFeedbackResponse], error)
	// Text generates text from a input.
	Text(context.Context, *connect.Request[genai.TextRequest]) (*connect.Response[genai.TextResponse], error)
	// ListJobs that have been submitted.
	ListJobs(context.Context, *connect.Request[genai.ListJobsRequest]) (*connect.Response[genai.ListJobsResponse], error)
	// WaitForJobs is used to wait for status updates for a set of jobs.
	WaitForJobs(context.Context, *connect.Request[genai.WaitForJobsRequest]) (*connect.Response[genai.WaitForJobsResponse], error)
	// GetResult returns the result for a job.
	GetResult(context.Context, *connect.Request[genai.GetResultRequest]) (*connect.Response[genai.GetResultResponse], error)
}

// NewGenerateClient constructs a client for the ttab.genai.Generate service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGenerateClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GenerateClient {
	baseURL = strings.TrimRight(baseURL, "/")
	generateMethods := genai.File_genai_service_proto.Services().ByName("Generate").Methods()
	return &generateClient{
		documentFromText: connect.NewClient[genai.DocumentFromTextRequest, genai.DocumentFromTextResponse](
			httpClient,
			baseURL+GenerateDocumentFromTextProcedure,
			connect.WithSchema(generateMethods.ByName("DocumentFromText")),
			connect.WithClientOptions(opts...),
		),
		languageFeedback: connect.NewClient[genai.LanguageFeedbackRequest, genai.LanguageFeedbackResponse](
			httpClient,
			baseURL+GenerateLanguageFeedbackProcedure,
			connect.WithSchema(generateMethods.ByName("LanguageFeedback")),
			connect.WithClientOptions(opts...),
		),
		text: connect.NewClient[genai.TextRequest, genai.TextResponse](
			httpClient,
			baseURL+GenerateTextProcedure,
			connect.WithSchema(generateMethods.ByName("Text")),
			connect.WithClientOptions(opts...),
		),
		listJobs: connect.NewClient[genai.ListJobsRequest, genai.ListJobsResponse](
			httpClient,
			baseURL+GenerateListJobsProcedure,
			connect.WithSchema(generateMethods.ByName("ListJobs")),
			connect.WithClientOptions(opts...),
		),
		waitForJobs: connect.NewClient[genai.WaitForJobsRequest, genai.WaitForJobsResponse](
			httpClient,
			baseURL+GenerateWaitForJobsProcedure,
			connect.WithSchema(generateMethods.ByName("WaitForJobs")),
			connect.WithClientOptions(opts...),
		),
		getResult: connect.NewClient[genai.GetResultRequest, genai.GetResultResponse](
			httpClient,
			baseURL+GenerateGetResultProcedure,
			connect.WithSchema(generateMethods.ByName("GetResult")),
			connect.WithClientOptions(opts...),
		),
	}
}

// generateClient implements GenerateClient.
type generateClient struct {
	documentFromText *connect.Client[genai.DocumentFromTextRequest, genai.DocumentFromTextResponse]
	languageFeedback *connect.Client[genai.LanguageFeedbackRequest, genai.LanguageFeedbackResponse]
	text             *connect.Client[genai.TextRequest, genai.TextResponse]
	listJobs         *connect.Client[genai.ListJobsRequest, genai.ListJobsResponse]
	waitForJobs      *connect.Client[genai.WaitForJobsRequest, genai.WaitForJobsResponse]
	getResult        *connect.Client[genai.GetResultRequest, genai.GetResultResponse]
}

// DocumentFromText calls ttab.genai.Generate.DocumentFromText.
func (c *generateClient) DocumentFromText(ctx context.Context, req *connect.Request[genai.DocumentFromTextRequest]) (*connect.Response[genai.DocumentFromTextResponse], error) {
	return c.documentFromText.CallUnary(ctx, req)
}

// LanguageFeedback calls ttab.genai.Generate.LanguageFeedback.
func (c *generateClient) LanguageFeedback(ctx context.Context, req *connect.Request[genai.LanguageFeedbackRequest]) (*connect.Response[genai.LanguageFeedbackResponse], error) {
	return c.languageFeedback.CallUnary(ctx, req)
}

// Text calls ttab.genai.Generate.Text.
func (c *generateClient) Text(ctx context.Context, req *connect.Request[genai.TextRequest]) (*connect.Response[genai.TextResponse], error) {
	return c.text.CallUnary(ctx, req)
}

// ListJobs calls ttab.genai.Generate.ListJobs.
func (c *generateClient) ListJobs(ctx context.Context, req *connect.Request[genai.ListJobsRequest]) (*connect.Response[genai.ListJobsResponse], error) {
	return c.listJobs.CallUnary(ctx, req)
}

// WaitForJobs calls ttab.genai.Generate.WaitForJobs.
func (c *generateClient) WaitForJobs(ctx context.Context, req *connect.Request[genai.WaitForJobsRequest]) (*connect.Response[genai.WaitForJobsResponse], error) {
	return c.waitForJobs.CallUnary(ctx, req)
}

// GetResult calls ttab.genai.Generate.GetResult.
func (c *generateClient) GetResult(ctx context.Context, req *connect.Request[genai.GetResultRequest]) (*connect.Response[genai.GetResultResponse], error) {
	return c.getResult.CallUnary(ctx, req)
}

// GenerateHandler is an implementation of the ttab.genai.Generate service.
type GenerateHandler interface {
	// DocumentFromText creates a document from an input text.
	DocumentFromText(context.Context, *connect.Request[genai.DocumentFromTextRequest]) (*connect.Response[genai.DocumentFromTextResponse], error)
	// LanguageFeedback gives feedback on a text.
	LanguageFeedback(context.Context, *connect.Request[genai.LanguageFeedbackRequest]) (*connect.Response[genai.LanguageFeedbackResponse], error)
	// Text generates text from a input.
	Text(context.Context, *connect.Request[genai.TextRequest]) (*connect.Response[genai.TextResponse], error)
	// ListJobs that have been submitted.
	ListJobs(context.Context, *connect.Request[genai.ListJobsRequest]) (*connect.Response[genai.ListJobsResponse], error)
	// WaitForJobs is used to wait for status updates for a set of jobs.
	WaitForJobs(context.Context, *connect.Request[genai.WaitForJobsRequest]) (*connect.Response[genai.WaitForJobsResponse], error)
	// GetResult returns the result for a job.
	GetResult(context.Context, *connect.Request[genai.GetResultRequest]) (*connect.Response[genai.GetResultResponse], error)
}

// NewGenerateHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGenerateHandler(svc GenerateHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	generateMethods := genai.File_genai_service_proto.Services().ByName("Generate").Methods()
	generateDocumentFromTextHandler := connect.NewUnaryHandler(
		GenerateDocumentFromTextProcedure,
		svc.DocumentFromText,
		connect.WithSchema(generateMethods.ByName("DocumentFromText")),
		connect.WithHandlerOptions(opts...),
	)
	generateLanguageFeedbackHandler := connect.NewUnaryHandler(
		GenerateLanguageFeedbackProcedure,
		svc.LanguageFeedback,
		connect.WithSchema(generateMethods.ByName("LanguageFeedback")),
		connect.WithHandlerOptions(opts...),
	)
	generateTextHandler := connect.NewUnaryHandler(
		GenerateTextProcedure,
		svc.Text,
		connect.WithSchema(generateMethods.ByName("Text")),
		connect.WithHandlerOptions(opts...),
	)
	generateListJobsHandler := connect.NewUnaryHandler(
		GenerateListJobsProcedure,
		svc.ListJobs,
		connect.WithSchema(generateMethods.ByName("ListJobs")),
		connect.WithHandlerOptions(opts...),
	)
	generateWaitForJobsHandler := connect.NewUnaryHandler(
		GenerateWaitForJobsProcedure,
		svc.WaitForJobs,
		connect.WithSchema(generateMethods.ByName("WaitForJobs")),
		connect.WithHandlerOptions(opts...),
	)
	generateGetResultHandler := connect.NewUnaryHandler(
		GenerateGetResultProcedure,
		svc.GetResult,
		connect.WithSchema(generateMethods.ByName("GetResult")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ttab.genai.Generate/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GenerateDocumentFromTextProcedure:
			generateDocumentFromTextHandler.ServeHTTP(w, r)
		case GenerateLanguageFeedbackProcedure:
			generateLanguageFeedbackHandler.ServeHTTP(w, r)
		case GenerateTextProcedure:
			generateTextHandler.ServeHTTP(w, r)
		case GenerateListJobsProcedure:
			generateListJobsHandler.ServeHTTP(w, r)
		case GenerateWaitForJobsProcedure:
			generateWaitForJobsHandler.ServeHTTP(w, r)
		case GenerateGetResultProcedure:
			generateGetResultHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGenerateHandler returns CodeUnimplemented from all methods.
type UnimplementedGenerateHandler struct{}

func (UnimplementedGenerateHandler) DocumentFromText(context.Context, *connect.Request[genai.DocumentFromTextRequest]) (*connect.Response[genai.DocumentFromTextResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.genai.Generate.DocumentFromText is not implemented"))
}

func (UnimplementedGenerateHandler) LanguageFeedback(context.Context, *connect.Request[genai.LanguageFeedbackRequest]) (*connect.Response[genai.LanguageFeedbackResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.genai.Generate.LanguageFeedback is not implemented"))
}

func (UnimplementedGenerateHandler) Text(context.Context, *connect.Request[genai.TextRequest]) (*connect.Response[genai.TextResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.genai.Generate.Text is not implemented"))
}

func (UnimplementedGenerateHandler) ListJobs(context.Context, *connect.Request[genai.ListJobsRequest]) (*connect.Response[genai.ListJobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.genai.Generate.ListJobs is not implemented"))
}

func (UnimplementedGenerateHandler) WaitForJobs(context.Context, *connect.Request[genai.WaitForJobsRequest]) (*connect.Response[genai.WaitForJobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.genai.Generate.WaitForJobs is not implemented"))
}

func (UnimplementedGenerateHandler) GetResult(context.Context, *connect.Request[genai.GetResultRequest]) (*connect.Response[genai.GetResultResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.genai.Generate.GetResult is not implemented"))
}
