// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: everysport/service.proto

package everysportconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	everysport "github.com/ttab/elephant-tt-api/everysport"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ManageName is the fully-qualified name of the Manage service.
	ManageName = "ttab.everysport.Manage"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ManageManualImportProcedure is the fully-qualified name of the Manage's ManualImport RPC.
	ManageManualImportProcedure = "/ttab.everysport.Manage/ManualImport"
	// ManageListSportsProcedure is the fully-qualified name of the Manage's ListSports RPC.
	ManageListSportsProcedure = "/ttab.everysport.Manage/ListSports"
	// ManageListCategoriesProcedure is the fully-qualified name of the Manage's ListCategories RPC.
	ManageListCategoriesProcedure = "/ttab.everysport.Manage/ListCategories"
	// ManageListCompetitionsProcedure is the fully-qualified name of the Manage's ListCompetitions RPC.
	ManageListCompetitionsProcedure = "/ttab.everysport.Manage/ListCompetitions"
	// ManageGetSportProcedure is the fully-qualified name of the Manage's GetSport RPC.
	ManageGetSportProcedure = "/ttab.everysport.Manage/GetSport"
	// ManageGetCompetitionProcedure is the fully-qualified name of the Manage's GetCompetition RPC.
	ManageGetCompetitionProcedure = "/ttab.everysport.Manage/GetCompetition"
	// ManageGetCategoryProcedure is the fully-qualified name of the Manage's GetCategory RPC.
	ManageGetCategoryProcedure = "/ttab.everysport.Manage/GetCategory"
	// ManageUpdateSportProcedure is the fully-qualified name of the Manage's UpdateSport RPC.
	ManageUpdateSportProcedure = "/ttab.everysport.Manage/UpdateSport"
	// ManageUpdateCompetitionProcedure is the fully-qualified name of the Manage's UpdateCompetition
	// RPC.
	ManageUpdateCompetitionProcedure = "/ttab.everysport.Manage/UpdateCompetition"
	// ManageUpdateCategoryProcedure is the fully-qualified name of the Manage's UpdateCategory RPC.
	ManageUpdateCategoryProcedure = "/ttab.everysport.Manage/UpdateCategory"
	// ManageApplyDefaultsProcedure is the fully-qualified name of the Manage's ApplyDefaults RPC.
	ManageApplyDefaultsProcedure = "/ttab.everysport.Manage/ApplyDefaults"
	// ManageExportConfigProcedure is the fully-qualified name of the Manage's ExportConfig RPC.
	ManageExportConfigProcedure = "/ttab.everysport.Manage/ExportConfig"
	// ManageListPendingImportsProcedure is the fully-qualified name of the Manage's ListPendingImports
	// RPC.
	ManageListPendingImportsProcedure = "/ttab.everysport.Manage/ListPendingImports"
	// ManageReviewCompetitionsProcedure is the fully-qualified name of the Manage's ReviewCompetitions
	// RPC.
	ManageReviewCompetitionsProcedure = "/ttab.everysport.Manage/ReviewCompetitions"
)

// ManageClient is a client for the ttab.everysport.Manage service.
type ManageClient interface {
	// ManualImport re-imports calendar events based on a search query.
	ManualImport(context.Context, *connect.Request[everysport.ManualImportRequest]) (*connect.Response[everysport.ManualImportResponse], error)
	// ListSports lists the sports in the import configuration.
	ListSports(context.Context, *connect.Request[everysport.ListSportsRequest]) (*connect.Response[everysport.ListSportsResponse], error)
	// ListCategories lists competition categories, for one sport or for all of
	// them. A category imports nothing of its own, it carries the defaults that
	// new competitions under it are created with.
	ListCategories(context.Context, *connect.Request[everysport.ListCategoriesRequest]) (*connect.Response[everysport.ListCategoriesResponse], error)
	// ListCompetitions lists competitions in the import configuration.
	ListCompetitions(context.Context, *connect.Request[everysport.ListCompetitionsRequest]) (*connect.Response[everysport.ListCompetitionsResponse], error)
	// GetSport returns a single sport configuration.
	GetSport(context.Context, *connect.Request[everysport.GetSportRequest]) (*connect.Response[everysport.GetSportResponse], error)
	// GetCompetition returns a single competition configuration.
	GetCompetition(context.Context, *connect.Request[everysport.GetCompetitionRequest]) (*connect.Response[everysport.GetCompetitionResponse], error)
	// GetCategory returns a single competition category.
	GetCategory(context.Context, *connect.Request[everysport.GetCategoryRequest]) (*connect.Response[everysport.GetCategoryResponse], error)
	// UpdateSport replaces the editable settings of a sport.
	UpdateSport(context.Context, *connect.Request[everysport.UpdateSportRequest]) (*connect.Response[everysport.UpdateSportResponse], error)
	// UpdateCompetition replaces the editable settings of a competition.
	UpdateCompetition(context.Context, *connect.Request[everysport.UpdateCompetitionRequest]) (*connect.Response[everysport.UpdateCompetitionResponse], error)
	// UpdateCategory replaces the comment and the import defaults of a
	// competition category.
	UpdateCategory(context.Context, *connect.Request[everysport.UpdateCategoryRequest]) (*connect.Response[everysport.UpdateCategoryResponse], error)
	// ApplyDefaults writes the defaults of a sport or a category to the rows
	// below it. With dry_run set it reports what would change and writes
	// nothing, which is what the preview shown before an apply is built from.
	ApplyDefaults(context.Context, *connect.Request[everysport.ApplyDefaultsRequest]) (*connect.Response[everysport.ApplyDefaultsResponse], error)
	// ExportConfig returns the full import configuration as CSV.
	ExportConfig(context.Context, *connect.Request[everysport.ExportConfigRequest]) (*connect.Response[everysport.ExportConfigResponse], error)
	// ListPendingImports lists the competitions that have calendar entries the
	// service skipped, with the date range those entries fall in.
	ListPendingImports(context.Context, *connect.Request[everysport.ListPendingImportsRequest]) (*connect.Response[everysport.ListPendingImportsResponse], error)
	// ReviewCompetitions decides a batch of competitions at once, which is what
	// working through the review queue is.
	ReviewCompetitions(context.Context, *connect.Request[everysport.ReviewCompetitionsRequest]) (*connect.Response[everysport.ReviewCompetitionsResponse], error)
}

// NewManageClient constructs a client for the ttab.everysport.Manage service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewManageClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ManageClient {
	baseURL = strings.TrimRight(baseURL, "/")
	manageMethods := everysport.File_everysport_service_proto.Services().ByName("Manage").Methods()
	return &manageClient{
		manualImport: connect.NewClient[everysport.ManualImportRequest, everysport.ManualImportResponse](
			httpClient,
			baseURL+ManageManualImportProcedure,
			connect.WithSchema(manageMethods.ByName("ManualImport")),
			connect.WithClientOptions(opts...),
		),
		listSports: connect.NewClient[everysport.ListSportsRequest, everysport.ListSportsResponse](
			httpClient,
			baseURL+ManageListSportsProcedure,
			connect.WithSchema(manageMethods.ByName("ListSports")),
			connect.WithClientOptions(opts...),
		),
		listCategories: connect.NewClient[everysport.ListCategoriesRequest, everysport.ListCategoriesResponse](
			httpClient,
			baseURL+ManageListCategoriesProcedure,
			connect.WithSchema(manageMethods.ByName("ListCategories")),
			connect.WithClientOptions(opts...),
		),
		listCompetitions: connect.NewClient[everysport.ListCompetitionsRequest, everysport.ListCompetitionsResponse](
			httpClient,
			baseURL+ManageListCompetitionsProcedure,
			connect.WithSchema(manageMethods.ByName("ListCompetitions")),
			connect.WithClientOptions(opts...),
		),
		getSport: connect.NewClient[everysport.GetSportRequest, everysport.GetSportResponse](
			httpClient,
			baseURL+ManageGetSportProcedure,
			connect.WithSchema(manageMethods.ByName("GetSport")),
			connect.WithClientOptions(opts...),
		),
		getCompetition: connect.NewClient[everysport.GetCompetitionRequest, everysport.GetCompetitionResponse](
			httpClient,
			baseURL+ManageGetCompetitionProcedure,
			connect.WithSchema(manageMethods.ByName("GetCompetition")),
			connect.WithClientOptions(opts...),
		),
		getCategory: connect.NewClient[everysport.GetCategoryRequest, everysport.GetCategoryResponse](
			httpClient,
			baseURL+ManageGetCategoryProcedure,
			connect.WithSchema(manageMethods.ByName("GetCategory")),
			connect.WithClientOptions(opts...),
		),
		updateSport: connect.NewClient[everysport.UpdateSportRequest, everysport.UpdateSportResponse](
			httpClient,
			baseURL+ManageUpdateSportProcedure,
			connect.WithSchema(manageMethods.ByName("UpdateSport")),
			connect.WithClientOptions(opts...),
		),
		updateCompetition: connect.NewClient[everysport.UpdateCompetitionRequest, everysport.UpdateCompetitionResponse](
			httpClient,
			baseURL+ManageUpdateCompetitionProcedure,
			connect.WithSchema(manageMethods.ByName("UpdateCompetition")),
			connect.WithClientOptions(opts...),
		),
		updateCategory: connect.NewClient[everysport.UpdateCategoryRequest, everysport.UpdateCategoryResponse](
			httpClient,
			baseURL+ManageUpdateCategoryProcedure,
			connect.WithSchema(manageMethods.ByName("UpdateCategory")),
			connect.WithClientOptions(opts...),
		),
		applyDefaults: connect.NewClient[everysport.ApplyDefaultsRequest, everysport.ApplyDefaultsResponse](
			httpClient,
			baseURL+ManageApplyDefaultsProcedure,
			connect.WithSchema(manageMethods.ByName("ApplyDefaults")),
			connect.WithClientOptions(opts...),
		),
		exportConfig: connect.NewClient[everysport.ExportConfigRequest, everysport.ExportConfigResponse](
			httpClient,
			baseURL+ManageExportConfigProcedure,
			connect.WithSchema(manageMethods.ByName("ExportConfig")),
			connect.WithClientOptions(opts...),
		),
		listPendingImports: connect.NewClient[everysport.ListPendingImportsRequest, everysport.ListPendingImportsResponse](
			httpClient,
			baseURL+ManageListPendingImportsProcedure,
			connect.WithSchema(manageMethods.ByName("ListPendingImports")),
			connect.WithClientOptions(opts...),
		),
		reviewCompetitions: connect.NewClient[everysport.ReviewCompetitionsRequest, everysport.ReviewCompetitionsResponse](
			httpClient,
			baseURL+ManageReviewCompetitionsProcedure,
			connect.WithSchema(manageMethods.ByName("ReviewCompetitions")),
			connect.WithClientOptions(opts...),
		),
	}
}

// manageClient implements ManageClient.
type manageClient struct {
	manualImport       *connect.Client[everysport.ManualImportRequest, everysport.ManualImportResponse]
	listSports         *connect.Client[everysport.ListSportsRequest, everysport.ListSportsResponse]
	listCategories     *connect.Client[everysport.ListCategoriesRequest, everysport.ListCategoriesResponse]
	listCompetitions   *connect.Client[everysport.ListCompetitionsRequest, everysport.ListCompetitionsResponse]
	getSport           *connect.Client[everysport.GetSportRequest, everysport.GetSportResponse]
	getCompetition     *connect.Client[everysport.GetCompetitionRequest, everysport.GetCompetitionResponse]
	getCategory        *connect.Client[everysport.GetCategoryRequest, everysport.GetCategoryResponse]
	updateSport        *connect.Client[everysport.UpdateSportRequest, everysport.UpdateSportResponse]
	updateCompetition  *connect.Client[everysport.UpdateCompetitionRequest, everysport.UpdateCompetitionResponse]
	updateCategory     *connect.Client[everysport.UpdateCategoryRequest, everysport.UpdateCategoryResponse]
	applyDefaults      *connect.Client[everysport.ApplyDefaultsRequest, everysport.ApplyDefaultsResponse]
	exportConfig       *connect.Client[everysport.ExportConfigRequest, everysport.ExportConfigResponse]
	listPendingImports *connect.Client[everysport.ListPendingImportsRequest, everysport.ListPendingImportsResponse]
	reviewCompetitions *connect.Client[everysport.ReviewCompetitionsRequest, everysport.ReviewCompetitionsResponse]
}

// ManualImport calls ttab.everysport.Manage.ManualImport.
func (c *manageClient) ManualImport(ctx context.Context, req *connect.Request[everysport.ManualImportRequest]) (*connect.Response[everysport.ManualImportResponse], error) {
	return c.manualImport.CallUnary(ctx, req)
}

// ListSports calls ttab.everysport.Manage.ListSports.
func (c *manageClient) ListSports(ctx context.Context, req *connect.Request[everysport.ListSportsRequest]) (*connect.Response[everysport.ListSportsResponse], error) {
	return c.listSports.CallUnary(ctx, req)
}

// ListCategories calls ttab.everysport.Manage.ListCategories.
func (c *manageClient) ListCategories(ctx context.Context, req *connect.Request[everysport.ListCategoriesRequest]) (*connect.Response[everysport.ListCategoriesResponse], error) {
	return c.listCategories.CallUnary(ctx, req)
}

// ListCompetitions calls ttab.everysport.Manage.ListCompetitions.
func (c *manageClient) ListCompetitions(ctx context.Context, req *connect.Request[everysport.ListCompetitionsRequest]) (*connect.Response[everysport.ListCompetitionsResponse], error) {
	return c.listCompetitions.CallUnary(ctx, req)
}

// GetSport calls ttab.everysport.Manage.GetSport.
func (c *manageClient) GetSport(ctx context.Context, req *connect.Request[everysport.GetSportRequest]) (*connect.Response[everysport.GetSportResponse], error) {
	return c.getSport.CallUnary(ctx, req)
}

// GetCompetition calls ttab.everysport.Manage.GetCompetition.
func (c *manageClient) GetCompetition(ctx context.Context, req *connect.Request[everysport.GetCompetitionRequest]) (*connect.Response[everysport.GetCompetitionResponse], error) {
	return c.getCompetition.CallUnary(ctx, req)
}

// GetCategory calls ttab.everysport.Manage.GetCategory.
func (c *manageClient) GetCategory(ctx context.Context, req *connect.Request[everysport.GetCategoryRequest]) (*connect.Response[everysport.GetCategoryResponse], error) {
	return c.getCategory.CallUnary(ctx, req)
}

// UpdateSport calls ttab.everysport.Manage.UpdateSport.
func (c *manageClient) UpdateSport(ctx context.Context, req *connect.Request[everysport.UpdateSportRequest]) (*connect.Response[everysport.UpdateSportResponse], error) {
	return c.updateSport.CallUnary(ctx, req)
}

// UpdateCompetition calls ttab.everysport.Manage.UpdateCompetition.
func (c *manageClient) UpdateCompetition(ctx context.Context, req *connect.Request[everysport.UpdateCompetitionRequest]) (*connect.Response[everysport.UpdateCompetitionResponse], error) {
	return c.updateCompetition.CallUnary(ctx, req)
}

// UpdateCategory calls ttab.everysport.Manage.UpdateCategory.
func (c *manageClient) UpdateCategory(ctx context.Context, req *connect.Request[everysport.UpdateCategoryRequest]) (*connect.Response[everysport.UpdateCategoryResponse], error) {
	return c.updateCategory.CallUnary(ctx, req)
}

// ApplyDefaults calls ttab.everysport.Manage.ApplyDefaults.
func (c *manageClient) ApplyDefaults(ctx context.Context, req *connect.Request[everysport.ApplyDefaultsRequest]) (*connect.Response[everysport.ApplyDefaultsResponse], error) {
	return c.applyDefaults.CallUnary(ctx, req)
}

// ExportConfig calls ttab.everysport.Manage.ExportConfig.
func (c *manageClient) ExportConfig(ctx context.Context, req *connect.Request[everysport.ExportConfigRequest]) (*connect.Response[everysport.ExportConfigResponse], error) {
	return c.exportConfig.CallUnary(ctx, req)
}

// ListPendingImports calls ttab.everysport.Manage.ListPendingImports.
func (c *manageClient) ListPendingImports(ctx context.Context, req *connect.Request[everysport.ListPendingImportsRequest]) (*connect.Response[everysport.ListPendingImportsResponse], error) {
	return c.listPendingImports.CallUnary(ctx, req)
}

// ReviewCompetitions calls ttab.everysport.Manage.ReviewCompetitions.
func (c *manageClient) ReviewCompetitions(ctx context.Context, req *connect.Request[everysport.ReviewCompetitionsRequest]) (*connect.Response[everysport.ReviewCompetitionsResponse], error) {
	return c.reviewCompetitions.CallUnary(ctx, req)
}

// ManageHandler is an implementation of the ttab.everysport.Manage service.
type ManageHandler interface {
	// ManualImport re-imports calendar events based on a search query.
	ManualImport(context.Context, *connect.Request[everysport.ManualImportRequest]) (*connect.Response[everysport.ManualImportResponse], error)
	// ListSports lists the sports in the import configuration.
	ListSports(context.Context, *connect.Request[everysport.ListSportsRequest]) (*connect.Response[everysport.ListSportsResponse], error)
	// ListCategories lists competition categories, for one sport or for all of
	// them. A category imports nothing of its own, it carries the defaults that
	// new competitions under it are created with.
	ListCategories(context.Context, *connect.Request[everysport.ListCategoriesRequest]) (*connect.Response[everysport.ListCategoriesResponse], error)
	// ListCompetitions lists competitions in the import configuration.
	ListCompetitions(context.Context, *connect.Request[everysport.ListCompetitionsRequest]) (*connect.Response[everysport.ListCompetitionsResponse], error)
	// GetSport returns a single sport configuration.
	GetSport(context.Context, *connect.Request[everysport.GetSportRequest]) (*connect.Response[everysport.GetSportResponse], error)
	// GetCompetition returns a single competition configuration.
	GetCompetition(context.Context, *connect.Request[everysport.GetCompetitionRequest]) (*connect.Response[everysport.GetCompetitionResponse], error)
	// GetCategory returns a single competition category.
	GetCategory(context.Context, *connect.Request[everysport.GetCategoryRequest]) (*connect.Response[everysport.GetCategoryResponse], error)
	// UpdateSport replaces the editable settings of a sport.
	UpdateSport(context.Context, *connect.Request[everysport.UpdateSportRequest]) (*connect.Response[everysport.UpdateSportResponse], error)
	// UpdateCompetition replaces the editable settings of a competition.
	UpdateCompetition(context.Context, *connect.Request[everysport.UpdateCompetitionRequest]) (*connect.Response[everysport.UpdateCompetitionResponse], error)
	// UpdateCategory replaces the comment and the import defaults of a
	// competition category.
	UpdateCategory(context.Context, *connect.Request[everysport.UpdateCategoryRequest]) (*connect.Response[everysport.UpdateCategoryResponse], error)
	// ApplyDefaults writes the defaults of a sport or a category to the rows
	// below it. With dry_run set it reports what would change and writes
	// nothing, which is what the preview shown before an apply is built from.
	ApplyDefaults(context.Context, *connect.Request[everysport.ApplyDefaultsRequest]) (*connect.Response[everysport.ApplyDefaultsResponse], error)
	// ExportConfig returns the full import configuration as CSV.
	ExportConfig(context.Context, *connect.Request[everysport.ExportConfigRequest]) (*connect.Response[everysport.ExportConfigResponse], error)
	// ListPendingImports lists the competitions that have calendar entries the
	// service skipped, with the date range those entries fall in.
	ListPendingImports(context.Context, *connect.Request[everysport.ListPendingImportsRequest]) (*connect.Response[everysport.ListPendingImportsResponse], error)
	// ReviewCompetitions decides a batch of competitions at once, which is what
	// working through the review queue is.
	ReviewCompetitions(context.Context, *connect.Request[everysport.ReviewCompetitionsRequest]) (*connect.Response[everysport.ReviewCompetitionsResponse], error)
}

// NewManageHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewManageHandler(svc ManageHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	manageMethods := everysport.File_everysport_service_proto.Services().ByName("Manage").Methods()
	manageManualImportHandler := connect.NewUnaryHandler(
		ManageManualImportProcedure,
		svc.ManualImport,
		connect.WithSchema(manageMethods.ByName("ManualImport")),
		connect.WithHandlerOptions(opts...),
	)
	manageListSportsHandler := connect.NewUnaryHandler(
		ManageListSportsProcedure,
		svc.ListSports,
		connect.WithSchema(manageMethods.ByName("ListSports")),
		connect.WithHandlerOptions(opts...),
	)
	manageListCategoriesHandler := connect.NewUnaryHandler(
		ManageListCategoriesProcedure,
		svc.ListCategories,
		connect.WithSchema(manageMethods.ByName("ListCategories")),
		connect.WithHandlerOptions(opts...),
	)
	manageListCompetitionsHandler := connect.NewUnaryHandler(
		ManageListCompetitionsProcedure,
		svc.ListCompetitions,
		connect.WithSchema(manageMethods.ByName("ListCompetitions")),
		connect.WithHandlerOptions(opts...),
	)
	manageGetSportHandler := connect.NewUnaryHandler(
		ManageGetSportProcedure,
		svc.GetSport,
		connect.WithSchema(manageMethods.ByName("GetSport")),
		connect.WithHandlerOptions(opts...),
	)
	manageGetCompetitionHandler := connect.NewUnaryHandler(
		ManageGetCompetitionProcedure,
		svc.GetCompetition,
		connect.WithSchema(manageMethods.ByName("GetCompetition")),
		connect.WithHandlerOptions(opts...),
	)
	manageGetCategoryHandler := connect.NewUnaryHandler(
		ManageGetCategoryProcedure,
		svc.GetCategory,
		connect.WithSchema(manageMethods.ByName("GetCategory")),
		connect.WithHandlerOptions(opts...),
	)
	manageUpdateSportHandler := connect.NewUnaryHandler(
		ManageUpdateSportProcedure,
		svc.UpdateSport,
		connect.WithSchema(manageMethods.ByName("UpdateSport")),
		connect.WithHandlerOptions(opts...),
	)
	manageUpdateCompetitionHandler := connect.NewUnaryHandler(
		ManageUpdateCompetitionProcedure,
		svc.UpdateCompetition,
		connect.WithSchema(manageMethods.ByName("UpdateCompetition")),
		connect.WithHandlerOptions(opts...),
	)
	manageUpdateCategoryHandler := connect.NewUnaryHandler(
		ManageUpdateCategoryProcedure,
		svc.UpdateCategory,
		connect.WithSchema(manageMethods.ByName("UpdateCategory")),
		connect.WithHandlerOptions(opts...),
	)
	manageApplyDefaultsHandler := connect.NewUnaryHandler(
		ManageApplyDefaultsProcedure,
		svc.ApplyDefaults,
		connect.WithSchema(manageMethods.ByName("ApplyDefaults")),
		connect.WithHandlerOptions(opts...),
	)
	manageExportConfigHandler := connect.NewUnaryHandler(
		ManageExportConfigProcedure,
		svc.ExportConfig,
		connect.WithSchema(manageMethods.ByName("ExportConfig")),
		connect.WithHandlerOptions(opts...),
	)
	manageListPendingImportsHandler := connect.NewUnaryHandler(
		ManageListPendingImportsProcedure,
		svc.ListPendingImports,
		connect.WithSchema(manageMethods.ByName("ListPendingImports")),
		connect.WithHandlerOptions(opts...),
	)
	manageReviewCompetitionsHandler := connect.NewUnaryHandler(
		ManageReviewCompetitionsProcedure,
		svc.ReviewCompetitions,
		connect.WithSchema(manageMethods.ByName("ReviewCompetitions")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ttab.everysport.Manage/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ManageManualImportProcedure:
			manageManualImportHandler.ServeHTTP(w, r)
		case ManageListSportsProcedure:
			manageListSportsHandler.ServeHTTP(w, r)
		case ManageListCategoriesProcedure:
			manageListCategoriesHandler.ServeHTTP(w, r)
		case ManageListCompetitionsProcedure:
			manageListCompetitionsHandler.ServeHTTP(w, r)
		case ManageGetSportProcedure:
			manageGetSportHandler.ServeHTTP(w, r)
		case ManageGetCompetitionProcedure:
			manageGetCompetitionHandler.ServeHTTP(w, r)
		case ManageGetCategoryProcedure:
			manageGetCategoryHandler.ServeHTTP(w, r)
		case ManageUpdateSportProcedure:
			manageUpdateSportHandler.ServeHTTP(w, r)
		case ManageUpdateCompetitionProcedure:
			manageUpdateCompetitionHandler.ServeHTTP(w, r)
		case ManageUpdateCategoryProcedure:
			manageUpdateCategoryHandler.ServeHTTP(w, r)
		case ManageApplyDefaultsProcedure:
			manageApplyDefaultsHandler.ServeHTTP(w, r)
		case ManageExportConfigProcedure:
			manageExportConfigHandler.ServeHTTP(w, r)
		case ManageListPendingImportsProcedure:
			manageListPendingImportsHandler.ServeHTTP(w, r)
		case ManageReviewCompetitionsProcedure:
			manageReviewCompetitionsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedManageHandler returns CodeUnimplemented from all methods.
type UnimplementedManageHandler struct{}

func (UnimplementedManageHandler) ManualImport(context.Context, *connect.Request[everysport.ManualImportRequest]) (*connect.Response[everysport.ManualImportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.everysport.Manage.ManualImport is not implemented"))
}

func (UnimplementedManageHandler) ListSports(context.Context, *connect.Request[everysport.ListSportsRequest]) (*connect.Response[everysport.ListSportsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.everysport.Manage.ListSports is not implemented"))
}

func (UnimplementedManageHandler) ListCategories(context.Context, *connect.Request[everysport.ListCategoriesRequest]) (*connect.Response[everysport.ListCategoriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.everysport.Manage.ListCategories is not implemented"))
}

func (UnimplementedManageHandler) ListCompetitions(context.Context, *connect.Request[everysport.ListCompetitionsRequest]) (*connect.Response[everysport.ListCompetitionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.everysport.Manage.ListCompetitions is not implemented"))
}

func (UnimplementedManageHandler) GetSport(context.Context, *connect.Request[everysport.GetSportRequest]) (*connect.Response[everysport.GetSportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.everysport.Manage.GetSport is not implemented"))
}

func (UnimplementedManageHandler) GetCompetition(context.Context, *connect.Request[everysport.GetCompetitionRequest]) (*connect.Response[everysport.GetCompetitionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.everysport.Manage.GetCompetition is not implemented"))
}

func (UnimplementedManageHandler) GetCategory(context.Context, *connect.Request[everysport.GetCategoryRequest]) (*connect.Response[everysport.GetCategoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.everysport.Manage.GetCategory is not implemented"))
}

func (UnimplementedManageHandler) UpdateSport(context.Context, *connect.Request[everysport.UpdateSportRequest]) (*connect.Response[everysport.UpdateSportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.everysport.Manage.UpdateSport is not implemented"))
}

func (UnimplementedManageHandler) UpdateCompetition(context.Context, *connect.Request[everysport.UpdateCompetitionRequest]) (*connect.Response[everysport.UpdateCompetitionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.everysport.Manage.UpdateCompetition is not implemented"))
}

func (UnimplementedManageHandler) UpdateCategory(context.Context, *connect.Request[everysport.UpdateCategoryRequest]) (*connect.Response[everysport.UpdateCategoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.everysport.Manage.UpdateCategory is not implemented"))
}

func (UnimplementedManageHandler) ApplyDefaults(context.Context, *connect.Request[everysport.ApplyDefaultsRequest]) (*connect.Response[everysport.ApplyDefaultsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.everysport.Manage.ApplyDefaults is not implemented"))
}

func (UnimplementedManageHandler) ExportConfig(context.Context, *connect.Request[everysport.ExportConfigRequest]) (*connect.Response[everysport.ExportConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.everysport.Manage.ExportConfig is not implemented"))
}

func (UnimplementedManageHandler) ListPendingImports(context.Context, *connect.Request[everysport.ListPendingImportsRequest]) (*connect.Response[everysport.ListPendingImportsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.everysport.Manage.ListPendingImports is not implemented"))
}

func (UnimplementedManageHandler) ReviewCompetitions(context.Context, *connect.Request[everysport.ReviewCompetitionsRequest]) (*connect.Response[everysport.ReviewCompetitionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.everysport.Manage.ReviewCompetitions is not implemented"))
}
