// Code generated by protoc-gen-elephant-rpc. DO NOT EDIT.
//
// Source: everysport/service.proto

package everysportconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	everysport "github.com/ttab/elephant-tt-api/everysport"
	http "net/http"
)

// NewManageServiceHandler builds an HTTP handler for the ttab.everysport.Manage service from an
// implementation of the plain everysport.Manage interface, and returns the path to mount it on
// together with the handler, just like NewManageHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewManageServiceHandler(svc everysport.Manage, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewManageHandler(&manageServiceHandler{svc: svc}, opts...)
}

// manageServiceHandler implements ManageHandler on top of a everysport.Manage.
type manageServiceHandler struct {
	svc everysport.Manage
}

func (h *manageServiceHandler) ManualImport(ctx context.Context, req *connect.Request[everysport.ManualImportRequest]) (*connect.Response[everysport.ManualImportResponse], error) {
	res, err := h.svc.ManualImport(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *manageServiceHandler) ListSports(ctx context.Context, req *connect.Request[everysport.ListSportsRequest]) (*connect.Response[everysport.ListSportsResponse], error) {
	res, err := h.svc.ListSports(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *manageServiceHandler) ListCategories(ctx context.Context, req *connect.Request[everysport.ListCategoriesRequest]) (*connect.Response[everysport.ListCategoriesResponse], error) {
	res, err := h.svc.ListCategories(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *manageServiceHandler) ListCompetitions(ctx context.Context, req *connect.Request[everysport.ListCompetitionsRequest]) (*connect.Response[everysport.ListCompetitionsResponse], error) {
	res, err := h.svc.ListCompetitions(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *manageServiceHandler) GetSport(ctx context.Context, req *connect.Request[everysport.GetSportRequest]) (*connect.Response[everysport.GetSportResponse], error) {
	res, err := h.svc.GetSport(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *manageServiceHandler) GetCompetition(ctx context.Context, req *connect.Request[everysport.GetCompetitionRequest]) (*connect.Response[everysport.GetCompetitionResponse], error) {
	res, err := h.svc.GetCompetition(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *manageServiceHandler) GetCategory(ctx context.Context, req *connect.Request[everysport.GetCategoryRequest]) (*connect.Response[everysport.GetCategoryResponse], error) {
	res, err := h.svc.GetCategory(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *manageServiceHandler) UpdateSport(ctx context.Context, req *connect.Request[everysport.UpdateSportRequest]) (*connect.Response[everysport.UpdateSportResponse], error) {
	res, err := h.svc.UpdateSport(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *manageServiceHandler) UpdateCompetition(ctx context.Context, req *connect.Request[everysport.UpdateCompetitionRequest]) (*connect.Response[everysport.UpdateCompetitionResponse], error) {
	res, err := h.svc.UpdateCompetition(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *manageServiceHandler) UpdateCategory(ctx context.Context, req *connect.Request[everysport.UpdateCategoryRequest]) (*connect.Response[everysport.UpdateCategoryResponse], error) {
	res, err := h.svc.UpdateCategory(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *manageServiceHandler) ApplyDefaults(ctx context.Context, req *connect.Request[everysport.ApplyDefaultsRequest]) (*connect.Response[everysport.ApplyDefaultsResponse], error) {
	res, err := h.svc.ApplyDefaults(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *manageServiceHandler) ExportConfig(ctx context.Context, req *connect.Request[everysport.ExportConfigRequest]) (*connect.Response[everysport.ExportConfigResponse], error) {
	res, err := h.svc.ExportConfig(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *manageServiceHandler) ListPendingImports(ctx context.Context, req *connect.Request[everysport.ListPendingImportsRequest]) (*connect.Response[everysport.ListPendingImportsResponse], error) {
	res, err := h.svc.ListPendingImports(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *manageServiceHandler) ReviewCompetitions(ctx context.Context, req *connect.Request[everysport.ReviewCompetitionsRequest]) (*connect.Response[everysport.ReviewCompetitionsResponse], error) {
	res, err := h.svc.ReviewCompetitions(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewManageServiceClient constructs a client for the ttab.everysport.Manage service that implements
// the plain everysport.Manage interface, so that it is a drop-in for the Twirp clients. The options
// are the ones NewManageClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewManageServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) everysport.Manage {
	return &manageServiceClient{
		client: NewManageClient(httpClient, baseURL, opts...),
	}
}

// manageServiceClient implements everysport.Manage on top of a ManageClient.
type manageServiceClient struct {
	client ManageClient
}

func (c *manageServiceClient) ManualImport(ctx context.Context, req *everysport.ManualImportRequest) (*everysport.ManualImportResponse, error) {
	res, err := c.client.ManualImport(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *manageServiceClient) ListSports(ctx context.Context, req *everysport.ListSportsRequest) (*everysport.ListSportsResponse, error) {
	res, err := c.client.ListSports(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *manageServiceClient) ListCategories(ctx context.Context, req *everysport.ListCategoriesRequest) (*everysport.ListCategoriesResponse, error) {
	res, err := c.client.ListCategories(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *manageServiceClient) ListCompetitions(ctx context.Context, req *everysport.ListCompetitionsRequest) (*everysport.ListCompetitionsResponse, error) {
	res, err := c.client.ListCompetitions(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *manageServiceClient) GetSport(ctx context.Context, req *everysport.GetSportRequest) (*everysport.GetSportResponse, error) {
	res, err := c.client.GetSport(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *manageServiceClient) GetCompetition(ctx context.Context, req *everysport.GetCompetitionRequest) (*everysport.GetCompetitionResponse, error) {
	res, err := c.client.GetCompetition(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *manageServiceClient) GetCategory(ctx context.Context, req *everysport.GetCategoryRequest) (*everysport.GetCategoryResponse, error) {
	res, err := c.client.GetCategory(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *manageServiceClient) UpdateSport(ctx context.Context, req *everysport.UpdateSportRequest) (*everysport.UpdateSportResponse, error) {
	res, err := c.client.UpdateSport(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *manageServiceClient) UpdateCompetition(ctx context.Context, req *everysport.UpdateCompetitionRequest) (*everysport.UpdateCompetitionResponse, error) {
	res, err := c.client.UpdateCompetition(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *manageServiceClient) UpdateCategory(ctx context.Context, req *everysport.UpdateCategoryRequest) (*everysport.UpdateCategoryResponse, error) {
	res, err := c.client.UpdateCategory(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *manageServiceClient) ApplyDefaults(ctx context.Context, req *everysport.ApplyDefaultsRequest) (*everysport.ApplyDefaultsResponse, error) {
	res, err := c.client.ApplyDefaults(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *manageServiceClient) ExportConfig(ctx context.Context, req *everysport.ExportConfigRequest) (*everysport.ExportConfigResponse, error) {
	res, err := c.client.ExportConfig(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *manageServiceClient) ListPendingImports(ctx context.Context, req *everysport.ListPendingImportsRequest) (*everysport.ListPendingImportsResponse, error) {
	res, err := c.client.ListPendingImports(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *manageServiceClient) ReviewCompetitions(ctx context.Context, req *everysport.ReviewCompetitionsRequest) (*everysport.ReviewCompetitionsResponse, error) {
	res, err := c.client.ReviewCompetitions(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}
