// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v4.24.4
// source: eidos/service.proto

package eidos

import (
	newsdoc "github.com/ttab/elephant-api/newsdoc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyseDocumentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DocumentUUID is the uuid of the document to analyse, optional. Required if
	// no document is provided in the request.
	DocumentUuid string `protobuf:"bytes,1,opt,name=document_uuid,json=documentUuid,proto3" json:"document_uuid,omitempty"`
	// Document to analyse, optional.
	Document      *newsdoc.Document `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyseDocumentRequest) Reset() {
	*x = AnalyseDocumentRequest{}
	mi := &file_eidos_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyseDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyseDocumentRequest) ProtoMessage() {}

func (x *AnalyseDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eidos_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyseDocumentRequest.ProtoReflect.Descriptor instead.
func (*AnalyseDocumentRequest) Descriptor() ([]byte, []int) {
	return file_eidos_service_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyseDocumentRequest) GetDocumentUuid() string {
	if x != nil {
		return x.DocumentUuid
	}
	return ""
}

func (x *AnalyseDocumentRequest) GetDocument() *newsdoc.Document {
	if x != nil {
		return x.Document
	}
	return nil
}

type AnalyseDocumentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Meta document with the detected entities and topics.
	Meta *newsdoc.Document `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Text used in recognition query.
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyseDocumentResponse) Reset() {
	*x = AnalyseDocumentResponse{}
	mi := &file_eidos_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyseDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyseDocumentResponse) ProtoMessage() {}

func (x *AnalyseDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eidos_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyseDocumentResponse.ProtoReflect.Descriptor instead.
func (*AnalyseDocumentResponse) Descriptor() ([]byte, []int) {
	return file_eidos_service_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyseDocumentResponse) GetMeta() *newsdoc.Document {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AnalyseDocumentResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_eidos_service_proto protoreflect.FileDescriptor

var file_eidos_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x65, 0x69, 0x64, 0x6f, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x65, 0x69, 0x64, 0x6f,
	0x73, 0x1a, 0x15, 0x6e, 0x65, 0x77, 0x73, 0x64, 0x6f, 0x63, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x64,
	0x6f, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x16, 0x41, 0x6e, 0x61, 0x6c,
	0x79, 0x73, 0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x55, 0x75, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6e, 0x65, 0x77, 0x73,
	0x64, 0x6f, 0x63, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x64, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x54, 0x0a, 0x17, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73,
	0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x25, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x6e, 0x65, 0x77, 0x73, 0x64, 0x6f, 0x63, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x32, 0x64, 0x0a, 0x06,
	0x54, 0x61, 0x67, 0x67, 0x65, 0x72, 0x12, 0x5a, 0x0a, 0x0f, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73,
	0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x2e, 0x74, 0x74, 0x61, 0x62,
	0x2e, 0x65, 0x69, 0x64, 0x6f, 0x73, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x74, 0x74, 0x61, 0x62, 0x2e, 0x65, 0x69, 0x64, 0x6f, 0x73, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79,
	0x73, 0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x74, 0x74, 0x61, 0x62, 0x2f, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2d, 0x74,
	0x74, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x69, 0x64, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_eidos_service_proto_rawDescOnce sync.Once
	file_eidos_service_proto_rawDescData = file_eidos_service_proto_rawDesc
)

func file_eidos_service_proto_rawDescGZIP() []byte {
	file_eidos_service_proto_rawDescOnce.Do(func() {
		file_eidos_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_eidos_service_proto_rawDescData)
	})
	return file_eidos_service_proto_rawDescData
}

var file_eidos_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_eidos_service_proto_goTypes = []any{
	(*AnalyseDocumentRequest)(nil),  // 0: ttab.eidos.AnalyseDocumentRequest
	(*AnalyseDocumentResponse)(nil), // 1: ttab.eidos.AnalyseDocumentResponse
	(*newsdoc.Document)(nil),        // 2: newsdoc.Document
}
var file_eidos_service_proto_depIdxs = []int32{
	2, // 0: ttab.eidos.AnalyseDocumentRequest.document:type_name -> newsdoc.Document
	2, // 1: ttab.eidos.AnalyseDocumentResponse.meta:type_name -> newsdoc.Document
	0, // 2: ttab.eidos.Tagger.AnalyseDocument:input_type -> ttab.eidos.AnalyseDocumentRequest
	1, // 3: ttab.eidos.Tagger.AnalyseDocument:output_type -> ttab.eidos.AnalyseDocumentResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_eidos_service_proto_init() }
func file_eidos_service_proto_init() {
	if File_eidos_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_eidos_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eidos_service_proto_goTypes,
		DependencyIndexes: file_eidos_service_proto_depIdxs,
		MessageInfos:      file_eidos_service_proto_msgTypes,
	}.Build()
	File_eidos_service_proto = out.File
	file_eidos_service_proto_rawDesc = nil
	file_eidos_service_proto_goTypes = nil
	file_eidos_service_proto_depIdxs = nil
}
