// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: eidos/service.proto

package eidos

import (
	newsdoc "github.com/ttab/elephant-api/newsdoc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyseDocumentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DocumentUUID is the uuid of the document to analyse, optional. Required if
	// no document is provided in the request.
	DocumentUuid string `protobuf:"bytes,1,opt,name=document_uuid,json=documentUuid,proto3" json:"document_uuid,omitempty"`
	// Document to analyse, optional.
	Document      *newsdoc.Document `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyseDocumentRequest) Reset() {
	*x = AnalyseDocumentRequest{}
	mi := &file_eidos_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyseDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyseDocumentRequest) ProtoMessage() {}

func (x *AnalyseDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eidos_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyseDocumentRequest.ProtoReflect.Descriptor instead.
func (*AnalyseDocumentRequest) Descriptor() ([]byte, []int) {
	return file_eidos_service_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyseDocumentRequest) GetDocumentUuid() string {
	if x != nil {
		return x.DocumentUuid
	}
	return ""
}

func (x *AnalyseDocumentRequest) GetDocument() *newsdoc.Document {
	if x != nil {
		return x.Document
	}
	return nil
}

type AnalyseDocumentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Meta document with the detected entities and topics.
	Meta *newsdoc.Document `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Text used in recognition query.
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyseDocumentResponse) Reset() {
	*x = AnalyseDocumentResponse{}
	mi := &file_eidos_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyseDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyseDocumentResponse) ProtoMessage() {}

func (x *AnalyseDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eidos_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyseDocumentResponse.ProtoReflect.Descriptor instead.
func (*AnalyseDocumentResponse) Descriptor() ([]byte, []int) {
	return file_eidos_service_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyseDocumentResponse) GetMeta() *newsdoc.Document {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AnalyseDocumentResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type RegisterUsageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ContentType of the media that was tagged.
	ContentType string `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// ContentURI is an URI that identified the tagged media.
	ContextUri string `protobuf:"bytes,2,opt,name=context_uri,json=contextUri,proto3" json:"context_uri,omitempty"`
	// The UUIDs of the entities that were used.
	EntityUuids   []string `protobuf:"bytes,3,rep,name=entity_uuids,json=entityUuids,proto3" json:"entity_uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUsageRequest) Reset() {
	*x = RegisterUsageRequest{}
	mi := &file_eidos_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUsageRequest) ProtoMessage() {}

func (x *RegisterUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eidos_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUsageRequest.ProtoReflect.Descriptor instead.
func (*RegisterUsageRequest) Descriptor() ([]byte, []int) {
	return file_eidos_service_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterUsageRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *RegisterUsageRequest) GetContextUri() string {
	if x != nil {
		return x.ContextUri
	}
	return ""
}

func (x *RegisterUsageRequest) GetEntityUuids() []string {
	if x != nil {
		return x.EntityUuids
	}
	return nil
}

type RegisterUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUsageResponse) Reset() {
	*x = RegisterUsageResponse{}
	mi := &file_eidos_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUsageResponse) ProtoMessage() {}

func (x *RegisterUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eidos_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUsageResponse.ProtoReflect.Descriptor instead.
func (*RegisterUsageResponse) Descriptor() ([]byte, []int) {
	return file_eidos_service_proto_rawDescGZIP(), []int{3}
}

var File_eidos_service_proto protoreflect.FileDescriptor

const file_eidos_service_proto_rawDesc = "" +
	"\n" +
	"\x13eidos/service.proto\x12\n" +
	"ttab.eidos\x1a\x15newsdoc/newsdoc.proto\"l\n" +
	"\x16AnalyseDocumentRequest\x12#\n" +
	"\rdocument_uuid\x18\x01 \x01(\tR\fdocumentUuid\x12-\n" +
	"\bdocument\x18\x02 \x01(\v2\x11.newsdoc.DocumentR\bdocument\"T\n" +
	"\x17AnalyseDocumentResponse\x12%\n" +
	"\x04meta\x18\x01 \x01(\v2\x11.newsdoc.DocumentR\x04meta\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"}\n" +
	"\x14RegisterUsageRequest\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12\x1f\n" +
	"\vcontext_uri\x18\x02 \x01(\tR\n" +
	"contextUri\x12!\n" +
	"\fentity_uuids\x18\x03 \x03(\tR\ventityUuids\"\x17\n" +
	"\x15RegisterUsageResponse2\xba\x01\n" +
	"\x06Tagger\x12Z\n" +
	"\x0fAnalyseDocument\x12\".ttab.eidos.AnalyseDocumentRequest\x1a#.ttab.eidos.AnalyseDocumentResponse\x12T\n" +
	"\rRegisterUsage\x12 .ttab.eidos.RegisterUsageRequest\x1a!.ttab.eidos.RegisterUsageResponseB'Z%github.com/ttab/elephant-tt-api/eidosb\x06proto3"

var (
	file_eidos_service_proto_rawDescOnce sync.Once
	file_eidos_service_proto_rawDescData []byte
)

func file_eidos_service_proto_rawDescGZIP() []byte {
	file_eidos_service_proto_rawDescOnce.Do(func() {
		file_eidos_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eidos_service_proto_rawDesc), len(file_eidos_service_proto_rawDesc)))
	})
	return file_eidos_service_proto_rawDescData
}

var file_eidos_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_eidos_service_proto_goTypes = []any{
	(*AnalyseDocumentRequest)(nil),  // 0: ttab.eidos.AnalyseDocumentRequest
	(*AnalyseDocumentResponse)(nil), // 1: ttab.eidos.AnalyseDocumentResponse
	(*RegisterUsageRequest)(nil),    // 2: ttab.eidos.RegisterUsageRequest
	(*RegisterUsageResponse)(nil),   // 3: ttab.eidos.RegisterUsageResponse
	(*newsdoc.Document)(nil),        // 4: newsdoc.Document
}
var file_eidos_service_proto_depIdxs = []int32{
	4, // 0: ttab.eidos.AnalyseDocumentRequest.document:type_name -> newsdoc.Document
	4, // 1: ttab.eidos.AnalyseDocumentResponse.meta:type_name -> newsdoc.Document
	0, // 2: ttab.eidos.Tagger.AnalyseDocument:input_type -> ttab.eidos.AnalyseDocumentRequest
	2, // 3: ttab.eidos.Tagger.RegisterUsage:input_type -> ttab.eidos.RegisterUsageRequest
	1, // 4: ttab.eidos.Tagger.AnalyseDocument:output_type -> ttab.eidos.AnalyseDocumentResponse
	3, // 5: ttab.eidos.Tagger.RegisterUsage:output_type -> ttab.eidos.RegisterUsageResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_eidos_service_proto_init() }
func file_eidos_service_proto_init() {
	if File_eidos_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eidos_service_proto_rawDesc), len(file_eidos_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eidos_service_proto_goTypes,
		DependencyIndexes: file_eidos_service_proto_depIdxs,
		MessageInfos:      file_eidos_service_proto_msgTypes,
	}.Build()
	File_eidos_service_proto = out.File
	file_eidos_service_proto_goTypes = nil
	file_eidos_service_proto_depIdxs = nil
}
