// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: eidos/service.proto

package eidosconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	eidos "github.com/ttab/elephant-tt-api/eidos"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TaggerName is the fully-qualified name of the Tagger service.
	TaggerName = "ttab.eidos.Tagger"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TaggerAnalyseDocumentProcedure is the fully-qualified name of the Tagger's AnalyseDocument RPC.
	TaggerAnalyseDocumentProcedure = "/ttab.eidos.Tagger/AnalyseDocument"
	// TaggerRegisterUsageProcedure is the fully-qualified name of the Tagger's RegisterUsage RPC.
	TaggerRegisterUsageProcedure = "/ttab.eidos.Tagger/RegisterUsage"
)

// TaggerClient is a client for the ttab.eidos.Tagger service.
type TaggerClient interface {
	// AnalyseDocument and return the generated meta document and the text
	// representatin of the document that was used for analysis.
	AnalyseDocument(context.Context, *connect.Request[eidos.AnalyseDocumentRequest]) (*connect.Response[eidos.AnalyseDocumentResponse], error)
	// RegisterUsage is used to inform eidos when an external system has tagged a
	// piece of media with entities managed by eidos.
	RegisterUsage(context.Context, *connect.Request[eidos.RegisterUsageRequest]) (*connect.Response[eidos.RegisterUsageResponse], error)
}

// NewTaggerClient constructs a client for the ttab.eidos.Tagger service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTaggerClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TaggerClient {
	baseURL = strings.TrimRight(baseURL, "/")
	taggerMethods := eidos.File_eidos_service_proto.Services().ByName("Tagger").Methods()
	return &taggerClient{
		analyseDocument: connect.NewClient[eidos.AnalyseDocumentRequest, eidos.AnalyseDocumentResponse](
			httpClient,
			baseURL+TaggerAnalyseDocumentProcedure,
			connect.WithSchema(taggerMethods.ByName("AnalyseDocument")),
			connect.WithClientOptions(opts...),
		),
		registerUsage: connect.NewClient[eidos.RegisterUsageRequest, eidos.RegisterUsageResponse](
			httpClient,
			baseURL+TaggerRegisterUsageProcedure,
			connect.WithSchema(taggerMethods.ByName("RegisterUsage")),
			connect.WithClientOptions(opts...),
		),
	}
}

// taggerClient implements TaggerClient.
type taggerClient struct {
	analyseDocument *connect.Client[eidos.AnalyseDocumentRequest, eidos.AnalyseDocumentResponse]
	registerUsage   *connect.Client[eidos.RegisterUsageRequest, eidos.RegisterUsageResponse]
}

// AnalyseDocument calls ttab.eidos.Tagger.AnalyseDocument.
func (c *taggerClient) AnalyseDocument(ctx context.Context, req *connect.Request[eidos.AnalyseDocumentRequest]) (*connect.Response[eidos.AnalyseDocumentResponse], error) {
	return c.analyseDocument.CallUnary(ctx, req)
}

// RegisterUsage calls ttab.eidos.Tagger.RegisterUsage.
func (c *taggerClient) RegisterUsage(ctx context.Context, req *connect.Request[eidos.RegisterUsageRequest]) (*connect.Response[eidos.RegisterUsageResponse], error) {
	return c.registerUsage.CallUnary(ctx, req)
}

// TaggerHandler is an implementation of the ttab.eidos.Tagger service.
type TaggerHandler interface {
	// AnalyseDocument and return the generated meta document and the text
	// representatin of the document that was used for analysis.
	AnalyseDocument(context.Context, *connect.Request[eidos.AnalyseDocumentRequest]) (*connect.Response[eidos.AnalyseDocumentResponse], error)
	// RegisterUsage is used to inform eidos when an external system has tagged a
	// piece of media with entities managed by eidos.
	RegisterUsage(context.Context, *connect.Request[eidos.RegisterUsageRequest]) (*connect.Response[eidos.RegisterUsageResponse], error)
}

// NewTaggerHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTaggerHandler(svc TaggerHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	taggerMethods := eidos.File_eidos_service_proto.Services().ByName("Tagger").Methods()
	taggerAnalyseDocumentHandler := connect.NewUnaryHandler(
		TaggerAnalyseDocumentProcedure,
		svc.AnalyseDocument,
		connect.WithSchema(taggerMethods.ByName("AnalyseDocument")),
		connect.WithHandlerOptions(opts...),
	)
	taggerRegisterUsageHandler := connect.NewUnaryHandler(
		TaggerRegisterUsageProcedure,
		svc.RegisterUsage,
		connect.WithSchema(taggerMethods.ByName("RegisterUsage")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ttab.eidos.Tagger/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TaggerAnalyseDocumentProcedure:
			taggerAnalyseDocumentHandler.ServeHTTP(w, r)
		case TaggerRegisterUsageProcedure:
			taggerRegisterUsageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTaggerHandler returns CodeUnimplemented from all methods.
type UnimplementedTaggerHandler struct{}

func (UnimplementedTaggerHandler) AnalyseDocument(context.Context, *connect.Request[eidos.AnalyseDocumentRequest]) (*connect.Response[eidos.AnalyseDocumentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.eidos.Tagger.AnalyseDocument is not implemented"))
}

func (UnimplementedTaggerHandler) RegisterUsage(context.Context, *connect.Request[eidos.RegisterUsageRequest]) (*connect.Response[eidos.RegisterUsageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ttab.eidos.Tagger.RegisterUsage is not implemented"))
}
