// Code generated by protoc-gen-elephant-rpc. DO NOT EDIT.
//
// Source: eidos/service.proto

package eidosconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	eidos "github.com/ttab/elephant-tt-api/eidos"
	http "net/http"
)

// NewTaggerServiceHandler builds an HTTP handler for the ttab.eidos.Tagger service from an
// implementation of the plain eidos.Tagger interface, and returns the path to mount it on together
// with the handler, just like NewTaggerHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewTaggerServiceHandler(svc eidos.Tagger, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewTaggerHandler(&taggerServiceHandler{svc: svc}, opts...)
}

// taggerServiceHandler implements TaggerHandler on top of a eidos.Tagger.
type taggerServiceHandler struct {
	svc eidos.Tagger
}

func (h *taggerServiceHandler) AnalyseDocument(ctx context.Context, req *connect.Request[eidos.AnalyseDocumentRequest]) (*connect.Response[eidos.AnalyseDocumentResponse], error) {
	res, err := h.svc.AnalyseDocument(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *taggerServiceHandler) RegisterUsage(ctx context.Context, req *connect.Request[eidos.RegisterUsageRequest]) (*connect.Response[eidos.RegisterUsageResponse], error) {
	res, err := h.svc.RegisterUsage(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewTaggerServiceClient constructs a client for the ttab.eidos.Tagger service that implements the
// plain eidos.Tagger interface, so that it is a drop-in for the Twirp clients. The options are the
// ones NewTaggerClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewTaggerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) eidos.Tagger {
	return &taggerServiceClient{
		client: NewTaggerClient(httpClient, baseURL, opts...),
	}
}

// taggerServiceClient implements eidos.Tagger on top of a TaggerClient.
type taggerServiceClient struct {
	client TaggerClient
}

func (c *taggerServiceClient) AnalyseDocument(ctx context.Context, req *eidos.AnalyseDocumentRequest) (*eidos.AnalyseDocumentResponse, error) {
	res, err := c.client.AnalyseDocument(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *taggerServiceClient) RegisterUsage(ctx context.Context, req *eidos.RegisterUsageRequest) (*eidos.RegisterUsageResponse, error) {
	res, err := c.client.RegisterUsage(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}
